// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go
//
// Generated by this command:
//
//	mockgen -source=manager.go -destination=mock_manager.go -package=volume
//

// Package volume is a generated GoMock package.
package volume

import (
	context "context"

	vsr "github.com/vanus-labs/vanus/api/vsr"
	kv "github.com/vanus-labs/vanus/pkg/kv"
	metadata "github.com/vanus-labs/vanus/server/controller/eventbus/metadata"
	server "github.com/vanus-labs/vanus/server/controller/eventbus/server"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	_ = "STUB: not implemented"

	// GetAllActiveVolumes mocks base method.
	return nil
}

func (m *MockManager) GetAllActiveVolumes() []server.Instance {
	_ = "STUB: not implemented"
	return nil
}

// GetAllActiveVolumes indicates an expected call of GetAllActiveVolumes.
func (mr *MockManagerMockRecorder) GetAllActiveVolumes() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBlocksOfVolume mocks base method.
func (m *MockManager) GetBlocksOfVolume(ctx context.Context, instance server.Instance) (map[uint64]*metadata.Block, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetBlocksOfVolume indicates an expected call of GetBlocksOfVolume.
func (mr *MockManagerMockRecorder) GetBlocksOfVolume(ctx, instance any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetVolumeInstanceByID mocks base method.
func (m *MockManager) GetVolumeInstanceByID(id vsr.ID) server.Instance {
	_ = "STUB: not implemented"
	return *new(server.Instance)
}

// GetVolumeInstanceByID indicates an expected call of GetVolumeInstanceByID.
func (mr *MockManagerMockRecorder) GetVolumeInstanceByID(id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Init mocks base method.
func (m *MockManager) Init(ctx context.Context, kvClient kv.Client) error {
	_ = "STUB: not implemented"
	return nil
}

// Init indicates an expected call of Init.
func (mr *MockManagerMockRecorder) Init(ctx, kvClient any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LookupVolumeByID mocks base method.
func (m *MockManager) LookupVolumeByID(id uint64) server.Instance {
	_ = "STUB: not implemented"
	return *new(server.Instance)
}

// LookupVolumeByID indicates an expected call of LookupVolumeByID.
func (mr *MockManagerMockRecorder) LookupVolumeByID(id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterVolume mocks base method.
func (m *MockManager) RegisterVolume(ctx context.Context, md *metadata.VolumeMetadata) (server.Instance, error) {
	_ = "STUB: not implemented"
	return *new(server.Instance), nil
}

// RegisterVolume indicates an expected call of RegisterVolume.
func (mr *MockManagerMockRecorder) RegisterVolume(ctx, md any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateRouting mocks base method.
func (m *MockManager) UpdateRouting(ctx context.Context, ins server.Instance, srv server.Server) {
	_ = "STUB: not implemented"
	return
}

// UpdateRouting indicates an expected call of UpdateRouting.
func (mr *MockManagerMockRecorder) UpdateRouting(ctx, ins, srv any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
