// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go
//
// Generated by this command:
//
//	mockgen -source=manager.go -destination=mock_manager.go -package=server
//

// Package server is a generated GoMock package.
package server

import (
	context "context"
	time "time"

	segment "github.com/vanus-labs/vanus/api/segment"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	_ = "STUB: not implemented"

	// AddServer mocks base method.
	return nil
}

func (m *MockManager) AddServer(ctx context.Context, srv Server) error {
	_ = "STUB: not implemented"
	return nil
}

// AddServer indicates an expected call of AddServer.
func (mr *MockManagerMockRecorder) AddServer(ctx, srv any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CanCreateEventbus mocks base method.
func (m *MockManager) CanCreateEventbus(ctx context.Context, replicaNum int) bool {
	_ = "STUB: not implemented"
	return false
}

// CanCreateEventbus indicates an expected call of CanCreateEventbus.
func (mr *MockManagerMockRecorder) CanCreateEventbus(ctx, replicaNum any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetServerByAddress mocks base method.
func (m *MockManager) GetServerByAddress(addr string) Server {
	_ = "STUB: not implemented"
	return *new(Server)
}

// GetServerByAddress indicates an expected call of GetServerByAddress.
func (mr *MockManagerMockRecorder) GetServerByAddress(addr any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetServerByVolumeID mocks base method.
func (m *MockManager) GetServerByVolumeID(id uint64) Server {
	_ = "STUB: not implemented"
	return *new(Server)
}

// GetServerByVolumeID indicates an expected call of GetServerByVolumeID.
func (mr *MockManagerMockRecorder) GetServerByVolumeID(id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoveServer mocks base method.
func (m *MockManager) RemoveServer(ctx context.Context, srv Server) error {
	_ = "STUB: not implemented"
	return nil
}

// RemoveServer indicates an expected call of RemoveServer.
func (mr *MockManagerMockRecorder) RemoveServer(ctx, srv any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Run mocks base method.
func (m *MockManager) Run(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// Run indicates an expected call of Run.
func (mr *MockManagerMockRecorder) Run(ctx any) *gomock.Call { _ = "STUB: not implemented"; return nil }

// Stop mocks base method.
func (m *MockManager) Stop(ctx context.Context) { _ = "STUB: not implemented"; return }

// Stop indicates an expected call of Stop.
func (mr *MockManagerMockRecorder) Stop(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockServer is a mock of Server interface.
type MockServer struct {
	ctrl     *gomock.Controller
	recorder *MockServerMockRecorder
}

// MockServerMockRecorder is the mock recorder for MockServer.
type MockServerMockRecorder struct {
	mock *MockServer
}

// NewMockServer creates a new mock instance.
func NewMockServer(ctrl *gomock.Controller) *MockServer { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServer) EXPECT() *MockServerMockRecorder {
	_ = "STUB: not implemented"

	// Address mocks base method.
	return nil
}

func (m *MockServer) Address() string { _ = "STUB: not implemented"; return "" }

// Address indicates an expected call of Address.
func (mr *MockServerMockRecorder) Address() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Close mocks base method.
func (m *MockServer) Close() error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockServerMockRecorder) Close() *gomock.Call { _ = "STUB: not implemented"; return nil }

// GetClient mocks base method.
func (m *MockServer) GetClient() segment.SegmentServerClient {
	_ = "STUB: not implemented"
	return *new(segment.SegmentServerClient)
}

// GetClient indicates an expected call of GetClient.
func (mr *MockServerMockRecorder) GetClient() *gomock.Call { _ = "STUB: not implemented"; return nil }

// IsActive mocks base method.
func (m *MockServer) IsActive(ctx context.Context) bool { _ = "STUB: not implemented"; return false }

// IsActive indicates an expected call of IsActive.
func (mr *MockServerMockRecorder) IsActive(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Polish mocks base method.
func (m *MockServer) Polish() { _ = "STUB: not implemented"; return }

// Polish indicates an expected call of Polish.
func (mr *MockServerMockRecorder) Polish() *gomock.Call { _ = "STUB: not implemented"; return nil }

// RemoteStart mocks base method.
func (m *MockServer) RemoteStart(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// RemoteStart indicates an expected call of RemoteStart.
func (mr *MockServerMockRecorder) RemoteStart(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoteStop mocks base method.
func (m *MockServer) RemoteStop(ctx context.Context) { _ = "STUB: not implemented"; return }

// RemoteStop indicates an expected call of RemoteStop.
func (mr *MockServerMockRecorder) RemoteStop(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Uptime mocks base method.
func (m *MockServer) Uptime() time.Time { _ = "STUB: not implemented"; return *new(time.Time) }

// Uptime indicates an expected call of Uptime.
func (mr *MockServerMockRecorder) Uptime() *gomock.Call { _ = "STUB: not implemented"; return nil }

// VolumeID mocks base method.
func (m *MockServer) VolumeID() uint64 { _ = "STUB: not implemented"; return 0 }

// VolumeID indicates an expected call of VolumeID.
func (mr *MockServerMockRecorder) VolumeID() *gomock.Call { _ = "STUB: not implemented"; return nil }
