// Code generated by MockGen. DO NOT EDIT.
// Source: offset.go
//
// Generated by this command:
//
//	mockgen -source=offset.go -destination=mock_offset.go -package=offset
//

// Package offset is a generated GoMock package.
package offset

import (
	context "context"

	vsr "github.com/vanus-labs/vanus/api/vsr"
	info "github.com/vanus-labs/vanus/pkg/info"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	_ = "STUB: not implemented"

	// GetOffset mocks base method.
	return nil
}

func (m *MockManager) GetOffset(ctx context.Context, subscriptionID vsr.ID) (info.ListOffsetInfo, error) {
	_ = "STUB: not implemented"
	return *new(info.ListOffsetInfo), nil
}

// GetOffset indicates an expected call of GetOffset.
func (mr *MockManagerMockRecorder) GetOffset(ctx, subscriptionID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Offset mocks base method.
func (m *MockManager) Offset(ctx context.Context, subscriptionID vsr.ID, offsets info.ListOffsetInfo, commit bool) error {
	_ = "STUB: not implemented"
	return nil
}

// Offset indicates an expected call of Offset.
func (mr *MockManagerMockRecorder) Offset(ctx, subscriptionID, offsets, commit any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoveRegisterSubscription mocks base method.
func (m *MockManager) RemoveRegisterSubscription(ctx context.Context, id vsr.ID) error {
	_ = "STUB: not implemented"
	return nil
}

// RemoveRegisterSubscription indicates an expected call of RemoveRegisterSubscription.
func (mr *MockManagerMockRecorder) RemoveRegisterSubscription(ctx, id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Start mocks base method.
func (m *MockManager) Start() { _ = "STUB: not implemented"; return }

// Start indicates an expected call of Start.
func (mr *MockManagerMockRecorder) Start() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Stop mocks base method.
func (m *MockManager) Stop() { _ = "STUB: not implemented"; return }

// Stop indicates an expected call of Stop.
func (mr *MockManagerMockRecorder) Stop() *gomock.Call { _ = "STUB: not implemented"; return nil }
