// Code generated by MockGen. DO NOT EDIT.
// Source: role.go
//
// Generated by this command:
//
//	mockgen -source=role.go -destination=mock_role.go -package=manager
//

// Package manager is a generated GoMock package.
package manager

import (
	context "context"

	vsr "github.com/vanus-labs/vanus/api/vsr"
	metadata "github.com/vanus-labs/vanus/server/controller/tenant/metadata"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRoleManager is a mock of UserRoleManager interface.
type MockUserRoleManager struct {
	ctrl     *gomock.Controller
	recorder *MockUserRoleManagerMockRecorder
}

// MockUserRoleManagerMockRecorder is the mock recorder for MockUserRoleManager.
type MockUserRoleManagerMockRecorder struct {
	mock *MockUserRoleManager
}

// NewMockUserRoleManager creates a new mock instance.
func NewMockUserRoleManager(ctrl *gomock.Controller) *MockUserRoleManager {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRoleManager) EXPECT() *MockUserRoleManagerMockRecorder {
	_ = "STUB: not implemented"

	// AddUserRole mocks base method.
	return nil
}

func (m *MockUserRoleManager) AddUserRole(ctx context.Context, role *metadata.UserRole) error {
	_ = "STUB: not implemented"
	return nil
}

// AddUserRole indicates an expected call of AddUserRole.
func (mr *MockUserRoleManagerMockRecorder) AddUserRole(ctx, role any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteUserRole mocks base method.
func (m *MockUserRoleManager) DeleteUserRole(ctx context.Context, role *metadata.UserRole) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteUserRole indicates an expected call of DeleteUserRole.
func (mr *MockUserRoleManagerMockRecorder) DeleteUserRole(ctx, role any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUserRoleByResourceID mocks base method.
func (m *MockUserRoleManager) GetUserRoleByResourceID(ctx context.Context, resourceID vsr.ID) ([]*metadata.UserRole, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUserRoleByResourceID indicates an expected call of GetUserRoleByResourceID.
func (mr *MockUserRoleManagerMockRecorder) GetUserRoleByResourceID(ctx, resourceID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUserRoleByUser mocks base method.
func (m *MockUserRoleManager) GetUserRoleByUser(ctx context.Context, userIdentifier string) ([]*metadata.UserRole, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUserRoleByUser indicates an expected call of GetUserRoleByUser.
func (mr *MockUserRoleManagerMockRecorder) GetUserRoleByUser(ctx, userIdentifier any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Init mocks base method.
func (m *MockUserRoleManager) Init(ctx context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// Init indicates an expected call of Init.
func (mr *MockUserRoleManagerMockRecorder) Init(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsUserRoleExist mocks base method.
func (m *MockUserRoleManager) IsUserRoleExist(ctx context.Context, role *metadata.UserRole) bool {
	_ = "STUB: not implemented"
	return false
}

// IsUserRoleExist indicates an expected call of IsUserRoleExist.
func (mr *MockUserRoleManagerMockRecorder) IsUserRoleExist(ctx, role any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
