// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client.go -package=kv
//

// Package kv is a generated GoMock package.
package kv

import (
	context "context"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	_ = "STUB: not implemented"

	// Close mocks base method.
	return nil
}

func (m *MockClient) Close() error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call { _ = "STUB: not implemented"; return nil }

// CompareAndDelete mocks base method.
func (m *MockClient) CompareAndDelete(ctx context.Context, key string, preValue []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// CompareAndDelete indicates an expected call of CompareAndDelete.
func (mr *MockClientMockRecorder) CompareAndDelete(ctx, key, preValue any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CompareAndSwap mocks base method.
func (m *MockClient) CompareAndSwap(ctx context.Context, key string, preValue, value []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// CompareAndSwap indicates an expected call of CompareAndSwap.
func (mr *MockClientMockRecorder) CompareAndSwap(ctx, key, preValue, value any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Create mocks base method.
func (m *MockClient) Create(ctx context.Context, key string, value []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Create indicates an expected call of Create.
func (mr *MockClientMockRecorder) Create(ctx, key, value any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Delete mocks base method.
func (m *MockClient) Delete(ctx context.Context, key string) error {
	_ = "STUB: not implemented"
	return nil
}

// Delete indicates an expected call of Delete.
func (mr *MockClientMockRecorder) Delete(ctx, key any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteDir mocks base method.
func (m *MockClient) DeleteDir(ctx context.Context, path string) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteDir indicates an expected call of DeleteDir.
func (mr *MockClientMockRecorder) DeleteDir(ctx, path any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Exists mocks base method.
func (m *MockClient) Exists(ctx context.Context, key string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// Exists indicates an expected call of Exists.
func (mr *MockClientMockRecorder) Exists(ctx, key any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Get mocks base method.
func (m *MockClient) Get(ctx context.Context, key string) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Get indicates an expected call of Get.
func (mr *MockClientMockRecorder) Get(ctx, key any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// List mocks base method.
func (m *MockClient) List(ctx context.Context, path string) ([]Pair, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// List indicates an expected call of List.
func (mr *MockClientMockRecorder) List(ctx, path any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Set mocks base method.
func (m *MockClient) Set(ctx context.Context, key string, value []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Set indicates an expected call of Set.
func (mr *MockClientMockRecorder) Set(ctx, key, value any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetWithTTL mocks base method.
func (m *MockClient) SetWithTTL(ctx context.Context, key string, value []byte, ttl time.Duration) error {
	_ = "STUB: not implemented"
	return nil
}

// SetWithTTL indicates an expected call of SetWithTTL.
func (mr *MockClientMockRecorder) SetWithTTL(ctx, key, value, ttl any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Update mocks base method.
func (m *MockClient) Update(ctx context.Context, key string, value []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// Update indicates an expected call of Update.
func (mr *MockClientMockRecorder) Update(ctx, key, value any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Watch mocks base method.
func (m *MockClient) Watch(ctx context.Context, key string, stopCh <-chan struct{}) (chan Pair, chan error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Watch indicates an expected call of Watch.
func (mr *MockClientMockRecorder) Watch(ctx, key, stopCh any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WatchTree mocks base method.
func (m *MockClient) WatchTree(ctx context.Context, path string, stopCh <-chan struct{}) (chan Pair, chan error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// WatchTree indicates an expected call of WatchTree.
func (mr *MockClientMockRecorder) WatchTree(ctx, path, stopCh any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
