// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=mock_storage.go -package=secret
//

// Package secret is a generated GoMock package.
package secret

import (
	context "context"

	vsr "github.com/vanus-labs/vanus/api/vsr"
	pkg "github.com/vanus-labs/vanus/pkg"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	_ = "STUB: not implemented"

	// Delete mocks base method.
	return nil
}

func (m *MockStorage) Delete(ctx context.Context, subID vsr.ID) error {
	_ = "STUB: not implemented"
	return nil
}

// Delete indicates an expected call of Delete.
func (mr *MockStorageMockRecorder) Delete(ctx, subID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Read mocks base method.
func (m *MockStorage) Read(ctx context.Context, subID vsr.ID, credentialType pkg.CredentialType) (pkg.SinkCredential, error) {
	_ = "STUB: not implemented"
	return *new(pkg.SinkCredential), nil
}

// Read indicates an expected call of Read.
func (mr *MockStorageMockRecorder) Read(ctx, subID, credentialType any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Write mocks base method.
func (m *MockStorage) Write(ctx context.Context, subID vsr.ID, credential pkg.SinkCredential) error {
	_ = "STUB: not implemented"
	return nil
}

// Write indicates an expected call of Write.
func (mr *MockStorageMockRecorder) Write(ctx, subID, credential any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
