// Copyright 2022 Linkall Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: vanus/core/segment/segment.proto

package segment

import (
	context "context"

	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SegmentServer_Start_FullMethodName               = "/vanus.core.segment.SegmentServer/Start"
	SegmentServer_Stop_FullMethodName                = "/vanus.core.segment.SegmentServer/Stop"
	SegmentServer_CreateBlock_FullMethodName         = "/vanus.core.segment.SegmentServer/CreateBlock"
	SegmentServer_RemoveBlock_FullMethodName         = "/vanus.core.segment.SegmentServer/RemoveBlock"
	SegmentServer_DescribeBlock_FullMethodName       = "/vanus.core.segment.SegmentServer/DescribeBlock"
	SegmentServer_ActivateSegment_FullMethodName     = "/vanus.core.segment.SegmentServer/ActivateSegment"
	SegmentServer_InactivateSegment_FullMethodName   = "/vanus.core.segment.SegmentServer/InactivateSegment"
	SegmentServer_AppendToBlock_FullMethodName       = "/vanus.core.segment.SegmentServer/AppendToBlock"
	SegmentServer_ReadFromBlock_FullMethodName       = "/vanus.core.segment.SegmentServer/ReadFromBlock"
	SegmentServer_LookupOffsetInBlock_FullMethodName = "/vanus.core.segment.SegmentServer/LookupOffsetInBlock"
	SegmentServer_Status_FullMethodName              = "/vanus.core.segment.SegmentServer/Status"
)

// SegmentServerClient is the client API for SegmentServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SegmentServerClient interface {
	Start(ctx context.Context, in *StartSegmentServerRequest, opts ...grpc.CallOption) (*StartSegmentServerResponse, error)
	Stop(ctx context.Context, in *StopSegmentServerRequest, opts ...grpc.CallOption) (*StopSegmentServerResponse, error)
	CreateBlock(ctx context.Context, in *CreateBlockRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveBlock(ctx context.Context, in *RemoveBlockRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DescribeBlock(ctx context.Context, in *DescribeBlockRequest, opts ...grpc.CallOption) (*DescribeBlockResponse, error)
	ActivateSegment(ctx context.Context, in *ActivateSegmentRequest, opts ...grpc.CallOption) (*ActivateSegmentResponse, error)
	InactivateSegment(ctx context.Context, in *InactivateSegmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AppendToBlock(ctx context.Context, in *AppendToBlockRequest, opts ...grpc.CallOption) (*AppendToBlockResponse, error)
	ReadFromBlock(ctx context.Context, in *ReadFromBlockRequest, opts ...grpc.CallOption) (*ReadFromBlockResponse, error)
	LookupOffsetInBlock(ctx context.Context, in *LookupOffsetInBlockRequest, opts ...grpc.CallOption) (*LookupOffsetInBlockResponse, error)
	Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusResponse, error)
}

type segmentServerClient struct {
	cc grpc.ClientConnInterface
}

func NewSegmentServerClient(cc grpc.ClientConnInterface) SegmentServerClient {
	_ = "STUB: not implemented"
	return *new(SegmentServerClient)
}

func (c *segmentServerClient) Start(ctx context.Context, in *StartSegmentServerRequest, opts ...grpc.CallOption) (*StartSegmentServerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *segmentServerClient) Stop(ctx context.Context, in *StopSegmentServerRequest, opts ...grpc.CallOption) (*StopSegmentServerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *segmentServerClient) CreateBlock(ctx context.Context, in *CreateBlockRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *segmentServerClient) RemoveBlock(ctx context.Context, in *RemoveBlockRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *segmentServerClient) DescribeBlock(ctx context.Context, in *DescribeBlockRequest, opts ...grpc.CallOption) (*DescribeBlockResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *segmentServerClient) ActivateSegment(ctx context.Context, in *ActivateSegmentRequest, opts ...grpc.CallOption) (*ActivateSegmentResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *segmentServerClient) InactivateSegment(ctx context.Context, in *InactivateSegmentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *segmentServerClient) AppendToBlock(ctx context.Context, in *AppendToBlockRequest, opts ...grpc.CallOption) (*AppendToBlockResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *segmentServerClient) ReadFromBlock(ctx context.Context, in *ReadFromBlockRequest, opts ...grpc.CallOption) (*ReadFromBlockResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *segmentServerClient) LookupOffsetInBlock(ctx context.Context, in *LookupOffsetInBlockRequest, opts ...grpc.CallOption) (*LookupOffsetInBlockResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *segmentServerClient) Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SegmentServerServer is the server API for SegmentServer service.
// All implementations should embed UnimplementedSegmentServerServer
// for forward compatibility
type SegmentServerServer interface {
	Start(context.Context, *StartSegmentServerRequest) (*StartSegmentServerResponse, error)
	Stop(context.Context, *StopSegmentServerRequest) (*StopSegmentServerResponse, error)
	CreateBlock(context.Context, *CreateBlockRequest) (*emptypb.Empty, error)
	RemoveBlock(context.Context, *RemoveBlockRequest) (*emptypb.Empty, error)
	DescribeBlock(context.Context, *DescribeBlockRequest) (*DescribeBlockResponse, error)
	ActivateSegment(context.Context, *ActivateSegmentRequest) (*ActivateSegmentResponse, error)
	InactivateSegment(context.Context, *InactivateSegmentRequest) (*emptypb.Empty, error)
	AppendToBlock(context.Context, *AppendToBlockRequest) (*AppendToBlockResponse, error)
	ReadFromBlock(context.Context, *ReadFromBlockRequest) (*ReadFromBlockResponse, error)
	LookupOffsetInBlock(context.Context, *LookupOffsetInBlockRequest) (*LookupOffsetInBlockResponse, error)
	Status(context.Context, *emptypb.Empty) (*StatusResponse, error)
}

// UnimplementedSegmentServerServer should be embedded to have forward compatible implementations.
type UnimplementedSegmentServerServer struct {
}

func (UnimplementedSegmentServerServer) Start(context.Context, *StartSegmentServerRequest) (*StartSegmentServerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSegmentServerServer) Stop(context.Context, *StopSegmentServerRequest) (*StopSegmentServerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSegmentServerServer) CreateBlock(context.Context, *CreateBlockRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSegmentServerServer) RemoveBlock(context.Context, *RemoveBlockRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSegmentServerServer) DescribeBlock(context.Context, *DescribeBlockRequest) (*DescribeBlockResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSegmentServerServer) ActivateSegment(context.Context, *ActivateSegmentRequest) (*ActivateSegmentResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSegmentServerServer) InactivateSegment(context.Context, *InactivateSegmentRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSegmentServerServer) AppendToBlock(context.Context, *AppendToBlockRequest) (*AppendToBlockResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSegmentServerServer) ReadFromBlock(context.Context, *ReadFromBlockRequest) (*ReadFromBlockResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSegmentServerServer) LookupOffsetInBlock(context.Context, *LookupOffsetInBlockRequest) (*LookupOffsetInBlockResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSegmentServerServer) Status(context.Context, *emptypb.Empty) (*StatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnsafeSegmentServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SegmentServerServer will
// result in compilation errors.
type UnsafeSegmentServerServer interface {
	mustEmbedUnimplementedSegmentServerServer()
}

func RegisterSegmentServerServer(s grpc.ServiceRegistrar, srv SegmentServerServer) {
	_ = "STUB: not implemented"
	return
}

func _SegmentServer_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _SegmentServer_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _SegmentServer_CreateBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _SegmentServer_RemoveBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _SegmentServer_DescribeBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _SegmentServer_ActivateSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _SegmentServer_InactivateSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _SegmentServer_AppendToBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _SegmentServer_ReadFromBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _SegmentServer_LookupOffsetInBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _SegmentServer_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SegmentServer_ServiceDesc is the grpc.ServiceDesc for SegmentServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SegmentServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vanus.core.segment.SegmentServer",
	HandlerType: (*SegmentServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _SegmentServer_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _SegmentServer_Stop_Handler,
		},
		{
			MethodName: "CreateBlock",
			Handler:    _SegmentServer_CreateBlock_Handler,
		},
		{
			MethodName: "RemoveBlock",
			Handler:    _SegmentServer_RemoveBlock_Handler,
		},
		{
			MethodName: "DescribeBlock",
			Handler:    _SegmentServer_DescribeBlock_Handler,
		},
		{
			MethodName: "ActivateSegment",
			Handler:    _SegmentServer_ActivateSegment_Handler,
		},
		{
			MethodName: "InactivateSegment",
			Handler:    _SegmentServer_InactivateSegment_Handler,
		},
		{
			MethodName: "AppendToBlock",
			Handler:    _SegmentServer_AppendToBlock_Handler,
		},
		{
			MethodName: "ReadFromBlock",
			Handler:    _SegmentServer_ReadFromBlock_Handler,
		},
		{
			MethodName: "LookupOffsetInBlock",
			Handler:    _SegmentServer_LookupOffsetInBlock_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _SegmentServer_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vanus/core/segment/segment.proto",
}
