// Code generated by MockGen. DO NOT EDIT.
// Source: index.go
//
// Generated by this command:
//
//	mockgen -source=index.go -destination=testing/mock_index.go -package=testing
//

// Package testing is a generated GoMock package.
package testing

import (
	gomock "go.uber.org/mock/gomock"
)

// MockIndex is a mock of Index interface.
type MockIndex struct {
	ctrl     *gomock.Controller
	recorder *MockIndexMockRecorder
}

// MockIndexMockRecorder is the mock recorder for MockIndex.
type MockIndexMockRecorder struct {
	mock *MockIndex
}

// NewMockIndex creates a new mock instance.
func NewMockIndex(ctrl *gomock.Controller) *MockIndex { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndex) EXPECT() *MockIndexMockRecorder {
	_ = "STUB: not implemented"

	// EndOffset mocks base method.
	return nil
}

func (m *MockIndex) EndOffset() int64 { _ = "STUB: not implemented"; return 0 }

// EndOffset indicates an expected call of EndOffset.
func (mr *MockIndexMockRecorder) EndOffset() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Length mocks base method.
func (m *MockIndex) Length() int32 { _ = "STUB: not implemented"; return 0 }

// Length indicates an expected call of Length.
func (mr *MockIndexMockRecorder) Length() *gomock.Call { _ = "STUB: not implemented"; return nil }

// StartOffset mocks base method.
func (m *MockIndex) StartOffset() int64 { _ = "STUB: not implemented"; return 0 }

// StartOffset indicates an expected call of StartOffset.
func (mr *MockIndexMockRecorder) StartOffset() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Stime mocks base method.
func (m *MockIndex) Stime() int64 { _ = "STUB: not implemented"; return 0 }

// Stime indicates an expected call of Stime.
func (mr *MockIndexMockRecorder) Stime() *gomock.Call { _ = "STUB: not implemented"; return nil }
