// Code generated by MockGen. DO NOT EDIT.
// Source: subscription.go
//
// Generated by this command:
//
//	mockgen -source=subscription.go -destination=mock_subscription.go -package=subscription
//

// Package subscription is a generated GoMock package.
package subscription

import (
	context "context"
	time "time"

	vsr "github.com/vanus-labs/vanus/api/vsr"
	info "github.com/vanus-labs/vanus/pkg/info"
	metadata "github.com/vanus-labs/vanus/server/controller/trigger/metadata"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	_ = "STUB: not implemented"

	// AddSubscription mocks base method.
	return nil
}

func (m *MockManager) AddSubscription(ctx context.Context, subscription *metadata.Subscription) error {
	_ = "STUB: not implemented"
	return nil
}

// AddSubscription indicates an expected call of AddSubscription.
func (mr *MockManagerMockRecorder) AddSubscription(ctx, subscription any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteSubscription mocks base method.
func (m *MockManager) DeleteSubscription(ctx context.Context, id vsr.ID) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteSubscription indicates an expected call of DeleteSubscription.
func (mr *MockManagerMockRecorder) DeleteSubscription(ctx, id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetDeadLetterOffset mocks base method.
func (m *MockManager) GetDeadLetterOffset(ctx context.Context, id vsr.ID) (uint64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// GetDeadLetterOffset indicates an expected call of GetDeadLetterOffset.
func (mr *MockManagerMockRecorder) GetDeadLetterOffset(ctx, id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetOffset mocks base method.
func (m *MockManager) GetOffset(ctx context.Context, id vsr.ID) (info.ListOffsetInfo, error) {
	_ = "STUB: not implemented"
	return *new(info.ListOffsetInfo), nil
}

// GetOffset indicates an expected call of GetOffset.
func (mr *MockManagerMockRecorder) GetOffset(ctx, id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetOrSaveOffset mocks base method.
func (m *MockManager) GetOrSaveOffset(ctx context.Context, id vsr.ID) (info.ListOffsetInfo, error) {
	_ = "STUB: not implemented"
	return *new(info.ListOffsetInfo), nil
}

// GetOrSaveOffset indicates an expected call of GetOrSaveOffset.
func (mr *MockManagerMockRecorder) GetOrSaveOffset(ctx, id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSubscription mocks base method.
func (m *MockManager) GetSubscription(ctx context.Context, id vsr.ID) *metadata.Subscription {
	_ = "STUB: not implemented"
	return nil
}

// GetSubscription indicates an expected call of GetSubscription.
func (mr *MockManagerMockRecorder) GetSubscription(ctx, id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSubscriptionByName mocks base method.
func (m *MockManager) GetSubscriptionByName(ctx context.Context, namespaceID vsr.ID, name string) *metadata.Subscription {
	_ = "STUB: not implemented"
	return nil
}

// GetSubscriptionByName indicates an expected call of GetSubscriptionByName.
func (mr *MockManagerMockRecorder) GetSubscriptionByName(ctx, namespaceID, name any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Heartbeat mocks base method.
func (m *MockManager) Heartbeat(ctx context.Context, id vsr.ID, addr string, time time.Time) error {
	_ = "STUB: not implemented"
	return nil
}

// Heartbeat indicates an expected call of Heartbeat.
func (mr *MockManagerMockRecorder) Heartbeat(ctx, id, addr, time any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Init mocks base method.
func (m *MockManager) Init(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// Init indicates an expected call of Init.
func (mr *MockManagerMockRecorder) Init(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListSubscription mocks base method.
func (m *MockManager) ListSubscription(ctx context.Context) []*metadata.Subscription {
	_ = "STUB: not implemented"
	return nil
}

// ListSubscription indicates an expected call of ListSubscription.
func (mr *MockManagerMockRecorder) ListSubscription(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResetOffsetByTimestamp mocks base method.
func (m *MockManager) ResetOffsetByTimestamp(ctx context.Context, id vsr.ID, timestamp uint64) (info.ListOffsetInfo, error) {
	_ = "STUB: not implemented"
	return *new(info.ListOffsetInfo), nil
}

// ResetOffsetByTimestamp indicates an expected call of ResetOffsetByTimestamp.
func (mr *MockManagerMockRecorder) ResetOffsetByTimestamp(ctx, id, timestamp any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SaveDeadLetterOffset mocks base method.
func (m *MockManager) SaveDeadLetterOffset(ctx context.Context, id vsr.ID, offset uint64) error {
	_ = "STUB: not implemented"
	return nil
}

// SaveDeadLetterOffset indicates an expected call of SaveDeadLetterOffset.
func (mr *MockManagerMockRecorder) SaveDeadLetterOffset(ctx, id, offset any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SaveOffset mocks base method.
func (m *MockManager) SaveOffset(ctx context.Context, id vsr.ID, offsets info.ListOffsetInfo, commit bool) error {
	_ = "STUB: not implemented"
	return nil
}

// SaveOffset indicates an expected call of SaveOffset.
func (mr *MockManagerMockRecorder) SaveOffset(ctx, id, offsets, commit any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Start mocks base method.
func (m *MockManager) Start() { _ = "STUB: not implemented"; return }

// Start indicates an expected call of Start.
func (mr *MockManagerMockRecorder) Start() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Stop mocks base method.
func (m *MockManager) Stop() { _ = "STUB: not implemented"; return }

// Stop indicates an expected call of Stop.
func (mr *MockManagerMockRecorder) Stop() *gomock.Call { _ = "STUB: not implemented"; return nil }

// UpdateSubscription mocks base method.
func (m *MockManager) UpdateSubscription(ctx context.Context, subscription *metadata.Subscription) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateSubscription indicates an expected call of UpdateSubscription.
func (mr *MockManagerMockRecorder) UpdateSubscription(ctx, subscription any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
