// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client.go -package=authorization
//

// Package authorization is a generated GoMock package.
package authorization

import (
	context "context"

	vsr "github.com/vanus-labs/vanus/api/vsr"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleClient is a mock of RoleClient interface.
type MockRoleClient struct {
	ctrl     *gomock.Controller
	recorder *MockRoleClientMockRecorder
}

// MockRoleClientMockRecorder is the mock recorder for MockRoleClient.
type MockRoleClientMockRecorder struct {
	mock *MockRoleClient
}

// NewMockRoleClient creates a new mock instance.
func NewMockRoleClient(ctrl *gomock.Controller) *MockRoleClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleClient) EXPECT() *MockRoleClientMockRecorder {
	_ = "STUB: not implemented"

	// GetUserEventbusID mocks base method.
	return nil
}

func (m *MockRoleClient) GetUserEventbusID(ctx context.Context, user string) (vsr.IDList, error) {
	_ = "STUB: not implemented"
	return *new(vsr.IDList), nil
}

// GetUserEventbusID indicates an expected call of GetUserEventbusID.
func (mr *MockRoleClientMockRecorder) GetUserEventbusID(ctx, user any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUserNamespaceID mocks base method.
func (m *MockRoleClient) GetUserNamespaceID(ctx context.Context, user string) (vsr.IDList, error) {
	_ = "STUB: not implemented"
	return *new(vsr.IDList), nil
}

// GetUserNamespaceID indicates an expected call of GetUserNamespaceID.
func (mr *MockRoleClientMockRecorder) GetUserNamespaceID(ctx, user any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUserRole mocks base method.
func (m *MockRoleClient) GetUserRole(ctx context.Context, user string) ([]*UserRole, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockRoleClientMockRecorder) GetUserRole(ctx, user any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUserSubscriptionID mocks base method.
func (m *MockRoleClient) GetUserSubscriptionID(ctx context.Context, user string) (vsr.IDList, error) {
	_ = "STUB: not implemented"
	return *new(vsr.IDList), nil
}

// GetUserSubscriptionID indicates an expected call of GetUserSubscriptionID.
func (mr *MockRoleClientMockRecorder) GetUserSubscriptionID(ctx, user any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsClusterAdmin mocks base method.
func (m *MockRoleClient) IsClusterAdmin(ctx context.Context, user string) (bool, error) {
	_ = "STUB: not implemented"
	return false, nil
}

// IsClusterAdmin indicates an expected call of IsClusterAdmin.
func (mr *MockRoleClientMockRecorder) IsClusterAdmin(ctx, user any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
