// Code generated by "stringer -type=VoteResult"; DO NOT EDIT.

package quorum

func _() {
	_ = "STUB: not implemented"
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	return
}

const _VoteResult_name = "VotePendingVoteLostVoteWon"

var _VoteResult_index = [...]uint8{0, 11, 19, 26}

func (i VoteResult) String() string { _ = "STUB: not implemented"; return "" }
