// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: raftpb/raft.proto

package raftpb

import (
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EntryType int32

const (
	EntryNormal       EntryType = 0
	EntryConfChange   EntryType = 1
	EntryConfChangeV2 EntryType = 2
)

var EntryType_name = map[int32]string{
	0: "EntryNormal",
	1: "EntryConfChange",
	2: "EntryConfChangeV2",
}

var EntryType_value = map[string]int32{
	"EntryNormal":       0,
	"EntryConfChange":   1,
	"EntryConfChangeV2": 2,
}

func (x EntryType) String() string { _ = "STUB: not implemented"; return "" }

func (EntryType) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// For description of different message types, see:
// https://pkg.go.dev/go.etcd.io/etcd/raft/v3#hdr-MessageType
type MessageType int32

const (
	MsgHup            MessageType = 0
	MsgBeat           MessageType = 1
	MsgProp           MessageType = 2
	MsgApp            MessageType = 3
	MsgAppResp        MessageType = 4
	MsgVote           MessageType = 5
	MsgVoteResp       MessageType = 6
	MsgSnap           MessageType = 7
	MsgHeartbeat      MessageType = 8
	MsgHeartbeatResp  MessageType = 9
	MsgUnreachable    MessageType = 10
	MsgSnapStatus     MessageType = 11
	MsgCheckQuorum    MessageType = 12
	MsgTransferLeader MessageType = 13
	MsgTimeoutNow     MessageType = 14
	MsgReadIndex      MessageType = 15
	MsgReadIndexResp  MessageType = 16
	MsgPreVote        MessageType = 17
	MsgPreVoteResp    MessageType = 18
	MsgLogStatus      MessageType = 19
	MsgApplyStatus    MessageType = 20
	MsgStateStatus    MessageType = 21
)

var MessageType_name = map[int32]string{
	0:  "MsgHup",
	1:  "MsgBeat",
	2:  "MsgProp",
	3:  "MsgApp",
	4:  "MsgAppResp",
	5:  "MsgVote",
	6:  "MsgVoteResp",
	7:  "MsgSnap",
	8:  "MsgHeartbeat",
	9:  "MsgHeartbeatResp",
	10: "MsgUnreachable",
	11: "MsgSnapStatus",
	12: "MsgCheckQuorum",
	13: "MsgTransferLeader",
	14: "MsgTimeoutNow",
	15: "MsgReadIndex",
	16: "MsgReadIndexResp",
	17: "MsgPreVote",
	18: "MsgPreVoteResp",
	19: "MsgLogStatus",
	20: "MsgApplyStatus",
	21: "MsgStateStatus",
}

var MessageType_value = map[string]int32{
	"MsgHup":            0,
	"MsgBeat":           1,
	"MsgProp":           2,
	"MsgApp":            3,
	"MsgAppResp":        4,
	"MsgVote":           5,
	"MsgVoteResp":       6,
	"MsgSnap":           7,
	"MsgHeartbeat":      8,
	"MsgHeartbeatResp":  9,
	"MsgUnreachable":    10,
	"MsgSnapStatus":     11,
	"MsgCheckQuorum":    12,
	"MsgTransferLeader": 13,
	"MsgTimeoutNow":     14,
	"MsgReadIndex":      15,
	"MsgReadIndexResp":  16,
	"MsgPreVote":        17,
	"MsgPreVoteResp":    18,
	"MsgLogStatus":      19,
	"MsgApplyStatus":    20,
	"MsgStateStatus":    21,
}

func (x MessageType) String() string { _ = "STUB: not implemented"; return "" }

func (MessageType) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

// ConfChangeTransition specifies the behavior of a configuration change with
// respect to joint consensus.
type ConfChangeTransition int32

const (
	// Automatically use the simple protocol if possible, otherwise fall back
	// to ConfChangeJointImplicit. Most applications will want to use this.
	ConfChangeTransitionAuto ConfChangeTransition = 0
	// Use joint consensus unconditionally, and transition out of them
	// automatically (by proposing a zero configuration change).
	//
	// This option is suitable for applications that want to minimize the time
	// spent in the joint configuration and do not store the joint configuration
	// in the state machine (outside of InitialState).
	ConfChangeTransitionJointImplicit ConfChangeTransition = 1
	// Use joint consensus and remain in the joint configuration until the
	// application proposes a no-op configuration change. This is suitable for
	// applications that want to explicitly control the transitions, for example
	// to use a custom payload (via the Context field).
	ConfChangeTransitionJointExplicit ConfChangeTransition = 2
)

var ConfChangeTransition_name = map[int32]string{
	0: "ConfChangeTransitionAuto",
	1: "ConfChangeTransitionJointImplicit",
	2: "ConfChangeTransitionJointExplicit",
}

var ConfChangeTransition_value = map[string]int32{
	"ConfChangeTransitionAuto":          0,
	"ConfChangeTransitionJointImplicit": 1,
	"ConfChangeTransitionJointExplicit": 2,
}

func (x ConfChangeTransition) String() string { _ = "STUB: not implemented"; return "" }

func (ConfChangeTransition) EnumDescriptor() ([]byte, []int) {
	_ = "STUB: not implemented"
	return nil, nil
}

type ConfChangeType int32

const (
	ConfChangeAddNode        ConfChangeType = 0
	ConfChangeRemoveNode     ConfChangeType = 1
	ConfChangeUpdateNode     ConfChangeType = 2
	ConfChangeAddLearnerNode ConfChangeType = 3
)

var ConfChangeType_name = map[int32]string{
	0: "ConfChangeAddNode",
	1: "ConfChangeRemoveNode",
	2: "ConfChangeUpdateNode",
	3: "ConfChangeAddLearnerNode",
}

var ConfChangeType_value = map[string]int32{
	"ConfChangeAddNode":        0,
	"ConfChangeRemoveNode":     1,
	"ConfChangeUpdateNode":     2,
	"ConfChangeAddLearnerNode": 3,
}

func (x ConfChangeType) String() string { _ = "STUB: not implemented"; return "" }

func (ConfChangeType) EnumDescriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

type Entry struct {
	Term     uint64    `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Index    uint64    `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Type     EntryType `protobuf:"varint,1,opt,name=type,proto3,enum=vanus.raft.EntryType" json:"type,omitempty"`
	Data     []byte    `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	NodeId   uint64    `protobuf:"varint,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PrevTerm uint64    `protobuf:"varint,6,opt,name=prev_term,json=prevTerm,proto3" json:"prev_term,omitempty"`
}

func (m *Entry) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Entry) String() string            { _ = "STUB: not implemented"; return "" }
func (*Entry) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Entry) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Entry) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Entry) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Entry) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Entry) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Entry proto.InternalMessageInfo

type SnapshotMetadata struct {
	ConfState ConfState `protobuf:"bytes,1,opt,name=conf_state,json=confState,proto3" json:"conf_state"`
	Index     uint64    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Term      uint64    `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
}

func (m *SnapshotMetadata) Reset()                    { _ = "STUB: not implemented"; return }
func (m *SnapshotMetadata) String() string            { _ = "STUB: not implemented"; return "" }
func (*SnapshotMetadata) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*SnapshotMetadata) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *SnapshotMetadata) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SnapshotMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SnapshotMetadata) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *SnapshotMetadata) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *SnapshotMetadata) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_SnapshotMetadata proto.InternalMessageInfo

type Snapshot struct {
	Data     []byte           `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Metadata SnapshotMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata"`
}

func (m *Snapshot) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Snapshot) String() string            { _ = "STUB: not implemented"; return "" }
func (*Snapshot) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Snapshot) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Snapshot) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Snapshot) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Snapshot) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Snapshot) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

type Message struct {
	Type MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=vanus.raft.MessageType" json:"type,omitempty"`
	To   uint64      `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	From uint64      `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	Term uint64      `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"`
	// logTerm is generally used for appending Raft logs to followers. For
	// example, (type=MsgApp,index=100,logTerm=5) means leader appends entries
	// starting at index=101, and the term of entry at index 100 is 5.
	// (type=MsgAppResp,reject=true,index=100,logTerm=5) means follower rejects
	// some entries from its leader as it already has an entry with term 5 at
	// index 100.
	LogTerm    uint64   `protobuf:"varint,5,opt,name=log_term,json=logTerm,proto3" json:"log_term,omitempty"`
	Index      uint64   `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	Entries    []Entry  `protobuf:"bytes,7,rep,name=entries,proto3" json:"entries"`
	Commit     uint64   `protobuf:"varint,8,opt,name=commit,proto3" json:"commit,omitempty"`
	Vote       uint64   `protobuf:"varint,14,opt,name=vote,proto3" json:"vote,omitempty"`
	Compact    uint64   `protobuf:"varint,13,opt,name=compact,proto3" json:"compact,omitempty"`
	Snapshot   Snapshot `protobuf:"bytes,9,opt,name=snapshot,proto3" json:"snapshot"`
	Reject     bool     `protobuf:"varint,10,opt,name=reject,proto3" json:"reject,omitempty"`
	RejectHint uint64   `protobuf:"varint,11,opt,name=reject_hint,json=rejectHint,proto3" json:"reject_hint,omitempty"`
	Context    []byte   `protobuf:"bytes,12,opt,name=context,proto3" json:"context,omitempty"`
}

func (m *Message) Reset()                    { _ = "STUB: not implemented"; return }
func (m *Message) String() string            { _ = "STUB: not implemented"; return "" }
func (*Message) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*Message) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *Message) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *Message) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *Message) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *Message) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_Message proto.InternalMessageInfo

type HardState struct {
	Term   uint64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Vote   uint64 `protobuf:"varint,2,opt,name=vote,proto3" json:"vote,omitempty"`
	Commit uint64 `protobuf:"varint,3,opt,name=commit,proto3" json:"commit,omitempty"`
}

func (m *HardState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *HardState) String() string            { _ = "STUB: not implemented"; return "" }
func (*HardState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*HardState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *HardState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *HardState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *HardState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *HardState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *HardState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_HardState proto.InternalMessageInfo

type ConfState struct {
	// The voters in the incoming config. (If the configuration is not joint,
	// then the outgoing config is empty).
	Voters []uint64 `protobuf:"varint,1,rep,packed,name=voters,proto3" json:"voters,omitempty"`
	// The learners in the incoming config.
	Learners []uint64 `protobuf:"varint,2,rep,packed,name=learners,proto3" json:"learners,omitempty"`
	// The voters in the outgoing config.
	VotersOutgoing []uint64 `protobuf:"varint,3,rep,packed,name=voters_outgoing,json=votersOutgoing,proto3" json:"voters_outgoing,omitempty"`
	// The nodes that will become learners when the outgoing config is removed.
	// These nodes are necessarily currently in nodes_joint (or they would have
	// been added to the incoming config right away).
	LearnersNext []uint64 `protobuf:"varint,4,rep,packed,name=learners_next,json=learnersNext,proto3" json:"learners_next,omitempty"`
	// If set, the config is joint and Raft will automatically transition into
	// the final config (i.e. remove the outgoing config) when this is safe.
	AutoLeave bool `protobuf:"varint,5,opt,name=auto_leave,json=autoLeave,proto3" json:"auto_leave,omitempty"`
}

func (m *ConfState) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ConfState) String() string            { _ = "STUB: not implemented"; return "" }
func (*ConfState) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ConfState) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ConfState) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConfState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConfState) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ConfState) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ConfState) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ConfState proto.InternalMessageInfo

type ConfChange struct {
	Type    ConfChangeType `protobuf:"varint,2,opt,name=type,proto3,enum=vanus.raft.ConfChangeType" json:"type,omitempty"`
	NodeID  uint64         `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Context []byte         `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	// NB: this is used only by etcd to thread through a unique identifier.
	// Ideally it should really use the Context instead. No counterpart to
	// this field exists in ConfChangeV2.
	ID uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *ConfChange) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ConfChange) String() string            { _ = "STUB: not implemented"; return "" }
func (*ConfChange) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ConfChange) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ConfChange) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConfChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConfChange) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ConfChange) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ConfChange) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ConfChange proto.InternalMessageInfo

// ConfChangeSingle is an individual configuration change operation. Multiple
// such operations can be carried out atomically via a ConfChangeV2.
type ConfChangeSingle struct {
	Type   ConfChangeType `protobuf:"varint,1,opt,name=type,proto3,enum=vanus.raft.ConfChangeType" json:"type,omitempty"`
	NodeID uint64         `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
}

func (m *ConfChangeSingle) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ConfChangeSingle) String() string            { _ = "STUB: not implemented"; return "" }
func (*ConfChangeSingle) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ConfChangeSingle) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ConfChangeSingle) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConfChangeSingle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConfChangeSingle) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ConfChangeSingle) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ConfChangeSingle) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ConfChangeSingle proto.InternalMessageInfo

// ConfChangeV2 messages initiate configuration changes. They support both the
// simple "one at a time" membership change protocol and full Joint Consensus
// allowing for arbitrary changes in membership.
//
// The supplied context is treated as an opaque payload and can be used to
// attach an action on the state machine to the application of the config change
// proposal. Note that contrary to Joint Consensus as outlined in the Raft
// paper[1], configuration changes become active when they are *applied* to the
// state machine (not when they are appended to the log).
//
// The simple protocol can be used whenever only a single change is made.
//
// Non-simple changes require the use of Joint Consensus, for which two
// configuration changes are run. The first configuration change specifies the
// desired changes and transitions the Raft group into the joint configuration,
// in which quorum requires a majority of both the pre-changes and post-changes
// configuration. Joint Consensus avoids entering fragile intermediate
// configurations that could compromise survivability. For example, without the
// use of Joint Consensus and running across three availability zones with a
// replication factor of three, it is not possible to replace a voter without
// entering an intermediate configuration that does not survive the outage of
// one availability zone.
//
// The provided ConfChangeTransition specifies how (and whether) Joint Consensus
// is used, and assigns the task of leaving the joint configuration either to
// Raft or the application. Leaving the joint configuration is accomplished by
// proposing a ConfChangeV2 with only and optionally the Context field
// populated.
//
// For details on Raft membership changes, see:
//
// [1]: https://github.com/ongardie/dissertation/blob/master/online-trim.pdf
type ConfChangeV2 struct {
	Transition ConfChangeTransition `protobuf:"varint,1,opt,name=transition,proto3,enum=vanus.raft.ConfChangeTransition" json:"transition,omitempty"`
	Changes    []ConfChangeSingle   `protobuf:"bytes,2,rep,name=changes,proto3" json:"changes"`
	Context    []byte               `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
}

func (m *ConfChangeV2) Reset()                    { _ = "STUB: not implemented"; return }
func (m *ConfChangeV2) String() string            { _ = "STUB: not implemented"; return "" }
func (*ConfChangeV2) ProtoMessage()               { _ = "STUB: not implemented"; return }
func (*ConfChangeV2) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (m *ConfChangeV2) XXX_Unmarshal(b []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConfChangeV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConfChangeV2) XXX_Merge(src proto.Message) { _ = "STUB: not implemented"; return }

func (m *ConfChangeV2) XXX_Size() int { _ = "STUB: not implemented"; return 0 }

func (m *ConfChangeV2) XXX_DiscardUnknown() { _ = "STUB: not implemented"; return }

var xxx_messageInfo_ConfChangeV2 proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("vanus.raft.EntryType", EntryType_name, EntryType_value)
	proto.RegisterEnum("vanus.raft.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("vanus.raft.ConfChangeTransition", ConfChangeTransition_name, ConfChangeTransition_value)
	proto.RegisterEnum("vanus.raft.ConfChangeType", ConfChangeType_name, ConfChangeType_value)
	proto.RegisterType((*Entry)(nil), "vanus.raft.Entry")
	proto.RegisterType((*SnapshotMetadata)(nil), "vanus.raft.SnapshotMetadata")
	proto.RegisterType((*Snapshot)(nil), "vanus.raft.Snapshot")
	proto.RegisterType((*Message)(nil), "vanus.raft.Message")
	proto.RegisterType((*HardState)(nil), "vanus.raft.HardState")
	proto.RegisterType((*ConfState)(nil), "vanus.raft.ConfState")
	proto.RegisterType((*ConfChange)(nil), "vanus.raft.ConfChange")
	proto.RegisterType((*ConfChangeSingle)(nil), "vanus.raft.ConfChangeSingle")
	proto.RegisterType((*ConfChangeV2)(nil), "vanus.raft.ConfChangeV2")
}

func init() { proto.RegisterFile("raftpb/raft.proto", fileDescriptor_f652ee94e728864d) }

var fileDescriptor_f652ee94e728864d = []byte{
	// 1113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xcf, 0x6f, 0xe3, 0x44,
	0x14, 0xf6, 0x8f, 0x34, 0x3f, 0x5e, 0xd2, 0x74, 0x3a, 0x9b, 0xee, 0x9a, 0xb2, 0xa4, 0x21, 0x2b,
	0xb4, 0xa5, 0x88, 0x54, 0x14, 0x89, 0x03, 0x42, 0x88, 0xb6, 0xbb, 0x52, 0x0b, 0x4d, 0x59, 0xdc,
	0x6e, 0x0f, 0x1c, 0x88, 0x26, 0xf6, 0xd4, 0x31, 0xc4, 0x1e, 0xcb, 0x9e, 0x94, 0xf6, 0xca, 0x1d,
	0x09, 0x89, 0x0b, 0x77, 0x24, 0xc4, 0x81, 0x3f, 0xa4, 0xc7, 0x1e, 0x39, 0x55, 0x6c, 0xfb, 0x8f,
	0xa0, 0xf9, 0xe1, 0xc4, 0x29, 0x5d, 0xa4, 0x3d, 0x65, 0xde, 0xf7, 0xbe, 0x99, 0xf7, 0xbd, 0x6f,
	0xe6, 0x59, 0x81, 0xe5, 0x94, 0x9c, 0xf2, 0x64, 0xb8, 0x29, 0x7e, 0x7a, 0x49, 0xca, 0x38, 0xc3,
	0x70, 0x46, 0xe2, 0x49, 0xd6, 0x13, 0xc8, 0x6a, 0x2b, 0x60, 0x01, 0x93, 0xf0, 0xa6, 0x58, 0x29,
	0x46, 0xf7, 0x0f, 0x13, 0x16, 0x9e, 0xc7, 0x3c, 0xbd, 0xc0, 0x18, 0x4a, 0x9c, 0xa6, 0x91, 0x63,
	0x75, 0xcc, 0xf5, 0x92, 0x2b, 0xd7, 0xb8, 0x05, 0x0b, 0x61, 0xec, 0xd3, 0x73, 0xc7, 0x96, 0xa0,
	0x0a, 0xf0, 0xfb, 0x50, 0xe2, 0x17, 0x09, 0x75, 0xcc, 0x8e, 0xb9, 0xde, 0xdc, 0x5a, 0xe9, 0xcd,
	0x8a, 0xf4, 0xe4, 0x51, 0xc7, 0x17, 0x09, 0x75, 0x25, 0x45, 0x1c, 0xea, 0x13, 0x4e, 0x9c, 0x52,
	0xc7, 0x5c, 0x6f, 0xb8, 0x72, 0x8d, 0x1f, 0x41, 0x25, 0x66, 0x3e, 0x1d, 0x84, 0xbe, 0xb3, 0x20,
	0x8f, 0x2d, 0x8b, 0x70, 0xdf, 0xc7, 0x6f, 0x43, 0x2d, 0x49, 0xe9, 0xd9, 0x40, 0xca, 0x28, 0xcb,
	0x54, 0x55, 0x00, 0xc7, 0x34, 0x8d, 0xba, 0xe7, 0x80, 0x8e, 0x62, 0x92, 0x64, 0x23, 0xc6, 0xfb,
	0x94, 0x13, 0x79, 0xd2, 0xa7, 0x00, 0x1e, 0x8b, 0x4f, 0x07, 0x19, 0x27, 0x5c, 0xc9, 0xa9, 0xcf,
	0xcb, 0xd9, 0x65, 0xf1, 0xe9, 0x91, 0x48, 0xee, 0x94, 0x2e, 0xaf, 0xd7, 0x0c, 0xb7, 0xe6, 0xe5,
	0xc0, 0xac, 0x35, 0xab, 0xd8, 0x5a, 0x6e, 0x82, 0x3d, 0x33, 0xa1, 0xfb, 0x1d, 0x54, 0xf3, 0xca,
	0xd3, 0x7e, 0xcc, 0x42, 0x3f, 0x9f, 0x43, 0x35, 0xd2, 0x8a, 0xe4, 0x61, 0xf5, 0xad, 0xc7, 0x45,
	0x0d, 0x77, 0x55, 0x6b, 0x29, 0xd3, 0x3d, 0xdd, 0xdf, 0x6d, 0xa8, 0xf4, 0x69, 0x96, 0x91, 0x80,
	0xe2, 0x0f, 0xe6, 0xac, 0x7d, 0x54, 0x3c, 0x47, 0x53, 0x0a, 0xe6, 0x36, 0xc1, 0xe2, 0x4c, 0xeb,
	0xb7, 0x38, 0x13, 0xe2, 0x4e, 0x53, 0x36, 0x15, 0x2f, 0xd6, 0xd3, 0x86, 0x4a, 0x85, 0x5b, 0x7d,
	0x0b, 0xaa, 0x63, 0x16, 0x28, 0x9b, 0xd5, 0x0d, 0x54, 0xc6, 0x2c, 0x38, 0x9e, 0xbb, 0xf0, 0x72,
	0xd1, 0x95, 0x8f, 0xa0, 0x42, 0x63, 0x9e, 0x86, 0x34, 0x73, 0x2a, 0x1d, 0x7b, 0xbd, 0xbe, 0xb5,
	0xfc, 0x9f, 0x3b, 0xd7, 0x5d, 0xe5, 0x3c, 0xfc, 0x10, 0xca, 0x1e, 0x8b, 0xa2, 0x90, 0x3b, 0x55,
	0x75, 0xc7, 0x2a, 0x12, 0x7a, 0xce, 0x18, 0xa7, 0x4e, 0x53, 0xe9, 0x11, 0x6b, 0xec, 0x40, 0xc5,
	0x63, 0x51, 0x42, 0x3c, 0xee, 0x2c, 0x2a, 0x39, 0x3a, 0xc4, 0x9f, 0x40, 0x35, 0xd3, 0xf6, 0x39,
	0x35, 0x69, 0x6d, 0xeb, 0x3e, 0x6b, 0x73, 0x4b, 0x73, 0xae, 0xa8, 0x9e, 0xd2, 0xef, 0xa9, 0xc7,
	0x1d, 0xe8, 0x98, 0xeb, 0x55, 0x57, 0x47, 0x78, 0x0d, 0xea, 0x6a, 0x35, 0x18, 0x85, 0x31, 0x77,
	0xea, 0xb2, 0x1a, 0x28, 0x68, 0x2f, 0x8c, 0xb9, 0x92, 0x12, 0x73, 0x7a, 0xce, 0x9d, 0x86, 0xbc,
	0xe2, 0x3c, 0xec, 0x7e, 0x05, 0xb5, 0x3d, 0x92, 0xfa, 0xea, 0xf1, 0xe4, 0xae, 0x9a, 0x05, 0x57,
	0xf3, 0xce, 0xac, 0x42, 0x67, 0x33, 0x17, 0xec, 0xa2, 0x0b, 0xdd, 0xbf, 0x4c, 0xa8, 0x4d, 0xdf,
	0xa6, 0x60, 0x09, 0x76, 0x9a, 0x39, 0x66, 0xc7, 0x16, 0x2c, 0x15, 0xe1, 0x55, 0xa8, 0x8e, 0x29,
	0x49, 0x63, 0x91, 0xb1, 0x64, 0x66, 0x1a, 0xe3, 0xa7, 0xb0, 0xa4, 0x58, 0x03, 0x36, 0xe1, 0x01,
	0x0b, 0xe3, 0xc0, 0xb1, 0x25, 0xa5, 0xa9, 0xe0, 0xaf, 0x35, 0x8a, 0x9f, 0xc0, 0x62, 0xbe, 0x69,
	0x10, 0x8b, 0xbe, 0x4a, 0x92, 0xd6, 0xc8, 0xc1, 0x43, 0x7a, 0xce, 0xf1, 0x3b, 0x00, 0x64, 0xc2,
	0xd9, 0x60, 0x4c, 0xc9, 0x19, 0x95, 0x6f, 0xa2, 0xea, 0xd6, 0x04, 0x72, 0x20, 0x80, 0xee, 0xaf,
	0x26, 0x80, 0x90, 0xbb, 0x3b, 0x22, 0x71, 0x40, 0x71, 0x4f, 0x3f, 0x52, 0x4b, 0x3e, 0xd2, 0xd5,
	0xbb, 0x03, 0xa7, 0x58, 0x85, 0x77, 0xfa, 0x64, 0x36, 0xf0, 0xd2, 0x86, 0x1d, 0xb8, 0xb9, 0x5e,
	0x2b, 0x1f, 0x8a, 0xa1, 0x7f, 0x36, 0x1d, 0xfe, 0x82, 0xf3, 0xa5, 0x39, 0xe7, 0xf1, 0x43, 0xb0,
	0x42, 0x5f, 0x59, 0xbd, 0x53, 0xbe, 0xb9, 0x5e, 0xb3, 0xf6, 0x9f, 0xb9, 0x56, 0xe8, 0x77, 0x03,
	0x40, 0xb3, 0x72, 0x47, 0x61, 0x1c, 0x8c, 0x67, 0xd2, 0xcc, 0x37, 0x97, 0x66, 0xbd, 0x4e, 0x5a,
	0xf7, 0x4f, 0x13, 0x1a, 0xb3, 0xdd, 0x27, 0x5b, 0xf8, 0x0b, 0x00, 0x9e, 0x92, 0x38, 0x0b, 0x79,
	0xc8, 0x62, 0x5d, 0xab, 0xf3, 0x9a, 0x5a, 0x53, 0x9e, 0x5b, 0xd8, 0x83, 0x3f, 0x83, 0x8a, 0x27,
	0xf3, 0xea, 0x66, 0xef, 0x7c, 0x32, 0xee, 0xb6, 0x95, 0x0f, 0x97, 0xde, 0x52, 0xf4, 0xca, 0x9e,
	0xf3, 0x6a, 0x63, 0x0f, 0x6a, 0xd3, 0x4f, 0x30, 0x5e, 0x82, 0xba, 0x0c, 0x0e, 0x59, 0x1a, 0x91,
	0x31, 0x32, 0xf0, 0x03, 0x58, 0x92, 0xc0, 0xec, 0x7c, 0x64, 0xe2, 0x15, 0x58, 0xbe, 0x03, 0x9e,
	0x6c, 0x21, 0x6b, 0xe3, 0x67, 0x1b, 0xea, 0x85, 0x4f, 0x0e, 0x06, 0x28, 0xf7, 0xb3, 0x60, 0x6f,
	0x92, 0x20, 0x03, 0xd7, 0xa1, 0xd2, 0xcf, 0x82, 0x1d, 0x4a, 0x38, 0x32, 0x75, 0xf0, 0x22, 0x65,
	0x09, 0xb2, 0x34, 0x6b, 0x3b, 0x49, 0x90, 0x8d, 0x9b, 0x00, 0x6a, 0xed, 0xd2, 0x2c, 0x41, 0x25,
	0x4d, 0x3c, 0x61, 0x9c, 0xa2, 0x05, 0xa1, 0x4d, 0x07, 0x32, 0x5b, 0xd6, 0x59, 0x31, 0xd1, 0xa8,
	0x82, 0x11, 0x34, 0x44, 0x31, 0x4a, 0x52, 0x3e, 0x14, 0x55, 0xaa, 0xb8, 0x05, 0xa8, 0x88, 0xc8,
	0x4d, 0x35, 0x8c, 0xa1, 0xd9, 0xcf, 0x82, 0x97, 0x71, 0x4a, 0x89, 0x37, 0x22, 0xc3, 0x31, 0x45,
	0x80, 0x97, 0x61, 0x51, 0x1f, 0x24, 0xa6, 0x6b, 0x92, 0xa1, 0xba, 0xa6, 0xed, 0x8e, 0xa8, 0xf7,
	0xc3, 0x37, 0x13, 0x96, 0x4e, 0x22, 0xd4, 0x10, 0x6d, 0xf7, 0xb3, 0x40, 0x5e, 0xcf, 0x29, 0x4d,
	0x0f, 0x28, 0xf1, 0x69, 0x8a, 0x16, 0xf5, 0xee, 0xe3, 0x30, 0xa2, 0x6c, 0xc2, 0x0f, 0xd9, 0x8f,
	0xa8, 0xa9, 0xc5, 0xb8, 0x94, 0xf8, 0xfb, 0xe2, 0x6b, 0x88, 0x96, 0xb4, 0x98, 0x29, 0x22, 0xc5,
	0x20, 0xdd, 0xef, 0x8b, 0x94, 0xca, 0x16, 0x97, 0x75, 0x55, 0x1d, 0x4b, 0x0e, 0xd6, 0x67, 0x1d,
	0xb0, 0x40, 0x6b, 0x7b, 0xa0, 0x59, 0xdb, 0x49, 0x32, 0xbe, 0xd0, 0x58, 0x4b, 0x63, 0xf2, 0xe3,
	0xa0, 0xb1, 0x95, 0x8d, 0x9f, 0x4c, 0x68, 0xdd, 0xf7, 0xac, 0xf0, 0x63, 0x70, 0xee, 0xc3, 0xb7,
	0x27, 0x9c, 0x21, 0x03, 0xbf, 0x07, 0xef, 0xde, 0x97, 0xfd, 0x92, 0x85, 0x31, 0xdf, 0x8f, 0x92,
	0x71, 0xe8, 0x85, 0xe2, 0x12, 0xff, 0x8f, 0xf6, 0xfc, 0x5c, 0xd3, 0xac, 0x8d, 0x0b, 0x68, 0xce,
	0x8f, 0x91, 0xb0, 0x71, 0x86, 0x6c, 0xfb, 0xbe, 0x18, 0x1d, 0x64, 0x60, 0xa7, 0x28, 0xd6, 0xa5,
	0x11, 0x3b, 0xa3, 0x32, 0x63, 0xce, 0x67, 0x5e, 0x26, 0x3e, 0xe1, 0x2a, 0x63, 0xcd, 0x37, 0xb2,
	0xed, 0xfb, 0x07, 0xea, 0x0b, 0x25, 0xb3, 0xf6, 0x4e, 0xff, 0xf2, 0x55, 0xdb, 0xb8, 0x7a, 0xd5,
	0x36, 0x2e, 0x6f, 0xda, 0xe6, 0xd5, 0x4d, 0xdb, 0xfc, 0xe7, 0xa6, 0x6d, 0xfe, 0x72, 0xdb, 0x36,
	0x7e, 0xbb, 0x6d, 0x1b, 0x57, 0xb7, 0x6d, 0xe3, 0xef, 0xdb, 0xb6, 0xf1, 0xed, 0xd3, 0x20, 0xe4,
	0xa3, 0xc9, 0xb0, 0xe7, 0xb1, 0x68, 0x53, 0x0e, 0xd4, 0x87, 0x63, 0x32, 0xcc, 0xd4, 0x52, 0xfe,
	0x31, 0xda, 0x54, 0x7f, 0x92, 0x86, 0x65, 0xf9, 0xf7, 0xe7, 0xe3, 0x7f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0xbe, 0xfe, 0xc1, 0xa1, 0x35, 0x09, 0x00, 0x00,
}

func (m *Entry) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Entry) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Entry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SnapshotMetadata) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *SnapshotMetadata) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *SnapshotMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Snapshot) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Snapshot) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Snapshot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *Message) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *Message) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *Message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *HardState) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *HardState) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *HardState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ConfState) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *ConfState) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *ConfState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ConfChange) Marshal() (dAtA []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (m *ConfChange) MarshalTo(dAtA []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

func (m *ConfChange) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ConfChangeSingle) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConfChangeSingle) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ConfChangeSingle) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ConfChangeV2) Marshal() (dAtA []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (m *ConfChangeV2) MarshalTo(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func (m *ConfChangeV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

func encodeVarintRaft(dAtA []byte, offset int, v uint64) int { _ = "STUB: not implemented"; return 0 }

func (m *Entry) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *SnapshotMetadata) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Snapshot) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Message) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *HardState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ConfState) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ConfChange) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ConfChangeSingle) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func (m *ConfChangeV2) Size() (n int) { _ = "STUB: not implemented"; return 0 }

func sovRaft(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func sozRaft(x uint64) (n int) { _ = "STUB: not implemented"; return 0 }

func (m *Entry) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *SnapshotMetadata) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Snapshot) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *Message) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *HardState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConfState) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConfChange) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConfChangeSingle) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func (m *ConfChangeV2) Unmarshal(dAtA []byte) error { _ = "STUB: not implemented"; return nil }

func skipRaft(dAtA []byte) (n int, err error) { _ = "STUB: not implemented"; return 0, nil }

var (
	ErrInvalidLengthRaft        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRaft          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRaft = fmt.Errorf("proto: unexpected end of group")
)
