// Code generated by protoc-gen-go-grpc-mock. DO NOT EDIT.
// source: vanus/core/controller/controller.proto

package controller

import (
	context "context"

	meta "github.com/vanus-labs/vanus/api/meta"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// MockPingServerClient is a mock of PingServerClient interface.
type MockPingServerClient struct {
	ctrl     *gomock.Controller
	recorder *MockPingServerClientMockRecorder
}

// MockPingServerClientMockRecorder is the mock recorder for MockPingServerClient.
type MockPingServerClientMockRecorder struct {
	mock *MockPingServerClient
}

// NewMockPingServerClient creates a new mock instance.
func NewMockPingServerClient(ctrl *gomock.Controller) *MockPingServerClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPingServerClient) EXPECT() *MockPingServerClientMockRecorder {
	_ = "STUB: not implemented"

	// Ping mocks base method.
	return nil
}

func (m *MockPingServerClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PingResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Ping indicates an expected call of Ping.
func (mr *MockPingServerClientMockRecorder) Ping(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockPingServerServer is a mock of PingServerServer interface.
type MockPingServerServer struct {
	ctrl     *gomock.Controller
	recorder *MockPingServerServerMockRecorder
}

// MockPingServerServerMockRecorder is the mock recorder for MockPingServerServer.
type MockPingServerServerMockRecorder struct {
	mock *MockPingServerServer
}

// NewMockPingServerServer creates a new mock instance.
func NewMockPingServerServer(ctrl *gomock.Controller) *MockPingServerServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPingServerServer) EXPECT() *MockPingServerServerMockRecorder {
	_ = "STUB: not implemented"

	// Ping mocks base method.
	return nil
}

func (m *MockPingServerServer) Ping(ctx context.Context, in *emptypb.Empty) (*PingResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Ping indicates an expected call of Ping.
func (mr *MockPingServerServerMockRecorder) Ping(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockNamespaceControllerClient is a mock of NamespaceControllerClient interface.
type MockNamespaceControllerClient struct {
	ctrl     *gomock.Controller
	recorder *MockNamespaceControllerClientMockRecorder
}

// MockNamespaceControllerClientMockRecorder is the mock recorder for MockNamespaceControllerClient.
type MockNamespaceControllerClientMockRecorder struct {
	mock *MockNamespaceControllerClient
}

// NewMockNamespaceControllerClient creates a new mock instance.
func NewMockNamespaceControllerClient(ctrl *gomock.Controller) *MockNamespaceControllerClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNamespaceControllerClient) EXPECT() *MockNamespaceControllerClientMockRecorder {
	_ = "STUB: not implemented"

	// CreateNamespace mocks base method.
	return nil
}

func (m *MockNamespaceControllerClient) CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateNamespace indicates an expected call of CreateNamespace.
func (mr *MockNamespaceControllerClientMockRecorder) CreateNamespace(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteNamespace mocks base method.
func (m *MockNamespaceControllerClient) DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteNamespace indicates an expected call of DeleteNamespace.
func (mr *MockNamespaceControllerClientMockRecorder) DeleteNamespace(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNamespace mocks base method.
func (m *MockNamespaceControllerClient) GetNamespace(ctx context.Context, in *GetNamespaceRequest, opts ...grpc.CallOption) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockNamespaceControllerClientMockRecorder) GetNamespace(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNamespaceWithHumanFriendly mocks base method.
func (m *MockNamespaceControllerClient) GetNamespaceWithHumanFriendly(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetNamespaceWithHumanFriendly indicates an expected call of GetNamespaceWithHumanFriendly.
func (mr *MockNamespaceControllerClientMockRecorder) GetNamespaceWithHumanFriendly(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListNamespace mocks base method.
func (m *MockNamespaceControllerClient) ListNamespace(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListNamespaceResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListNamespace indicates an expected call of ListNamespace.
func (mr *MockNamespaceControllerClientMockRecorder) ListNamespace(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockNamespaceControllerServer is a mock of NamespaceControllerServer interface.
type MockNamespaceControllerServer struct {
	ctrl     *gomock.Controller
	recorder *MockNamespaceControllerServerMockRecorder
}

// MockNamespaceControllerServerMockRecorder is the mock recorder for MockNamespaceControllerServer.
type MockNamespaceControllerServerMockRecorder struct {
	mock *MockNamespaceControllerServer
}

// NewMockNamespaceControllerServer creates a new mock instance.
func NewMockNamespaceControllerServer(ctrl *gomock.Controller) *MockNamespaceControllerServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNamespaceControllerServer) EXPECT() *MockNamespaceControllerServerMockRecorder {
	_ = "STUB: not implemented"

	// CreateNamespace mocks base method.
	return nil
}

func (m *MockNamespaceControllerServer) CreateNamespace(ctx context.Context, in *CreateNamespaceRequest) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateNamespace indicates an expected call of CreateNamespace.
func (mr *MockNamespaceControllerServerMockRecorder) CreateNamespace(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteNamespace mocks base method.
func (m *MockNamespaceControllerServer) DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteNamespace indicates an expected call of DeleteNamespace.
func (mr *MockNamespaceControllerServerMockRecorder) DeleteNamespace(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNamespace mocks base method.
func (m *MockNamespaceControllerServer) GetNamespace(ctx context.Context, in *GetNamespaceRequest) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockNamespaceControllerServerMockRecorder) GetNamespace(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNamespaceWithHumanFriendly mocks base method.
func (m *MockNamespaceControllerServer) GetNamespaceWithHumanFriendly(ctx context.Context, in *wrapperspb.StringValue) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetNamespaceWithHumanFriendly indicates an expected call of GetNamespaceWithHumanFriendly.
func (mr *MockNamespaceControllerServerMockRecorder) GetNamespaceWithHumanFriendly(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListNamespace mocks base method.
func (m *MockNamespaceControllerServer) ListNamespace(ctx context.Context, in *emptypb.Empty) (*ListNamespaceResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListNamespace indicates an expected call of ListNamespace.
func (mr *MockNamespaceControllerServerMockRecorder) ListNamespace(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockEventbusControllerClient is a mock of EventbusControllerClient interface.
type MockEventbusControllerClient struct {
	ctrl     *gomock.Controller
	recorder *MockEventbusControllerClientMockRecorder
}

// MockEventbusControllerClientMockRecorder is the mock recorder for MockEventbusControllerClient.
type MockEventbusControllerClientMockRecorder struct {
	mock *MockEventbusControllerClient
}

// NewMockEventbusControllerClient creates a new mock instance.
func NewMockEventbusControllerClient(ctrl *gomock.Controller) *MockEventbusControllerClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventbusControllerClient) EXPECT() *MockEventbusControllerClientMockRecorder {
	_ = "STUB: not implemented"

	// CreateEventbus mocks base method.
	return nil
}

func (m *MockEventbusControllerClient) CreateEventbus(ctx context.Context, in *CreateEventbusRequest, opts ...grpc.CallOption) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateEventbus indicates an expected call of CreateEventbus.
func (mr *MockEventbusControllerClientMockRecorder) CreateEventbus(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateSystemEventbus mocks base method.
func (m *MockEventbusControllerClient) CreateSystemEventbus(ctx context.Context, in *CreateEventbusRequest, opts ...grpc.CallOption) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateSystemEventbus indicates an expected call of CreateSystemEventbus.
func (mr *MockEventbusControllerClientMockRecorder) CreateSystemEventbus(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteEventbus mocks base method.
func (m *MockEventbusControllerClient) DeleteEventbus(ctx context.Context, in *wrapperspb.UInt64Value, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteEventbus indicates an expected call of DeleteEventbus.
func (mr *MockEventbusControllerClientMockRecorder) DeleteEventbus(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEventbus mocks base method.
func (m *MockEventbusControllerClient) GetEventbus(ctx context.Context, in *wrapperspb.UInt64Value, opts ...grpc.CallOption) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEventbus indicates an expected call of GetEventbus.
func (mr *MockEventbusControllerClientMockRecorder) GetEventbus(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEventbusWithHumanFriendly mocks base method.
func (m *MockEventbusControllerClient) GetEventbusWithHumanFriendly(ctx context.Context, in *GetEventbusWithHumanFriendlyRequest, opts ...grpc.CallOption) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEventbusWithHumanFriendly indicates an expected call of GetEventbusWithHumanFriendly.
func (mr *MockEventbusControllerClientMockRecorder) GetEventbusWithHumanFriendly(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListEventbus mocks base method.
func (m *MockEventbusControllerClient) ListEventbus(ctx context.Context, in *ListEventbusRequest, opts ...grpc.CallOption) (*ListEventbusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListEventbus indicates an expected call of ListEventbus.
func (mr *MockEventbusControllerClientMockRecorder) ListEventbus(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateEventbus mocks base method.
func (m *MockEventbusControllerClient) UpdateEventbus(ctx context.Context, in *UpdateEventbusRequest, opts ...grpc.CallOption) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateEventbus indicates an expected call of UpdateEventbus.
func (mr *MockEventbusControllerClientMockRecorder) UpdateEventbus(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockEventbusControllerServer is a mock of EventbusControllerServer interface.
type MockEventbusControllerServer struct {
	ctrl     *gomock.Controller
	recorder *MockEventbusControllerServerMockRecorder
}

// MockEventbusControllerServerMockRecorder is the mock recorder for MockEventbusControllerServer.
type MockEventbusControllerServerMockRecorder struct {
	mock *MockEventbusControllerServer
}

// NewMockEventbusControllerServer creates a new mock instance.
func NewMockEventbusControllerServer(ctrl *gomock.Controller) *MockEventbusControllerServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventbusControllerServer) EXPECT() *MockEventbusControllerServerMockRecorder {
	_ = "STUB: not implemented"

	// CreateEventbus mocks base method.
	return nil
}

func (m *MockEventbusControllerServer) CreateEventbus(ctx context.Context, in *CreateEventbusRequest) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateEventbus indicates an expected call of CreateEventbus.
func (mr *MockEventbusControllerServerMockRecorder) CreateEventbus(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateSystemEventbus mocks base method.
func (m *MockEventbusControllerServer) CreateSystemEventbus(ctx context.Context, in *CreateEventbusRequest) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateSystemEventbus indicates an expected call of CreateSystemEventbus.
func (mr *MockEventbusControllerServerMockRecorder) CreateSystemEventbus(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteEventbus mocks base method.
func (m *MockEventbusControllerServer) DeleteEventbus(ctx context.Context, in *wrapperspb.UInt64Value) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteEventbus indicates an expected call of DeleteEventbus.
func (mr *MockEventbusControllerServerMockRecorder) DeleteEventbus(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEventbus mocks base method.
func (m *MockEventbusControllerServer) GetEventbus(ctx context.Context, in *wrapperspb.UInt64Value) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEventbus indicates an expected call of GetEventbus.
func (mr *MockEventbusControllerServerMockRecorder) GetEventbus(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEventbusWithHumanFriendly mocks base method.
func (m *MockEventbusControllerServer) GetEventbusWithHumanFriendly(ctx context.Context, in *GetEventbusWithHumanFriendlyRequest) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEventbusWithHumanFriendly indicates an expected call of GetEventbusWithHumanFriendly.
func (mr *MockEventbusControllerServerMockRecorder) GetEventbusWithHumanFriendly(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListEventbus mocks base method.
func (m *MockEventbusControllerServer) ListEventbus(ctx context.Context, in *ListEventbusRequest) (*ListEventbusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListEventbus indicates an expected call of ListEventbus.
func (mr *MockEventbusControllerServerMockRecorder) ListEventbus(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateEventbus mocks base method.
func (m *MockEventbusControllerServer) UpdateEventbus(ctx context.Context, in *UpdateEventbusRequest) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateEventbus indicates an expected call of UpdateEventbus.
func (mr *MockEventbusControllerServerMockRecorder) UpdateEventbus(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockEventlogControllerClient is a mock of EventlogControllerClient interface.
type MockEventlogControllerClient struct {
	ctrl     *gomock.Controller
	recorder *MockEventlogControllerClientMockRecorder
}

// MockEventlogControllerClientMockRecorder is the mock recorder for MockEventlogControllerClient.
type MockEventlogControllerClientMockRecorder struct {
	mock *MockEventlogControllerClient
}

// NewMockEventlogControllerClient creates a new mock instance.
func NewMockEventlogControllerClient(ctrl *gomock.Controller) *MockEventlogControllerClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventlogControllerClient) EXPECT() *MockEventlogControllerClientMockRecorder {
	_ = "STUB: not implemented"

	// GetAppendableSegment mocks base method.
	return nil
}

func (m *MockEventlogControllerClient) GetAppendableSegment(ctx context.Context, in *GetAppendableSegmentRequest, opts ...grpc.CallOption) (*GetAppendableSegmentResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAppendableSegment indicates an expected call of GetAppendableSegment.
func (mr *MockEventlogControllerClientMockRecorder) GetAppendableSegment(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListSegment mocks base method.
func (m *MockEventlogControllerClient) ListSegment(ctx context.Context, in *ListSegmentRequest, opts ...grpc.CallOption) (*ListSegmentResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListSegment indicates an expected call of ListSegment.
func (mr *MockEventlogControllerClientMockRecorder) ListSegment(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockEventlogControllerServer is a mock of EventlogControllerServer interface.
type MockEventlogControllerServer struct {
	ctrl     *gomock.Controller
	recorder *MockEventlogControllerServerMockRecorder
}

// MockEventlogControllerServerMockRecorder is the mock recorder for MockEventlogControllerServer.
type MockEventlogControllerServerMockRecorder struct {
	mock *MockEventlogControllerServer
}

// NewMockEventlogControllerServer creates a new mock instance.
func NewMockEventlogControllerServer(ctrl *gomock.Controller) *MockEventlogControllerServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventlogControllerServer) EXPECT() *MockEventlogControllerServerMockRecorder {
	_ = "STUB: not implemented"

	// GetAppendableSegment mocks base method.
	return nil
}

func (m *MockEventlogControllerServer) GetAppendableSegment(ctx context.Context, in *GetAppendableSegmentRequest) (*GetAppendableSegmentResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAppendableSegment indicates an expected call of GetAppendableSegment.
func (mr *MockEventlogControllerServerMockRecorder) GetAppendableSegment(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListSegment mocks base method.
func (m *MockEventlogControllerServer) ListSegment(ctx context.Context, in *ListSegmentRequest) (*ListSegmentResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListSegment indicates an expected call of ListSegment.
func (mr *MockEventlogControllerServerMockRecorder) ListSegment(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockSegmentController_SegmentHeartbeatClient is a mock of SegmentController_SegmentHeartbeatClient interface.
type MockSegmentController_SegmentHeartbeatClient struct {
	ctrl     *gomock.Controller
	recorder *MockSegmentController_SegmentHeartbeatClientMockRecorder
}

// MockSegmentController_SegmentHeartbeatClientMockRecorder is the mock recorder for MockSegmentController_SegmentHeartbeatClient.
type MockSegmentController_SegmentHeartbeatClientMockRecorder struct {
	mock *MockSegmentController_SegmentHeartbeatClient
}

// NewMockSegmentController_SegmentHeartbeatClient creates a new mock instance.
func NewMockSegmentController_SegmentHeartbeatClient(ctrl *gomock.Controller) *MockSegmentController_SegmentHeartbeatClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSegmentController_SegmentHeartbeatClient) EXPECT() *MockSegmentController_SegmentHeartbeatClientMockRecorder {
	_ = "STUB: not implemented"

	// CloseAndRecv mocks base method.
	return nil
}

func (m *MockSegmentController_SegmentHeartbeatClient) CloseAndRecv() (*SegmentHeartbeatResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CloseAndRecv indicates an expected call of CloseAndRecv.
func (mr *MockSegmentController_SegmentHeartbeatClientMockRecorder) CloseAndRecv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CloseSend mocks base method.
func (m *MockSegmentController_SegmentHeartbeatClient) CloseSend() error {
	_ = "STUB: not implemented"
	return nil
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockSegmentController_SegmentHeartbeatClientMockRecorder) CloseSend() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Context mocks base method.
func (m *MockSegmentController_SegmentHeartbeatClient) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockSegmentController_SegmentHeartbeatClientMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Header mocks base method.
func (m *MockSegmentController_SegmentHeartbeatClient) Header() (metadata.MD, error) {
	_ = "STUB: not implemented"
	return *new(metadata.MD), nil
}

// Header indicates an expected call of Header.
func (mr *MockSegmentController_SegmentHeartbeatClientMockRecorder) Header() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m *MockSegmentController_SegmentHeartbeatClient) RecvMsg(arg0 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockSegmentController_SegmentHeartbeatClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Send mocks base method.
func (m *MockSegmentController_SegmentHeartbeatClient) Send(arg0 *SegmentHeartbeatRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// Send indicates an expected call of Send.
func (mr *MockSegmentController_SegmentHeartbeatClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m *MockSegmentController_SegmentHeartbeatClient) SendMsg(arg0 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockSegmentController_SegmentHeartbeatClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Trailer mocks base method.
func (m *MockSegmentController_SegmentHeartbeatClient) Trailer() metadata.MD {
	_ = "STUB: not implemented"
	return *new(metadata.MD)
}

// Trailer indicates an expected call of Trailer.
func (mr *MockSegmentController_SegmentHeartbeatClientMockRecorder) Trailer() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockSegmentController_SegmentHeartbeatServer is a mock of SegmentController_SegmentHeartbeatServer interface.
type MockSegmentController_SegmentHeartbeatServer struct {
	ctrl     *gomock.Controller
	recorder *MockSegmentController_SegmentHeartbeatServerMockRecorder
}

// MockSegmentController_SegmentHeartbeatServerMockRecorder is the mock recorder for MockSegmentController_SegmentHeartbeatServer.
type MockSegmentController_SegmentHeartbeatServerMockRecorder struct {
	mock *MockSegmentController_SegmentHeartbeatServer
}

// NewMockSegmentController_SegmentHeartbeatServer creates a new mock instance.
func NewMockSegmentController_SegmentHeartbeatServer(ctrl *gomock.Controller) *MockSegmentController_SegmentHeartbeatServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSegmentController_SegmentHeartbeatServer) EXPECT() *MockSegmentController_SegmentHeartbeatServerMockRecorder {
	_ = "STUB: not implemented"

	// Context mocks base method.
	return nil
}

func (m *MockSegmentController_SegmentHeartbeatServer) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockSegmentController_SegmentHeartbeatServerMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Recv mocks base method.
func (m *MockSegmentController_SegmentHeartbeatServer) Recv() (*SegmentHeartbeatResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Recv indicates an expected call of Recv.
func (mr *MockSegmentController_SegmentHeartbeatServerMockRecorder) Recv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m *MockSegmentController_SegmentHeartbeatServer) RecvMsg(arg0 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockSegmentController_SegmentHeartbeatServerMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendAndClose mocks base method.
func (m *MockSegmentController_SegmentHeartbeatServer) SendAndClose(arg0 *SegmentHeartbeatRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// SendAndClose indicates an expected call of SendAndClose.
func (mr *MockSegmentController_SegmentHeartbeatServerMockRecorder) SendAndClose(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader mocks base method.
func (m *MockSegmentController_SegmentHeartbeatServer) SendHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockSegmentController_SegmentHeartbeatServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m *MockSegmentController_SegmentHeartbeatServer) SendMsg(arg0 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockSegmentController_SegmentHeartbeatServerMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader mocks base method.
func (m *MockSegmentController_SegmentHeartbeatServer) SetHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockSegmentController_SegmentHeartbeatServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTrailer mocks base method.
func (m *MockSegmentController_SegmentHeartbeatServer) SetTrailer(arg0 metadata.MD) {
	_ = "STUB: not implemented"
	return
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockSegmentController_SegmentHeartbeatServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockSegmentControllerClient is a mock of SegmentControllerClient interface.
type MockSegmentControllerClient struct {
	ctrl     *gomock.Controller
	recorder *MockSegmentControllerClientMockRecorder
}

// MockSegmentControllerClientMockRecorder is the mock recorder for MockSegmentControllerClient.
type MockSegmentControllerClientMockRecorder struct {
	mock *MockSegmentControllerClient
}

// NewMockSegmentControllerClient creates a new mock instance.
func NewMockSegmentControllerClient(ctrl *gomock.Controller) *MockSegmentControllerClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSegmentControllerClient) EXPECT() *MockSegmentControllerClientMockRecorder {
	_ = "STUB: not implemented"

	// QuerySegmentRouteInfo mocks base method.
	return nil
}

func (m *MockSegmentControllerClient) QuerySegmentRouteInfo(ctx context.Context, in *QuerySegmentRouteInfoRequest, opts ...grpc.CallOption) (*QuerySegmentRouteInfoResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// QuerySegmentRouteInfo indicates an expected call of QuerySegmentRouteInfo.
func (mr *MockSegmentControllerClientMockRecorder) QuerySegmentRouteInfo(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterSegmentServer mocks base method.
func (m *MockSegmentControllerClient) RegisterSegmentServer(ctx context.Context, in *RegisterSegmentServerRequest, opts ...grpc.CallOption) (*RegisterSegmentServerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RegisterSegmentServer indicates an expected call of RegisterSegmentServer.
func (mr *MockSegmentControllerClientMockRecorder) RegisterSegmentServer(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReportSegmentBlockIsFull mocks base method.
func (m *MockSegmentControllerClient) ReportSegmentBlockIsFull(ctx context.Context, in *SegmentHeartbeatRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReportSegmentBlockIsFull indicates an expected call of ReportSegmentBlockIsFull.
func (mr *MockSegmentControllerClientMockRecorder) ReportSegmentBlockIsFull(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReportSegmentLeader mocks base method.
func (m *MockSegmentControllerClient) ReportSegmentLeader(ctx context.Context, in *ReportSegmentLeaderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReportSegmentLeader indicates an expected call of ReportSegmentLeader.
func (mr *MockSegmentControllerClientMockRecorder) ReportSegmentLeader(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SegmentHeartbeat mocks base method.
func (m *MockSegmentControllerClient) SegmentHeartbeat(ctx context.Context, opts ...grpc.CallOption) (SegmentController_SegmentHeartbeatClient, error) {
	_ = "STUB: not implemented"
	return *new(SegmentController_SegmentHeartbeatClient), nil
}

// SegmentHeartbeat indicates an expected call of SegmentHeartbeat.
func (mr *MockSegmentControllerClientMockRecorder) SegmentHeartbeat(ctx interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UnregisterSegmentServer mocks base method.
func (m *MockSegmentControllerClient) UnregisterSegmentServer(ctx context.Context, in *UnregisterSegmentServerRequest, opts ...grpc.CallOption) (*UnregisterSegmentServerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnregisterSegmentServer indicates an expected call of UnregisterSegmentServer.
func (mr *MockSegmentControllerClientMockRecorder) UnregisterSegmentServer(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockSegmentControllerServer is a mock of SegmentControllerServer interface.
type MockSegmentControllerServer struct {
	ctrl     *gomock.Controller
	recorder *MockSegmentControllerServerMockRecorder
}

// MockSegmentControllerServerMockRecorder is the mock recorder for MockSegmentControllerServer.
type MockSegmentControllerServerMockRecorder struct {
	mock *MockSegmentControllerServer
}

// NewMockSegmentControllerServer creates a new mock instance.
func NewMockSegmentControllerServer(ctrl *gomock.Controller) *MockSegmentControllerServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSegmentControllerServer) EXPECT() *MockSegmentControllerServerMockRecorder {
	_ = "STUB: not implemented"

	// QuerySegmentRouteInfo mocks base method.
	return nil
}

func (m *MockSegmentControllerServer) QuerySegmentRouteInfo(ctx context.Context, in *QuerySegmentRouteInfoRequest) (*QuerySegmentRouteInfoResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// QuerySegmentRouteInfo indicates an expected call of QuerySegmentRouteInfo.
func (mr *MockSegmentControllerServerMockRecorder) QuerySegmentRouteInfo(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterSegmentServer mocks base method.
func (m *MockSegmentControllerServer) RegisterSegmentServer(ctx context.Context, in *RegisterSegmentServerRequest) (*RegisterSegmentServerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RegisterSegmentServer indicates an expected call of RegisterSegmentServer.
func (mr *MockSegmentControllerServerMockRecorder) RegisterSegmentServer(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReportSegmentBlockIsFull mocks base method.
func (m *MockSegmentControllerServer) ReportSegmentBlockIsFull(ctx context.Context, in *SegmentHeartbeatRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReportSegmentBlockIsFull indicates an expected call of ReportSegmentBlockIsFull.
func (mr *MockSegmentControllerServerMockRecorder) ReportSegmentBlockIsFull(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReportSegmentLeader mocks base method.
func (m *MockSegmentControllerServer) ReportSegmentLeader(ctx context.Context, in *ReportSegmentLeaderRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReportSegmentLeader indicates an expected call of ReportSegmentLeader.
func (mr *MockSegmentControllerServerMockRecorder) ReportSegmentLeader(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SegmentHeartbeat mocks base method.
func (m *MockSegmentControllerServer) SegmentHeartbeat(server SegmentController_SegmentHeartbeatServer) error {
	_ = "STUB: not implemented"
	return nil
}

// SegmentHeartbeat indicates an expected call of SegmentHeartbeat.
func (mr *MockSegmentControllerServerMockRecorder) SegmentHeartbeat(server interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UnregisterSegmentServer mocks base method.
func (m *MockSegmentControllerServer) UnregisterSegmentServer(ctx context.Context, in *UnregisterSegmentServerRequest) (*UnregisterSegmentServerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnregisterSegmentServer indicates an expected call of UnregisterSegmentServer.
func (mr *MockSegmentControllerServerMockRecorder) UnregisterSegmentServer(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockTriggerController_TriggerWorkerHeartbeatClient is a mock of TriggerController_TriggerWorkerHeartbeatClient interface.
type MockTriggerController_TriggerWorkerHeartbeatClient struct {
	ctrl     *gomock.Controller
	recorder *MockTriggerController_TriggerWorkerHeartbeatClientMockRecorder
}

// MockTriggerController_TriggerWorkerHeartbeatClientMockRecorder is the mock recorder for MockTriggerController_TriggerWorkerHeartbeatClient.
type MockTriggerController_TriggerWorkerHeartbeatClientMockRecorder struct {
	mock *MockTriggerController_TriggerWorkerHeartbeatClient
}

// NewMockTriggerController_TriggerWorkerHeartbeatClient creates a new mock instance.
func NewMockTriggerController_TriggerWorkerHeartbeatClient(ctrl *gomock.Controller) *MockTriggerController_TriggerWorkerHeartbeatClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTriggerController_TriggerWorkerHeartbeatClient) EXPECT() *MockTriggerController_TriggerWorkerHeartbeatClientMockRecorder {
	_ = "STUB: not implemented"

	// CloseAndRecv mocks base method.
	return nil
}

func (m *MockTriggerController_TriggerWorkerHeartbeatClient) CloseAndRecv() (*TriggerWorkerHeartbeatResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CloseAndRecv indicates an expected call of CloseAndRecv.
func (mr *MockTriggerController_TriggerWorkerHeartbeatClientMockRecorder) CloseAndRecv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CloseSend mocks base method.
func (m *MockTriggerController_TriggerWorkerHeartbeatClient) CloseSend() error {
	_ = "STUB: not implemented"
	return nil
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockTriggerController_TriggerWorkerHeartbeatClientMockRecorder) CloseSend() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Context mocks base method.
func (m *MockTriggerController_TriggerWorkerHeartbeatClient) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockTriggerController_TriggerWorkerHeartbeatClientMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Header mocks base method.
func (m *MockTriggerController_TriggerWorkerHeartbeatClient) Header() (metadata.MD, error) {
	_ = "STUB: not implemented"
	return *new(metadata.MD), nil
}

// Header indicates an expected call of Header.
func (mr *MockTriggerController_TriggerWorkerHeartbeatClientMockRecorder) Header() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m *MockTriggerController_TriggerWorkerHeartbeatClient) RecvMsg(arg0 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockTriggerController_TriggerWorkerHeartbeatClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Send mocks base method.
func (m *MockTriggerController_TriggerWorkerHeartbeatClient) Send(arg0 *TriggerWorkerHeartbeatRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// Send indicates an expected call of Send.
func (mr *MockTriggerController_TriggerWorkerHeartbeatClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m *MockTriggerController_TriggerWorkerHeartbeatClient) SendMsg(arg0 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockTriggerController_TriggerWorkerHeartbeatClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Trailer mocks base method.
func (m *MockTriggerController_TriggerWorkerHeartbeatClient) Trailer() metadata.MD {
	_ = "STUB: not implemented"
	return *new(metadata.MD)
}

// Trailer indicates an expected call of Trailer.
func (mr *MockTriggerController_TriggerWorkerHeartbeatClientMockRecorder) Trailer() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockTriggerController_TriggerWorkerHeartbeatServer is a mock of TriggerController_TriggerWorkerHeartbeatServer interface.
type MockTriggerController_TriggerWorkerHeartbeatServer struct {
	ctrl     *gomock.Controller
	recorder *MockTriggerController_TriggerWorkerHeartbeatServerMockRecorder
}

// MockTriggerController_TriggerWorkerHeartbeatServerMockRecorder is the mock recorder for MockTriggerController_TriggerWorkerHeartbeatServer.
type MockTriggerController_TriggerWorkerHeartbeatServerMockRecorder struct {
	mock *MockTriggerController_TriggerWorkerHeartbeatServer
}

// NewMockTriggerController_TriggerWorkerHeartbeatServer creates a new mock instance.
func NewMockTriggerController_TriggerWorkerHeartbeatServer(ctrl *gomock.Controller) *MockTriggerController_TriggerWorkerHeartbeatServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTriggerController_TriggerWorkerHeartbeatServer) EXPECT() *MockTriggerController_TriggerWorkerHeartbeatServerMockRecorder {
	_ = "STUB: not implemented"

	// Context mocks base method.
	return nil
}

func (m *MockTriggerController_TriggerWorkerHeartbeatServer) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockTriggerController_TriggerWorkerHeartbeatServerMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Recv mocks base method.
func (m *MockTriggerController_TriggerWorkerHeartbeatServer) Recv() (*TriggerWorkerHeartbeatResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Recv indicates an expected call of Recv.
func (mr *MockTriggerController_TriggerWorkerHeartbeatServerMockRecorder) Recv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m *MockTriggerController_TriggerWorkerHeartbeatServer) RecvMsg(arg0 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockTriggerController_TriggerWorkerHeartbeatServerMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendAndClose mocks base method.
func (m *MockTriggerController_TriggerWorkerHeartbeatServer) SendAndClose(arg0 *TriggerWorkerHeartbeatRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// SendAndClose indicates an expected call of SendAndClose.
func (mr *MockTriggerController_TriggerWorkerHeartbeatServerMockRecorder) SendAndClose(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader mocks base method.
func (m *MockTriggerController_TriggerWorkerHeartbeatServer) SendHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockTriggerController_TriggerWorkerHeartbeatServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m *MockTriggerController_TriggerWorkerHeartbeatServer) SendMsg(arg0 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockTriggerController_TriggerWorkerHeartbeatServerMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader mocks base method.
func (m *MockTriggerController_TriggerWorkerHeartbeatServer) SetHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockTriggerController_TriggerWorkerHeartbeatServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTrailer mocks base method.
func (m *MockTriggerController_TriggerWorkerHeartbeatServer) SetTrailer(arg0 metadata.MD) {
	_ = "STUB: not implemented"
	return
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockTriggerController_TriggerWorkerHeartbeatServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockTriggerControllerClient is a mock of TriggerControllerClient interface.
type MockTriggerControllerClient struct {
	ctrl     *gomock.Controller
	recorder *MockTriggerControllerClientMockRecorder
}

// MockTriggerControllerClientMockRecorder is the mock recorder for MockTriggerControllerClient.
type MockTriggerControllerClientMockRecorder struct {
	mock *MockTriggerControllerClient
}

// NewMockTriggerControllerClient creates a new mock instance.
func NewMockTriggerControllerClient(ctrl *gomock.Controller) *MockTriggerControllerClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTriggerControllerClient) EXPECT() *MockTriggerControllerClientMockRecorder {
	_ = "STUB: not implemented"

	// CommitOffset mocks base method.
	return nil
}

func (m *MockTriggerControllerClient) CommitOffset(ctx context.Context, in *CommitOffsetRequest, opts ...grpc.CallOption) (*CommitOffsetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CommitOffset indicates an expected call of CommitOffset.
func (mr *MockTriggerControllerClientMockRecorder) CommitOffset(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateSubscription mocks base method.
func (m *MockTriggerControllerClient) CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockTriggerControllerClientMockRecorder) CreateSubscription(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteSubscription mocks base method.
func (m *MockTriggerControllerClient) DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteSubscription indicates an expected call of DeleteSubscription.
func (mr *MockTriggerControllerClientMockRecorder) DeleteSubscription(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DisableSubscription mocks base method.
func (m *MockTriggerControllerClient) DisableSubscription(ctx context.Context, in *DisableSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DisableSubscription indicates an expected call of DisableSubscription.
func (mr *MockTriggerControllerClientMockRecorder) DisableSubscription(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetDeadLetterEventOffset mocks base method.
func (m *MockTriggerControllerClient) GetDeadLetterEventOffset(ctx context.Context, in *GetDeadLetterEventOffsetRequest, opts ...grpc.CallOption) (*GetDeadLetterEventOffsetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDeadLetterEventOffset indicates an expected call of GetDeadLetterEventOffset.
func (mr *MockTriggerControllerClientMockRecorder) GetDeadLetterEventOffset(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSubscription mocks base method.
func (m *MockTriggerControllerClient) GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetSubscription indicates an expected call of GetSubscription.
func (mr *MockTriggerControllerClientMockRecorder) GetSubscription(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListSubscription mocks base method.
func (m *MockTriggerControllerClient) ListSubscription(ctx context.Context, in *ListSubscriptionRequest, opts ...grpc.CallOption) (*ListSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListSubscription indicates an expected call of ListSubscription.
func (mr *MockTriggerControllerClientMockRecorder) ListSubscription(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterTriggerWorker mocks base method.
func (m *MockTriggerControllerClient) RegisterTriggerWorker(ctx context.Context, in *RegisterTriggerWorkerRequest, opts ...grpc.CallOption) (*RegisterTriggerWorkerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RegisterTriggerWorker indicates an expected call of RegisterTriggerWorker.
func (mr *MockTriggerControllerClientMockRecorder) RegisterTriggerWorker(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResetOffsetToTimestamp mocks base method.
func (m *MockTriggerControllerClient) ResetOffsetToTimestamp(ctx context.Context, in *ResetOffsetToTimestampRequest, opts ...grpc.CallOption) (*ResetOffsetToTimestampResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ResetOffsetToTimestamp indicates an expected call of ResetOffsetToTimestamp.
func (mr *MockTriggerControllerClientMockRecorder) ResetOffsetToTimestamp(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResumeSubscription mocks base method.
func (m *MockTriggerControllerClient) ResumeSubscription(ctx context.Context, in *ResumeSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ResumeSubscription indicates an expected call of ResumeSubscription.
func (mr *MockTriggerControllerClientMockRecorder) ResumeSubscription(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetDeadLetterEventOffset mocks base method.
func (m *MockTriggerControllerClient) SetDeadLetterEventOffset(ctx context.Context, in *SetDeadLetterEventOffsetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SetDeadLetterEventOffset indicates an expected call of SetDeadLetterEventOffset.
func (mr *MockTriggerControllerClientMockRecorder) SetDeadLetterEventOffset(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// TriggerWorkerHeartbeat mocks base method.
func (m *MockTriggerControllerClient) TriggerWorkerHeartbeat(ctx context.Context, opts ...grpc.CallOption) (TriggerController_TriggerWorkerHeartbeatClient, error) {
	_ = "STUB: not implemented"
	return *new(TriggerController_TriggerWorkerHeartbeatClient), nil
}

// TriggerWorkerHeartbeat indicates an expected call of TriggerWorkerHeartbeat.
func (mr *MockTriggerControllerClientMockRecorder) TriggerWorkerHeartbeat(ctx interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UnregisterTriggerWorker mocks base method.
func (m *MockTriggerControllerClient) UnregisterTriggerWorker(ctx context.Context, in *UnregisterTriggerWorkerRequest, opts ...grpc.CallOption) (*UnregisterTriggerWorkerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnregisterTriggerWorker indicates an expected call of UnregisterTriggerWorker.
func (mr *MockTriggerControllerClientMockRecorder) UnregisterTriggerWorker(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateSubscription mocks base method.
func (m *MockTriggerControllerClient) UpdateSubscription(ctx context.Context, in *UpdateSubscriptionRequest, opts ...grpc.CallOption) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateSubscription indicates an expected call of UpdateSubscription.
func (mr *MockTriggerControllerClientMockRecorder) UpdateSubscription(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockTriggerControllerServer is a mock of TriggerControllerServer interface.
type MockTriggerControllerServer struct {
	ctrl     *gomock.Controller
	recorder *MockTriggerControllerServerMockRecorder
}

// MockTriggerControllerServerMockRecorder is the mock recorder for MockTriggerControllerServer.
type MockTriggerControllerServerMockRecorder struct {
	mock *MockTriggerControllerServer
}

// NewMockTriggerControllerServer creates a new mock instance.
func NewMockTriggerControllerServer(ctrl *gomock.Controller) *MockTriggerControllerServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTriggerControllerServer) EXPECT() *MockTriggerControllerServerMockRecorder {
	_ = "STUB: not implemented"

	// CommitOffset mocks base method.
	return nil
}

func (m *MockTriggerControllerServer) CommitOffset(ctx context.Context, in *CommitOffsetRequest) (*CommitOffsetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CommitOffset indicates an expected call of CommitOffset.
func (mr *MockTriggerControllerServerMockRecorder) CommitOffset(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateSubscription mocks base method.
func (m *MockTriggerControllerServer) CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockTriggerControllerServerMockRecorder) CreateSubscription(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteSubscription mocks base method.
func (m *MockTriggerControllerServer) DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteSubscription indicates an expected call of DeleteSubscription.
func (mr *MockTriggerControllerServerMockRecorder) DeleteSubscription(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DisableSubscription mocks base method.
func (m *MockTriggerControllerServer) DisableSubscription(ctx context.Context, in *DisableSubscriptionRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DisableSubscription indicates an expected call of DisableSubscription.
func (mr *MockTriggerControllerServerMockRecorder) DisableSubscription(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetDeadLetterEventOffset mocks base method.
func (m *MockTriggerControllerServer) GetDeadLetterEventOffset(ctx context.Context, in *GetDeadLetterEventOffsetRequest) (*GetDeadLetterEventOffsetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDeadLetterEventOffset indicates an expected call of GetDeadLetterEventOffset.
func (mr *MockTriggerControllerServerMockRecorder) GetDeadLetterEventOffset(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSubscription mocks base method.
func (m *MockTriggerControllerServer) GetSubscription(ctx context.Context, in *GetSubscriptionRequest) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetSubscription indicates an expected call of GetSubscription.
func (mr *MockTriggerControllerServerMockRecorder) GetSubscription(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListSubscription mocks base method.
func (m *MockTriggerControllerServer) ListSubscription(ctx context.Context, in *ListSubscriptionRequest) (*ListSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListSubscription indicates an expected call of ListSubscription.
func (mr *MockTriggerControllerServerMockRecorder) ListSubscription(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterTriggerWorker mocks base method.
func (m *MockTriggerControllerServer) RegisterTriggerWorker(ctx context.Context, in *RegisterTriggerWorkerRequest) (*RegisterTriggerWorkerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RegisterTriggerWorker indicates an expected call of RegisterTriggerWorker.
func (mr *MockTriggerControllerServerMockRecorder) RegisterTriggerWorker(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResetOffsetToTimestamp mocks base method.
func (m *MockTriggerControllerServer) ResetOffsetToTimestamp(ctx context.Context, in *ResetOffsetToTimestampRequest) (*ResetOffsetToTimestampResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ResetOffsetToTimestamp indicates an expected call of ResetOffsetToTimestamp.
func (mr *MockTriggerControllerServerMockRecorder) ResetOffsetToTimestamp(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResumeSubscription mocks base method.
func (m *MockTriggerControllerServer) ResumeSubscription(ctx context.Context, in *ResumeSubscriptionRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ResumeSubscription indicates an expected call of ResumeSubscription.
func (mr *MockTriggerControllerServerMockRecorder) ResumeSubscription(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetDeadLetterEventOffset mocks base method.
func (m *MockTriggerControllerServer) SetDeadLetterEventOffset(ctx context.Context, in *SetDeadLetterEventOffsetRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SetDeadLetterEventOffset indicates an expected call of SetDeadLetterEventOffset.
func (mr *MockTriggerControllerServerMockRecorder) SetDeadLetterEventOffset(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// TriggerWorkerHeartbeat mocks base method.
func (m *MockTriggerControllerServer) TriggerWorkerHeartbeat(server TriggerController_TriggerWorkerHeartbeatServer) error {
	_ = "STUB: not implemented"
	return nil
}

// TriggerWorkerHeartbeat indicates an expected call of TriggerWorkerHeartbeat.
func (mr *MockTriggerControllerServerMockRecorder) TriggerWorkerHeartbeat(server interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UnregisterTriggerWorker mocks base method.
func (m *MockTriggerControllerServer) UnregisterTriggerWorker(ctx context.Context, in *UnregisterTriggerWorkerRequest) (*UnregisterTriggerWorkerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnregisterTriggerWorker indicates an expected call of UnregisterTriggerWorker.
func (mr *MockTriggerControllerServerMockRecorder) UnregisterTriggerWorker(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateSubscription mocks base method.
func (m *MockTriggerControllerServer) UpdateSubscription(ctx context.Context, in *UpdateSubscriptionRequest) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateSubscription indicates an expected call of UpdateSubscription.
func (mr *MockTriggerControllerServerMockRecorder) UpdateSubscription(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockSnowflakeControllerClient is a mock of SnowflakeControllerClient interface.
type MockSnowflakeControllerClient struct {
	ctrl     *gomock.Controller
	recorder *MockSnowflakeControllerClientMockRecorder
}

// MockSnowflakeControllerClientMockRecorder is the mock recorder for MockSnowflakeControllerClient.
type MockSnowflakeControllerClientMockRecorder struct {
	mock *MockSnowflakeControllerClient
}

// NewMockSnowflakeControllerClient creates a new mock instance.
func NewMockSnowflakeControllerClient(ctrl *gomock.Controller) *MockSnowflakeControllerClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnowflakeControllerClient) EXPECT() *MockSnowflakeControllerClientMockRecorder {
	_ = "STUB: not implemented"

	// GetClusterStartTime mocks base method.
	return nil
}

func (m *MockSnowflakeControllerClient) GetClusterStartTime(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*timestamppb.Timestamp, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetClusterStartTime indicates an expected call of GetClusterStartTime.
func (mr *MockSnowflakeControllerClientMockRecorder) GetClusterStartTime(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterNode mocks base method.
func (m *MockSnowflakeControllerClient) RegisterNode(ctx context.Context, in *wrapperspb.UInt32Value, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RegisterNode indicates an expected call of RegisterNode.
func (mr *MockSnowflakeControllerClientMockRecorder) RegisterNode(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UnregisterNode mocks base method.
func (m *MockSnowflakeControllerClient) UnregisterNode(ctx context.Context, in *wrapperspb.UInt32Value, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnregisterNode indicates an expected call of UnregisterNode.
func (mr *MockSnowflakeControllerClientMockRecorder) UnregisterNode(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockSnowflakeControllerServer is a mock of SnowflakeControllerServer interface.
type MockSnowflakeControllerServer struct {
	ctrl     *gomock.Controller
	recorder *MockSnowflakeControllerServerMockRecorder
}

// MockSnowflakeControllerServerMockRecorder is the mock recorder for MockSnowflakeControllerServer.
type MockSnowflakeControllerServerMockRecorder struct {
	mock *MockSnowflakeControllerServer
}

// NewMockSnowflakeControllerServer creates a new mock instance.
func NewMockSnowflakeControllerServer(ctrl *gomock.Controller) *MockSnowflakeControllerServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnowflakeControllerServer) EXPECT() *MockSnowflakeControllerServerMockRecorder {
	_ = "STUB: not implemented"

	// GetClusterStartTime mocks base method.
	return nil
}

func (m *MockSnowflakeControllerServer) GetClusterStartTime(ctx context.Context, in *emptypb.Empty) (*timestamppb.Timestamp, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetClusterStartTime indicates an expected call of GetClusterStartTime.
func (mr *MockSnowflakeControllerServerMockRecorder) GetClusterStartTime(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterNode mocks base method.
func (m *MockSnowflakeControllerServer) RegisterNode(ctx context.Context, in *wrapperspb.UInt32Value) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RegisterNode indicates an expected call of RegisterNode.
func (mr *MockSnowflakeControllerServerMockRecorder) RegisterNode(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UnregisterNode mocks base method.
func (m *MockSnowflakeControllerServer) UnregisterNode(ctx context.Context, in *wrapperspb.UInt32Value) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnregisterNode indicates an expected call of UnregisterNode.
func (mr *MockSnowflakeControllerServerMockRecorder) UnregisterNode(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockAuthControllerClient is a mock of AuthControllerClient interface.
type MockAuthControllerClient struct {
	ctrl     *gomock.Controller
	recorder *MockAuthControllerClientMockRecorder
}

// MockAuthControllerClientMockRecorder is the mock recorder for MockAuthControllerClient.
type MockAuthControllerClientMockRecorder struct {
	mock *MockAuthControllerClient
}

// NewMockAuthControllerClient creates a new mock instance.
func NewMockAuthControllerClient(ctrl *gomock.Controller) *MockAuthControllerClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthControllerClient) EXPECT() *MockAuthControllerClientMockRecorder {
	_ = "STUB: not implemented"

	// CreateToken mocks base method.
	return nil
}

func (m *MockAuthControllerClient) CreateToken(ctx context.Context, in *CreateTokenRequest, opts ...grpc.CallOption) (*meta.Token, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockAuthControllerClientMockRecorder) CreateToken(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateUser mocks base method.
func (m *MockAuthControllerClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*meta.User, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAuthControllerClientMockRecorder) CreateUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteToken mocks base method.
func (m *MockAuthControllerClient) DeleteToken(ctx context.Context, in *DeleteTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteToken indicates an expected call of DeleteToken.
func (mr *MockAuthControllerClientMockRecorder) DeleteToken(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteUser mocks base method.
func (m *MockAuthControllerClient) DeleteUser(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockAuthControllerClientMockRecorder) DeleteUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetResourceRole mocks base method.
func (m *MockAuthControllerClient) GetResourceRole(ctx context.Context, in *GetResourceRoleRequest, opts ...grpc.CallOption) (*GetResourceRoleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetResourceRole indicates an expected call of GetResourceRole.
func (mr *MockAuthControllerClientMockRecorder) GetResourceRole(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetToken mocks base method.
func (m *MockAuthControllerClient) GetToken(ctx context.Context, in *wrapperspb.UInt64Value, opts ...grpc.CallOption) (*meta.Token, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetToken indicates an expected call of GetToken.
func (mr *MockAuthControllerClientMockRecorder) GetToken(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUser mocks base method.
func (m *MockAuthControllerClient) GetUser(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*meta.User, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUser indicates an expected call of GetUser.
func (mr *MockAuthControllerClientMockRecorder) GetUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUserByToken mocks base method.
func (m *MockAuthControllerClient) GetUserByToken(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*wrapperspb.StringValue, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUserByToken indicates an expected call of GetUserByToken.
func (mr *MockAuthControllerClientMockRecorder) GetUserByToken(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUserRole mocks base method.
func (m *MockAuthControllerClient) GetUserRole(ctx context.Context, in *GetUserRoleRequest, opts ...grpc.CallOption) (*GetUserRoleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockAuthControllerClientMockRecorder) GetUserRole(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUserToken mocks base method.
func (m *MockAuthControllerClient) GetUserToken(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUserToken indicates an expected call of GetUserToken.
func (mr *MockAuthControllerClientMockRecorder) GetUserToken(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GrantRole mocks base method.
func (m *MockAuthControllerClient) GrantRole(ctx context.Context, in *RoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GrantRole indicates an expected call of GrantRole.
func (mr *MockAuthControllerClientMockRecorder) GrantRole(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListToken mocks base method.
func (m *MockAuthControllerClient) ListToken(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTokenResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListToken indicates an expected call of ListToken.
func (mr *MockAuthControllerClientMockRecorder) ListToken(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListUser mocks base method.
func (m *MockAuthControllerClient) ListUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListUserResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListUser indicates an expected call of ListUser.
func (mr *MockAuthControllerClientMockRecorder) ListUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RevokeRole mocks base method.
func (m *MockAuthControllerClient) RevokeRole(ctx context.Context, in *RoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RevokeRole indicates an expected call of RevokeRole.
func (mr *MockAuthControllerClientMockRecorder) RevokeRole(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockAuthControllerServer is a mock of AuthControllerServer interface.
type MockAuthControllerServer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthControllerServerMockRecorder
}

// MockAuthControllerServerMockRecorder is the mock recorder for MockAuthControllerServer.
type MockAuthControllerServerMockRecorder struct {
	mock *MockAuthControllerServer
}

// NewMockAuthControllerServer creates a new mock instance.
func NewMockAuthControllerServer(ctrl *gomock.Controller) *MockAuthControllerServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthControllerServer) EXPECT() *MockAuthControllerServerMockRecorder {
	_ = "STUB: not implemented"

	// CreateToken mocks base method.
	return nil
}

func (m *MockAuthControllerServer) CreateToken(ctx context.Context, in *CreateTokenRequest) (*meta.Token, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockAuthControllerServerMockRecorder) CreateToken(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateUser mocks base method.
func (m *MockAuthControllerServer) CreateUser(ctx context.Context, in *CreateUserRequest) (*meta.User, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAuthControllerServerMockRecorder) CreateUser(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteToken mocks base method.
func (m *MockAuthControllerServer) DeleteToken(ctx context.Context, in *DeleteTokenRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteToken indicates an expected call of DeleteToken.
func (mr *MockAuthControllerServerMockRecorder) DeleteToken(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteUser mocks base method.
func (m *MockAuthControllerServer) DeleteUser(ctx context.Context, in *wrapperspb.StringValue) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockAuthControllerServerMockRecorder) DeleteUser(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetResourceRole mocks base method.
func (m *MockAuthControllerServer) GetResourceRole(ctx context.Context, in *GetResourceRoleRequest) (*GetResourceRoleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetResourceRole indicates an expected call of GetResourceRole.
func (mr *MockAuthControllerServerMockRecorder) GetResourceRole(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetToken mocks base method.
func (m *MockAuthControllerServer) GetToken(ctx context.Context, in *wrapperspb.UInt64Value) (*meta.Token, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetToken indicates an expected call of GetToken.
func (mr *MockAuthControllerServerMockRecorder) GetToken(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUser mocks base method.
func (m *MockAuthControllerServer) GetUser(ctx context.Context, in *wrapperspb.StringValue) (*meta.User, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUser indicates an expected call of GetUser.
func (mr *MockAuthControllerServerMockRecorder) GetUser(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUserByToken mocks base method.
func (m *MockAuthControllerServer) GetUserByToken(ctx context.Context, in *wrapperspb.StringValue) (*wrapperspb.StringValue, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUserByToken indicates an expected call of GetUserByToken.
func (mr *MockAuthControllerServerMockRecorder) GetUserByToken(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUserRole mocks base method.
func (m *MockAuthControllerServer) GetUserRole(ctx context.Context, in *GetUserRoleRequest) (*GetUserRoleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockAuthControllerServerMockRecorder) GetUserRole(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUserToken mocks base method.
func (m *MockAuthControllerServer) GetUserToken(ctx context.Context, in *wrapperspb.StringValue) (*GetTokenResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUserToken indicates an expected call of GetUserToken.
func (mr *MockAuthControllerServerMockRecorder) GetUserToken(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GrantRole mocks base method.
func (m *MockAuthControllerServer) GrantRole(ctx context.Context, in *RoleRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GrantRole indicates an expected call of GrantRole.
func (mr *MockAuthControllerServerMockRecorder) GrantRole(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListToken mocks base method.
func (m *MockAuthControllerServer) ListToken(ctx context.Context, in *emptypb.Empty) (*ListTokenResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListToken indicates an expected call of ListToken.
func (mr *MockAuthControllerServerMockRecorder) ListToken(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListUser mocks base method.
func (m *MockAuthControllerServer) ListUser(ctx context.Context, in *emptypb.Empty) (*ListUserResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListUser indicates an expected call of ListUser.
func (mr *MockAuthControllerServerMockRecorder) ListUser(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RevokeRole mocks base method.
func (m *MockAuthControllerServer) RevokeRole(ctx context.Context, in *RoleRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RevokeRole indicates an expected call of RevokeRole.
func (mr *MockAuthControllerServerMockRecorder) RevokeRole(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
