// Copyright 2022 Linkall Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: vanus/core/controller/controller.proto

package controller

import (
	context "context"

	meta "github.com/vanus-labs/vanus/api/meta"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PingServer_Ping_FullMethodName = "/vanus.core.controller.PingServer/Ping"
)

// PingServerClient is the client API for PingServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PingServerClient interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PingResponse, error)
}

type pingServerClient struct {
	cc grpc.ClientConnInterface
}

func NewPingServerClient(cc grpc.ClientConnInterface) PingServerClient {
	_ = "STUB: not implemented"
	return *new(PingServerClient)
}

func (c *pingServerClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PingResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PingServerServer is the server API for PingServer service.
// All implementations should embed UnimplementedPingServerServer
// for forward compatibility
type PingServerServer interface {
	Ping(context.Context, *emptypb.Empty) (*PingResponse, error)
}

// UnimplementedPingServerServer should be embedded to have forward compatible implementations.
type UnimplementedPingServerServer struct {
}

func (UnimplementedPingServerServer) Ping(context.Context, *emptypb.Empty) (*PingResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnsafePingServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PingServerServer will
// result in compilation errors.
type UnsafePingServerServer interface {
	mustEmbedUnimplementedPingServerServer()
}

func RegisterPingServerServer(s grpc.ServiceRegistrar, srv PingServerServer) {
	_ = "STUB: not implemented"
	return
}

func _PingServer_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PingServer_ServiceDesc is the grpc.ServiceDesc for PingServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PingServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vanus.core.controller.PingServer",
	HandlerType: (*PingServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PingServer_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vanus/core/controller/controller.proto",
}

const (
	NamespaceController_CreateNamespace_FullMethodName               = "/vanus.core.controller.NamespaceController/CreateNamespace"
	NamespaceController_ListNamespace_FullMethodName                 = "/vanus.core.controller.NamespaceController/ListNamespace"
	NamespaceController_GetNamespace_FullMethodName                  = "/vanus.core.controller.NamespaceController/GetNamespace"
	NamespaceController_DeleteNamespace_FullMethodName               = "/vanus.core.controller.NamespaceController/DeleteNamespace"
	NamespaceController_GetNamespaceWithHumanFriendly_FullMethodName = "/vanus.core.controller.NamespaceController/GetNamespaceWithHumanFriendly"
)

// NamespaceControllerClient is the client API for NamespaceController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NamespaceControllerClient interface {
	CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*meta.Namespace, error)
	ListNamespace(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListNamespaceResponse, error)
	GetNamespace(ctx context.Context, in *GetNamespaceRequest, opts ...grpc.CallOption) (*meta.Namespace, error)
	DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetNamespaceWithHumanFriendly(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*meta.Namespace, error)
}

type namespaceControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewNamespaceControllerClient(cc grpc.ClientConnInterface) NamespaceControllerClient {
	_ = "STUB: not implemented"
	return *new(NamespaceControllerClient)
}

func (c *namespaceControllerClient) CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *namespaceControllerClient) ListNamespace(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListNamespaceResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *namespaceControllerClient) GetNamespace(ctx context.Context, in *GetNamespaceRequest, opts ...grpc.CallOption) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *namespaceControllerClient) DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *namespaceControllerClient) GetNamespaceWithHumanFriendly(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NamespaceControllerServer is the server API for NamespaceController service.
// All implementations should embed UnimplementedNamespaceControllerServer
// for forward compatibility
type NamespaceControllerServer interface {
	CreateNamespace(context.Context, *CreateNamespaceRequest) (*meta.Namespace, error)
	ListNamespace(context.Context, *emptypb.Empty) (*ListNamespaceResponse, error)
	GetNamespace(context.Context, *GetNamespaceRequest) (*meta.Namespace, error)
	DeleteNamespace(context.Context, *DeleteNamespaceRequest) (*emptypb.Empty, error)
	GetNamespaceWithHumanFriendly(context.Context, *wrapperspb.StringValue) (*meta.Namespace, error)
}

// UnimplementedNamespaceControllerServer should be embedded to have forward compatible implementations.
type UnimplementedNamespaceControllerServer struct {
}

func (UnimplementedNamespaceControllerServer) CreateNamespace(context.Context, *CreateNamespaceRequest) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedNamespaceControllerServer) ListNamespace(context.Context, *emptypb.Empty) (*ListNamespaceResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedNamespaceControllerServer) GetNamespace(context.Context, *GetNamespaceRequest) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedNamespaceControllerServer) DeleteNamespace(context.Context, *DeleteNamespaceRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedNamespaceControllerServer) GetNamespaceWithHumanFriendly(context.Context, *wrapperspb.StringValue) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnsafeNamespaceControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NamespaceControllerServer will
// result in compilation errors.
type UnsafeNamespaceControllerServer interface {
	mustEmbedUnimplementedNamespaceControllerServer()
}

func RegisterNamespaceControllerServer(s grpc.ServiceRegistrar, srv NamespaceControllerServer) {
	_ = "STUB: not implemented"
	return
}

func _NamespaceController_CreateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _NamespaceController_ListNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _NamespaceController_GetNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _NamespaceController_DeleteNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _NamespaceController_GetNamespaceWithHumanFriendly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// NamespaceController_ServiceDesc is the grpc.ServiceDesc for NamespaceController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NamespaceController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vanus.core.controller.NamespaceController",
	HandlerType: (*NamespaceControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNamespace",
			Handler:    _NamespaceController_CreateNamespace_Handler,
		},
		{
			MethodName: "ListNamespace",
			Handler:    _NamespaceController_ListNamespace_Handler,
		},
		{
			MethodName: "GetNamespace",
			Handler:    _NamespaceController_GetNamespace_Handler,
		},
		{
			MethodName: "DeleteNamespace",
			Handler:    _NamespaceController_DeleteNamespace_Handler,
		},
		{
			MethodName: "GetNamespaceWithHumanFriendly",
			Handler:    _NamespaceController_GetNamespaceWithHumanFriendly_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vanus/core/controller/controller.proto",
}

const (
	EventbusController_CreateEventbus_FullMethodName               = "/vanus.core.controller.EventbusController/CreateEventbus"
	EventbusController_CreateSystemEventbus_FullMethodName         = "/vanus.core.controller.EventbusController/CreateSystemEventbus"
	EventbusController_DeleteEventbus_FullMethodName               = "/vanus.core.controller.EventbusController/DeleteEventbus"
	EventbusController_GetEventbus_FullMethodName                  = "/vanus.core.controller.EventbusController/GetEventbus"
	EventbusController_ListEventbus_FullMethodName                 = "/vanus.core.controller.EventbusController/ListEventbus"
	EventbusController_UpdateEventbus_FullMethodName               = "/vanus.core.controller.EventbusController/UpdateEventbus"
	EventbusController_GetEventbusWithHumanFriendly_FullMethodName = "/vanus.core.controller.EventbusController/GetEventbusWithHumanFriendly"
)

// EventbusControllerClient is the client API for EventbusController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventbusControllerClient interface {
	// grpc -> HTTP
	CreateEventbus(ctx context.Context, in *CreateEventbusRequest, opts ...grpc.CallOption) (*meta.Eventbus, error)
	CreateSystemEventbus(ctx context.Context, in *CreateEventbusRequest, opts ...grpc.CallOption) (*meta.Eventbus, error)
	DeleteEventbus(ctx context.Context, in *wrapperspb.UInt64Value, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetEventbus(ctx context.Context, in *wrapperspb.UInt64Value, opts ...grpc.CallOption) (*meta.Eventbus, error)
	ListEventbus(ctx context.Context, in *ListEventbusRequest, opts ...grpc.CallOption) (*ListEventbusResponse, error)
	UpdateEventbus(ctx context.Context, in *UpdateEventbusRequest, opts ...grpc.CallOption) (*meta.Eventbus, error)
	GetEventbusWithHumanFriendly(ctx context.Context, in *GetEventbusWithHumanFriendlyRequest, opts ...grpc.CallOption) (*meta.Eventbus, error)
}

type eventbusControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewEventbusControllerClient(cc grpc.ClientConnInterface) EventbusControllerClient {
	_ = "STUB: not implemented"
	return *new(EventbusControllerClient)
}

func (c *eventbusControllerClient) CreateEventbus(ctx context.Context, in *CreateEventbusRequest, opts ...grpc.CallOption) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *eventbusControllerClient) CreateSystemEventbus(ctx context.Context, in *CreateEventbusRequest, opts ...grpc.CallOption) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *eventbusControllerClient) DeleteEventbus(ctx context.Context, in *wrapperspb.UInt64Value, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *eventbusControllerClient) GetEventbus(ctx context.Context, in *wrapperspb.UInt64Value, opts ...grpc.CallOption) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *eventbusControllerClient) ListEventbus(ctx context.Context, in *ListEventbusRequest, opts ...grpc.CallOption) (*ListEventbusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *eventbusControllerClient) UpdateEventbus(ctx context.Context, in *UpdateEventbusRequest, opts ...grpc.CallOption) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *eventbusControllerClient) GetEventbusWithHumanFriendly(ctx context.Context, in *GetEventbusWithHumanFriendlyRequest, opts ...grpc.CallOption) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EventbusControllerServer is the server API for EventbusController service.
// All implementations should embed UnimplementedEventbusControllerServer
// for forward compatibility
type EventbusControllerServer interface {
	// grpc -> HTTP
	CreateEventbus(context.Context, *CreateEventbusRequest) (*meta.Eventbus, error)
	CreateSystemEventbus(context.Context, *CreateEventbusRequest) (*meta.Eventbus, error)
	DeleteEventbus(context.Context, *wrapperspb.UInt64Value) (*emptypb.Empty, error)
	GetEventbus(context.Context, *wrapperspb.UInt64Value) (*meta.Eventbus, error)
	ListEventbus(context.Context, *ListEventbusRequest) (*ListEventbusResponse, error)
	UpdateEventbus(context.Context, *UpdateEventbusRequest) (*meta.Eventbus, error)
	GetEventbusWithHumanFriendly(context.Context, *GetEventbusWithHumanFriendlyRequest) (*meta.Eventbus, error)
}

// UnimplementedEventbusControllerServer should be embedded to have forward compatible implementations.
type UnimplementedEventbusControllerServer struct {
}

func (UnimplementedEventbusControllerServer) CreateEventbus(context.Context, *CreateEventbusRequest) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedEventbusControllerServer) CreateSystemEventbus(context.Context, *CreateEventbusRequest) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedEventbusControllerServer) DeleteEventbus(context.Context, *wrapperspb.UInt64Value) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedEventbusControllerServer) GetEventbus(context.Context, *wrapperspb.UInt64Value) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedEventbusControllerServer) ListEventbus(context.Context, *ListEventbusRequest) (*ListEventbusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedEventbusControllerServer) UpdateEventbus(context.Context, *UpdateEventbusRequest) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedEventbusControllerServer) GetEventbusWithHumanFriendly(context.Context, *GetEventbusWithHumanFriendlyRequest) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnsafeEventbusControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventbusControllerServer will
// result in compilation errors.
type UnsafeEventbusControllerServer interface {
	mustEmbedUnimplementedEventbusControllerServer()
}

func RegisterEventbusControllerServer(s grpc.ServiceRegistrar, srv EventbusControllerServer) {
	_ = "STUB: not implemented"
	return
}

func _EventbusController_CreateEventbus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _EventbusController_CreateSystemEventbus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _EventbusController_DeleteEventbus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _EventbusController_GetEventbus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _EventbusController_ListEventbus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _EventbusController_UpdateEventbus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _EventbusController_GetEventbusWithHumanFriendly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EventbusController_ServiceDesc is the grpc.ServiceDesc for EventbusController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventbusController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vanus.core.controller.EventbusController",
	HandlerType: (*EventbusControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEventbus",
			Handler:    _EventbusController_CreateEventbus_Handler,
		},
		{
			MethodName: "CreateSystemEventbus",
			Handler:    _EventbusController_CreateSystemEventbus_Handler,
		},
		{
			MethodName: "DeleteEventbus",
			Handler:    _EventbusController_DeleteEventbus_Handler,
		},
		{
			MethodName: "GetEventbus",
			Handler:    _EventbusController_GetEventbus_Handler,
		},
		{
			MethodName: "ListEventbus",
			Handler:    _EventbusController_ListEventbus_Handler,
		},
		{
			MethodName: "UpdateEventbus",
			Handler:    _EventbusController_UpdateEventbus_Handler,
		},
		{
			MethodName: "GetEventbusWithHumanFriendly",
			Handler:    _EventbusController_GetEventbusWithHumanFriendly_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vanus/core/controller/controller.proto",
}

const (
	EventlogController_ListSegment_FullMethodName          = "/vanus.core.controller.EventlogController/ListSegment"
	EventlogController_GetAppendableSegment_FullMethodName = "/vanus.core.controller.EventlogController/GetAppendableSegment"
)

// EventlogControllerClient is the client API for EventlogController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventlogControllerClient interface {
	ListSegment(ctx context.Context, in *ListSegmentRequest, opts ...grpc.CallOption) (*ListSegmentResponse, error)
	GetAppendableSegment(ctx context.Context, in *GetAppendableSegmentRequest, opts ...grpc.CallOption) (*GetAppendableSegmentResponse, error)
}

type eventlogControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewEventlogControllerClient(cc grpc.ClientConnInterface) EventlogControllerClient {
	_ = "STUB: not implemented"
	return *new(EventlogControllerClient)
}

func (c *eventlogControllerClient) ListSegment(ctx context.Context, in *ListSegmentRequest, opts ...grpc.CallOption) (*ListSegmentResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *eventlogControllerClient) GetAppendableSegment(ctx context.Context, in *GetAppendableSegmentRequest, opts ...grpc.CallOption) (*GetAppendableSegmentResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EventlogControllerServer is the server API for EventlogController service.
// All implementations should embed UnimplementedEventlogControllerServer
// for forward compatibility
type EventlogControllerServer interface {
	ListSegment(context.Context, *ListSegmentRequest) (*ListSegmentResponse, error)
	GetAppendableSegment(context.Context, *GetAppendableSegmentRequest) (*GetAppendableSegmentResponse, error)
}

// UnimplementedEventlogControllerServer should be embedded to have forward compatible implementations.
type UnimplementedEventlogControllerServer struct {
}

func (UnimplementedEventlogControllerServer) ListSegment(context.Context, *ListSegmentRequest) (*ListSegmentResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedEventlogControllerServer) GetAppendableSegment(context.Context, *GetAppendableSegmentRequest) (*GetAppendableSegmentResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnsafeEventlogControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventlogControllerServer will
// result in compilation errors.
type UnsafeEventlogControllerServer interface {
	mustEmbedUnimplementedEventlogControllerServer()
}

func RegisterEventlogControllerServer(s grpc.ServiceRegistrar, srv EventlogControllerServer) {
	_ = "STUB: not implemented"
	return
}

func _EventlogController_ListSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _EventlogController_GetAppendableSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// EventlogController_ServiceDesc is the grpc.ServiceDesc for EventlogController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventlogController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vanus.core.controller.EventlogController",
	HandlerType: (*EventlogControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSegment",
			Handler:    _EventlogController_ListSegment_Handler,
		},
		{
			MethodName: "GetAppendableSegment",
			Handler:    _EventlogController_GetAppendableSegment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vanus/core/controller/controller.proto",
}

const (
	SegmentController_QuerySegmentRouteInfo_FullMethodName    = "/vanus.core.controller.SegmentController/QuerySegmentRouteInfo"
	SegmentController_SegmentHeartbeat_FullMethodName         = "/vanus.core.controller.SegmentController/SegmentHeartbeat"
	SegmentController_RegisterSegmentServer_FullMethodName    = "/vanus.core.controller.SegmentController/RegisterSegmentServer"
	SegmentController_UnregisterSegmentServer_FullMethodName  = "/vanus.core.controller.SegmentController/UnregisterSegmentServer"
	SegmentController_ReportSegmentBlockIsFull_FullMethodName = "/vanus.core.controller.SegmentController/ReportSegmentBlockIsFull"
	SegmentController_ReportSegmentLeader_FullMethodName      = "/vanus.core.controller.SegmentController/ReportSegmentLeader"
)

// SegmentControllerClient is the client API for SegmentController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SegmentControllerClient interface {
	QuerySegmentRouteInfo(ctx context.Context, in *QuerySegmentRouteInfoRequest, opts ...grpc.CallOption) (*QuerySegmentRouteInfoResponse, error)
	SegmentHeartbeat(ctx context.Context, opts ...grpc.CallOption) (SegmentController_SegmentHeartbeatClient, error)
	RegisterSegmentServer(ctx context.Context, in *RegisterSegmentServerRequest, opts ...grpc.CallOption) (*RegisterSegmentServerResponse, error)
	UnregisterSegmentServer(ctx context.Context, in *UnregisterSegmentServerRequest, opts ...grpc.CallOption) (*UnregisterSegmentServerResponse, error)
	ReportSegmentBlockIsFull(ctx context.Context, in *SegmentHeartbeatRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ReportSegmentLeader(ctx context.Context, in *ReportSegmentLeaderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type segmentControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewSegmentControllerClient(cc grpc.ClientConnInterface) SegmentControllerClient {
	_ = "STUB: not implemented"
	return *new(SegmentControllerClient)
}

func (c *segmentControllerClient) QuerySegmentRouteInfo(ctx context.Context, in *QuerySegmentRouteInfoRequest, opts ...grpc.CallOption) (*QuerySegmentRouteInfoResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *segmentControllerClient) SegmentHeartbeat(ctx context.Context, opts ...grpc.CallOption) (SegmentController_SegmentHeartbeatClient, error) {
	_ = "STUB: not implemented"
	return *new(SegmentController_SegmentHeartbeatClient), nil
}

type SegmentController_SegmentHeartbeatClient interface {
	Send(*SegmentHeartbeatRequest) error
	CloseAndRecv() (*SegmentHeartbeatResponse, error)
	grpc.ClientStream
}

type segmentControllerSegmentHeartbeatClient struct {
	grpc.ClientStream
}

func (x *segmentControllerSegmentHeartbeatClient) Send(m *SegmentHeartbeatRequest) error {
	_ = "STUB: not implemented"
	return nil
}

func (x *segmentControllerSegmentHeartbeatClient) CloseAndRecv() (*SegmentHeartbeatResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *segmentControllerClient) RegisterSegmentServer(ctx context.Context, in *RegisterSegmentServerRequest, opts ...grpc.CallOption) (*RegisterSegmentServerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *segmentControllerClient) UnregisterSegmentServer(ctx context.Context, in *UnregisterSegmentServerRequest, opts ...grpc.CallOption) (*UnregisterSegmentServerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *segmentControllerClient) ReportSegmentBlockIsFull(ctx context.Context, in *SegmentHeartbeatRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *segmentControllerClient) ReportSegmentLeader(ctx context.Context, in *ReportSegmentLeaderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SegmentControllerServer is the server API for SegmentController service.
// All implementations should embed UnimplementedSegmentControllerServer
// for forward compatibility
type SegmentControllerServer interface {
	QuerySegmentRouteInfo(context.Context, *QuerySegmentRouteInfoRequest) (*QuerySegmentRouteInfoResponse, error)
	SegmentHeartbeat(SegmentController_SegmentHeartbeatServer) error
	RegisterSegmentServer(context.Context, *RegisterSegmentServerRequest) (*RegisterSegmentServerResponse, error)
	UnregisterSegmentServer(context.Context, *UnregisterSegmentServerRequest) (*UnregisterSegmentServerResponse, error)
	ReportSegmentBlockIsFull(context.Context, *SegmentHeartbeatRequest) (*emptypb.Empty, error)
	ReportSegmentLeader(context.Context, *ReportSegmentLeaderRequest) (*emptypb.Empty, error)
}

// UnimplementedSegmentControllerServer should be embedded to have forward compatible implementations.
type UnimplementedSegmentControllerServer struct {
}

func (UnimplementedSegmentControllerServer) QuerySegmentRouteInfo(context.Context, *QuerySegmentRouteInfoRequest) (*QuerySegmentRouteInfoResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSegmentControllerServer) SegmentHeartbeat(SegmentController_SegmentHeartbeatServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (UnimplementedSegmentControllerServer) RegisterSegmentServer(context.Context, *RegisterSegmentServerRequest) (*RegisterSegmentServerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSegmentControllerServer) UnregisterSegmentServer(context.Context, *UnregisterSegmentServerRequest) (*UnregisterSegmentServerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSegmentControllerServer) ReportSegmentBlockIsFull(context.Context, *SegmentHeartbeatRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSegmentControllerServer) ReportSegmentLeader(context.Context, *ReportSegmentLeaderRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnsafeSegmentControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SegmentControllerServer will
// result in compilation errors.
type UnsafeSegmentControllerServer interface {
	mustEmbedUnimplementedSegmentControllerServer()
}

func RegisterSegmentControllerServer(s grpc.ServiceRegistrar, srv SegmentControllerServer) {
	_ = "STUB: not implemented"
	return
}

func _SegmentController_QuerySegmentRouteInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _SegmentController_SegmentHeartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

type SegmentController_SegmentHeartbeatServer interface {
	SendAndClose(*SegmentHeartbeatResponse) error
	Recv() (*SegmentHeartbeatRequest, error)
	grpc.ServerStream
}

type segmentControllerSegmentHeartbeatServer struct {
	grpc.ServerStream
}

func (x *segmentControllerSegmentHeartbeatServer) SendAndClose(m *SegmentHeartbeatResponse) error {
	_ = "STUB: not implemented"
	return nil
}

func (x *segmentControllerSegmentHeartbeatServer) Recv() (*SegmentHeartbeatRequest, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _SegmentController_RegisterSegmentServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _SegmentController_UnregisterSegmentServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _SegmentController_ReportSegmentBlockIsFull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _SegmentController_ReportSegmentLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SegmentController_ServiceDesc is the grpc.ServiceDesc for SegmentController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SegmentController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vanus.core.controller.SegmentController",
	HandlerType: (*SegmentControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QuerySegmentRouteInfo",
			Handler:    _SegmentController_QuerySegmentRouteInfo_Handler,
		},
		{
			MethodName: "RegisterSegmentServer",
			Handler:    _SegmentController_RegisterSegmentServer_Handler,
		},
		{
			MethodName: "UnregisterSegmentServer",
			Handler:    _SegmentController_UnregisterSegmentServer_Handler,
		},
		{
			MethodName: "ReportSegmentBlockIsFull",
			Handler:    _SegmentController_ReportSegmentBlockIsFull_Handler,
		},
		{
			MethodName: "ReportSegmentLeader",
			Handler:    _SegmentController_ReportSegmentLeader_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SegmentHeartbeat",
			Handler:       _SegmentController_SegmentHeartbeat_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "vanus/core/controller/controller.proto",
}

const (
	TriggerController_CreateSubscription_FullMethodName       = "/vanus.core.controller.TriggerController/CreateSubscription"
	TriggerController_UpdateSubscription_FullMethodName       = "/vanus.core.controller.TriggerController/UpdateSubscription"
	TriggerController_DeleteSubscription_FullMethodName       = "/vanus.core.controller.TriggerController/DeleteSubscription"
	TriggerController_DisableSubscription_FullMethodName      = "/vanus.core.controller.TriggerController/DisableSubscription"
	TriggerController_ResumeSubscription_FullMethodName       = "/vanus.core.controller.TriggerController/ResumeSubscription"
	TriggerController_GetSubscription_FullMethodName          = "/vanus.core.controller.TriggerController/GetSubscription"
	TriggerController_ListSubscription_FullMethodName         = "/vanus.core.controller.TriggerController/ListSubscription"
	TriggerController_TriggerWorkerHeartbeat_FullMethodName   = "/vanus.core.controller.TriggerController/TriggerWorkerHeartbeat"
	TriggerController_RegisterTriggerWorker_FullMethodName    = "/vanus.core.controller.TriggerController/RegisterTriggerWorker"
	TriggerController_UnregisterTriggerWorker_FullMethodName  = "/vanus.core.controller.TriggerController/UnregisterTriggerWorker"
	TriggerController_ResetOffsetToTimestamp_FullMethodName   = "/vanus.core.controller.TriggerController/ResetOffsetToTimestamp"
	TriggerController_CommitOffset_FullMethodName             = "/vanus.core.controller.TriggerController/CommitOffset"
	TriggerController_SetDeadLetterEventOffset_FullMethodName = "/vanus.core.controller.TriggerController/SetDeadLetterEventOffset"
	TriggerController_GetDeadLetterEventOffset_FullMethodName = "/vanus.core.controller.TriggerController/GetDeadLetterEventOffset"
)

// TriggerControllerClient is the client API for TriggerController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TriggerControllerClient interface {
	CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*meta.Subscription, error)
	UpdateSubscription(ctx context.Context, in *UpdateSubscriptionRequest, opts ...grpc.CallOption) (*meta.Subscription, error)
	DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DisableSubscription(ctx context.Context, in *DisableSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ResumeSubscription(ctx context.Context, in *ResumeSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*meta.Subscription, error)
	ListSubscription(ctx context.Context, in *ListSubscriptionRequest, opts ...grpc.CallOption) (*ListSubscriptionResponse, error)
	TriggerWorkerHeartbeat(ctx context.Context, opts ...grpc.CallOption) (TriggerController_TriggerWorkerHeartbeatClient, error)
	RegisterTriggerWorker(ctx context.Context, in *RegisterTriggerWorkerRequest, opts ...grpc.CallOption) (*RegisterTriggerWorkerResponse, error)
	UnregisterTriggerWorker(ctx context.Context, in *UnregisterTriggerWorkerRequest, opts ...grpc.CallOption) (*UnregisterTriggerWorkerResponse, error)
	ResetOffsetToTimestamp(ctx context.Context, in *ResetOffsetToTimestampRequest, opts ...grpc.CallOption) (*ResetOffsetToTimestampResponse, error)
	CommitOffset(ctx context.Context, in *CommitOffsetRequest, opts ...grpc.CallOption) (*CommitOffsetResponse, error)
	SetDeadLetterEventOffset(ctx context.Context, in *SetDeadLetterEventOffsetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetDeadLetterEventOffset(ctx context.Context, in *GetDeadLetterEventOffsetRequest, opts ...grpc.CallOption) (*GetDeadLetterEventOffsetResponse, error)
}

type triggerControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewTriggerControllerClient(cc grpc.ClientConnInterface) TriggerControllerClient {
	_ = "STUB: not implemented"
	return *new(TriggerControllerClient)
}

func (c *triggerControllerClient) CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *triggerControllerClient) UpdateSubscription(ctx context.Context, in *UpdateSubscriptionRequest, opts ...grpc.CallOption) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *triggerControllerClient) DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *triggerControllerClient) DisableSubscription(ctx context.Context, in *DisableSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *triggerControllerClient) ResumeSubscription(ctx context.Context, in *ResumeSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *triggerControllerClient) GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *triggerControllerClient) ListSubscription(ctx context.Context, in *ListSubscriptionRequest, opts ...grpc.CallOption) (*ListSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *triggerControllerClient) TriggerWorkerHeartbeat(ctx context.Context, opts ...grpc.CallOption) (TriggerController_TriggerWorkerHeartbeatClient, error) {
	_ = "STUB: not implemented"
	return *new(TriggerController_TriggerWorkerHeartbeatClient), nil
}

type TriggerController_TriggerWorkerHeartbeatClient interface {
	Send(*TriggerWorkerHeartbeatRequest) error
	CloseAndRecv() (*TriggerWorkerHeartbeatResponse, error)
	grpc.ClientStream
}

type triggerControllerTriggerWorkerHeartbeatClient struct {
	grpc.ClientStream
}

func (x *triggerControllerTriggerWorkerHeartbeatClient) Send(m *TriggerWorkerHeartbeatRequest) error {
	_ = "STUB: not implemented"
	return nil
}

func (x *triggerControllerTriggerWorkerHeartbeatClient) CloseAndRecv() (*TriggerWorkerHeartbeatResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *triggerControllerClient) RegisterTriggerWorker(ctx context.Context, in *RegisterTriggerWorkerRequest, opts ...grpc.CallOption) (*RegisterTriggerWorkerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *triggerControllerClient) UnregisterTriggerWorker(ctx context.Context, in *UnregisterTriggerWorkerRequest, opts ...grpc.CallOption) (*UnregisterTriggerWorkerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *triggerControllerClient) ResetOffsetToTimestamp(ctx context.Context, in *ResetOffsetToTimestampRequest, opts ...grpc.CallOption) (*ResetOffsetToTimestampResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *triggerControllerClient) CommitOffset(ctx context.Context, in *CommitOffsetRequest, opts ...grpc.CallOption) (*CommitOffsetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *triggerControllerClient) SetDeadLetterEventOffset(ctx context.Context, in *SetDeadLetterEventOffsetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *triggerControllerClient) GetDeadLetterEventOffset(ctx context.Context, in *GetDeadLetterEventOffsetRequest, opts ...grpc.CallOption) (*GetDeadLetterEventOffsetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TriggerControllerServer is the server API for TriggerController service.
// All implementations should embed UnimplementedTriggerControllerServer
// for forward compatibility
type TriggerControllerServer interface {
	CreateSubscription(context.Context, *CreateSubscriptionRequest) (*meta.Subscription, error)
	UpdateSubscription(context.Context, *UpdateSubscriptionRequest) (*meta.Subscription, error)
	DeleteSubscription(context.Context, *DeleteSubscriptionRequest) (*emptypb.Empty, error)
	DisableSubscription(context.Context, *DisableSubscriptionRequest) (*emptypb.Empty, error)
	ResumeSubscription(context.Context, *ResumeSubscriptionRequest) (*emptypb.Empty, error)
	GetSubscription(context.Context, *GetSubscriptionRequest) (*meta.Subscription, error)
	ListSubscription(context.Context, *ListSubscriptionRequest) (*ListSubscriptionResponse, error)
	TriggerWorkerHeartbeat(TriggerController_TriggerWorkerHeartbeatServer) error
	RegisterTriggerWorker(context.Context, *RegisterTriggerWorkerRequest) (*RegisterTriggerWorkerResponse, error)
	UnregisterTriggerWorker(context.Context, *UnregisterTriggerWorkerRequest) (*UnregisterTriggerWorkerResponse, error)
	ResetOffsetToTimestamp(context.Context, *ResetOffsetToTimestampRequest) (*ResetOffsetToTimestampResponse, error)
	CommitOffset(context.Context, *CommitOffsetRequest) (*CommitOffsetResponse, error)
	SetDeadLetterEventOffset(context.Context, *SetDeadLetterEventOffsetRequest) (*emptypb.Empty, error)
	GetDeadLetterEventOffset(context.Context, *GetDeadLetterEventOffsetRequest) (*GetDeadLetterEventOffsetResponse, error)
}

// UnimplementedTriggerControllerServer should be embedded to have forward compatible implementations.
type UnimplementedTriggerControllerServer struct {
}

func (UnimplementedTriggerControllerServer) CreateSubscription(context.Context, *CreateSubscriptionRequest) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTriggerControllerServer) UpdateSubscription(context.Context, *UpdateSubscriptionRequest) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTriggerControllerServer) DeleteSubscription(context.Context, *DeleteSubscriptionRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTriggerControllerServer) DisableSubscription(context.Context, *DisableSubscriptionRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTriggerControllerServer) ResumeSubscription(context.Context, *ResumeSubscriptionRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTriggerControllerServer) GetSubscription(context.Context, *GetSubscriptionRequest) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTriggerControllerServer) ListSubscription(context.Context, *ListSubscriptionRequest) (*ListSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTriggerControllerServer) TriggerWorkerHeartbeat(TriggerController_TriggerWorkerHeartbeatServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (UnimplementedTriggerControllerServer) RegisterTriggerWorker(context.Context, *RegisterTriggerWorkerRequest) (*RegisterTriggerWorkerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTriggerControllerServer) UnregisterTriggerWorker(context.Context, *UnregisterTriggerWorkerRequest) (*UnregisterTriggerWorkerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTriggerControllerServer) ResetOffsetToTimestamp(context.Context, *ResetOffsetToTimestampRequest) (*ResetOffsetToTimestampResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTriggerControllerServer) CommitOffset(context.Context, *CommitOffsetRequest) (*CommitOffsetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTriggerControllerServer) SetDeadLetterEventOffset(context.Context, *SetDeadLetterEventOffsetRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTriggerControllerServer) GetDeadLetterEventOffset(context.Context, *GetDeadLetterEventOffsetRequest) (*GetDeadLetterEventOffsetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnsafeTriggerControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TriggerControllerServer will
// result in compilation errors.
type UnsafeTriggerControllerServer interface {
	mustEmbedUnimplementedTriggerControllerServer()
}

func RegisterTriggerControllerServer(s grpc.ServiceRegistrar, srv TriggerControllerServer) {
	_ = "STUB: not implemented"
	return
}

func _TriggerController_CreateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TriggerController_UpdateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TriggerController_DeleteSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TriggerController_DisableSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TriggerController_ResumeSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TriggerController_GetSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TriggerController_ListSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TriggerController_TriggerWorkerHeartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

type TriggerController_TriggerWorkerHeartbeatServer interface {
	SendAndClose(*TriggerWorkerHeartbeatResponse) error
	Recv() (*TriggerWorkerHeartbeatRequest, error)
	grpc.ServerStream
}

type triggerControllerTriggerWorkerHeartbeatServer struct {
	grpc.ServerStream
}

func (x *triggerControllerTriggerWorkerHeartbeatServer) SendAndClose(m *TriggerWorkerHeartbeatResponse) error {
	_ = "STUB: not implemented"
	return nil
}

func (x *triggerControllerTriggerWorkerHeartbeatServer) Recv() (*TriggerWorkerHeartbeatRequest, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TriggerController_RegisterTriggerWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TriggerController_UnregisterTriggerWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TriggerController_ResetOffsetToTimestamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TriggerController_CommitOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TriggerController_SetDeadLetterEventOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TriggerController_GetDeadLetterEventOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TriggerController_ServiceDesc is the grpc.ServiceDesc for TriggerController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TriggerController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vanus.core.controller.TriggerController",
	HandlerType: (*TriggerControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSubscription",
			Handler:    _TriggerController_CreateSubscription_Handler,
		},
		{
			MethodName: "UpdateSubscription",
			Handler:    _TriggerController_UpdateSubscription_Handler,
		},
		{
			MethodName: "DeleteSubscription",
			Handler:    _TriggerController_DeleteSubscription_Handler,
		},
		{
			MethodName: "DisableSubscription",
			Handler:    _TriggerController_DisableSubscription_Handler,
		},
		{
			MethodName: "ResumeSubscription",
			Handler:    _TriggerController_ResumeSubscription_Handler,
		},
		{
			MethodName: "GetSubscription",
			Handler:    _TriggerController_GetSubscription_Handler,
		},
		{
			MethodName: "ListSubscription",
			Handler:    _TriggerController_ListSubscription_Handler,
		},
		{
			MethodName: "RegisterTriggerWorker",
			Handler:    _TriggerController_RegisterTriggerWorker_Handler,
		},
		{
			MethodName: "UnregisterTriggerWorker",
			Handler:    _TriggerController_UnregisterTriggerWorker_Handler,
		},
		{
			MethodName: "ResetOffsetToTimestamp",
			Handler:    _TriggerController_ResetOffsetToTimestamp_Handler,
		},
		{
			MethodName: "CommitOffset",
			Handler:    _TriggerController_CommitOffset_Handler,
		},
		{
			MethodName: "SetDeadLetterEventOffset",
			Handler:    _TriggerController_SetDeadLetterEventOffset_Handler,
		},
		{
			MethodName: "GetDeadLetterEventOffset",
			Handler:    _TriggerController_GetDeadLetterEventOffset_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TriggerWorkerHeartbeat",
			Handler:       _TriggerController_TriggerWorkerHeartbeat_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "vanus/core/controller/controller.proto",
}

const (
	SnowflakeController_GetClusterStartTime_FullMethodName = "/vanus.core.controller.SnowflakeController/GetClusterStartTime"
	SnowflakeController_RegisterNode_FullMethodName        = "/vanus.core.controller.SnowflakeController/RegisterNode"
	SnowflakeController_UnregisterNode_FullMethodName      = "/vanus.core.controller.SnowflakeController/UnregisterNode"
)

// SnowflakeControllerClient is the client API for SnowflakeController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnowflakeControllerClient interface {
	GetClusterStartTime(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*timestamppb.Timestamp, error)
	RegisterNode(ctx context.Context, in *wrapperspb.UInt32Value, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UnregisterNode(ctx context.Context, in *wrapperspb.UInt32Value, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type snowflakeControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewSnowflakeControllerClient(cc grpc.ClientConnInterface) SnowflakeControllerClient {
	_ = "STUB: not implemented"
	return *new(SnowflakeControllerClient)
}

func (c *snowflakeControllerClient) GetClusterStartTime(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*timestamppb.Timestamp, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *snowflakeControllerClient) RegisterNode(ctx context.Context, in *wrapperspb.UInt32Value, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *snowflakeControllerClient) UnregisterNode(ctx context.Context, in *wrapperspb.UInt32Value, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SnowflakeControllerServer is the server API for SnowflakeController service.
// All implementations should embed UnimplementedSnowflakeControllerServer
// for forward compatibility
type SnowflakeControllerServer interface {
	GetClusterStartTime(context.Context, *emptypb.Empty) (*timestamppb.Timestamp, error)
	RegisterNode(context.Context, *wrapperspb.UInt32Value) (*emptypb.Empty, error)
	UnregisterNode(context.Context, *wrapperspb.UInt32Value) (*emptypb.Empty, error)
}

// UnimplementedSnowflakeControllerServer should be embedded to have forward compatible implementations.
type UnimplementedSnowflakeControllerServer struct {
}

func (UnimplementedSnowflakeControllerServer) GetClusterStartTime(context.Context, *emptypb.Empty) (*timestamppb.Timestamp, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSnowflakeControllerServer) RegisterNode(context.Context, *wrapperspb.UInt32Value) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedSnowflakeControllerServer) UnregisterNode(context.Context, *wrapperspb.UInt32Value) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnsafeSnowflakeControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnowflakeControllerServer will
// result in compilation errors.
type UnsafeSnowflakeControllerServer interface {
	mustEmbedUnimplementedSnowflakeControllerServer()
}

func RegisterSnowflakeControllerServer(s grpc.ServiceRegistrar, srv SnowflakeControllerServer) {
	_ = "STUB: not implemented"
	return
}

func _SnowflakeController_GetClusterStartTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _SnowflakeController_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _SnowflakeController_UnregisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SnowflakeController_ServiceDesc is the grpc.ServiceDesc for SnowflakeController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnowflakeController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vanus.core.controller.SnowflakeController",
	HandlerType: (*SnowflakeControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClusterStartTime",
			Handler:    _SnowflakeController_GetClusterStartTime_Handler,
		},
		{
			MethodName: "RegisterNode",
			Handler:    _SnowflakeController_RegisterNode_Handler,
		},
		{
			MethodName: "UnregisterNode",
			Handler:    _SnowflakeController_UnregisterNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vanus/core/controller/controller.proto",
}

const (
	AuthController_CreateUser_FullMethodName      = "/vanus.core.controller.AuthController/CreateUser"
	AuthController_DeleteUser_FullMethodName      = "/vanus.core.controller.AuthController/DeleteUser"
	AuthController_GetUser_FullMethodName         = "/vanus.core.controller.AuthController/GetUser"
	AuthController_ListUser_FullMethodName        = "/vanus.core.controller.AuthController/ListUser"
	AuthController_GetUserByToken_FullMethodName  = "/vanus.core.controller.AuthController/GetUserByToken"
	AuthController_CreateToken_FullMethodName     = "/vanus.core.controller.AuthController/CreateToken"
	AuthController_DeleteToken_FullMethodName     = "/vanus.core.controller.AuthController/DeleteToken"
	AuthController_GetToken_FullMethodName        = "/vanus.core.controller.AuthController/GetToken"
	AuthController_GetUserToken_FullMethodName    = "/vanus.core.controller.AuthController/GetUserToken"
	AuthController_ListToken_FullMethodName       = "/vanus.core.controller.AuthController/ListToken"
	AuthController_GrantRole_FullMethodName       = "/vanus.core.controller.AuthController/GrantRole"
	AuthController_RevokeRole_FullMethodName      = "/vanus.core.controller.AuthController/RevokeRole"
	AuthController_GetUserRole_FullMethodName     = "/vanus.core.controller.AuthController/GetUserRole"
	AuthController_GetResourceRole_FullMethodName = "/vanus.core.controller.AuthController/GetResourceRole"
)

// AuthControllerClient is the client API for AuthController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthControllerClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*meta.User, error)
	DeleteUser(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetUser(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*meta.User, error)
	ListUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListUserResponse, error)
	GetUserByToken(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*wrapperspb.StringValue, error)
	CreateToken(ctx context.Context, in *CreateTokenRequest, opts ...grpc.CallOption) (*meta.Token, error)
	DeleteToken(ctx context.Context, in *DeleteTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetToken(ctx context.Context, in *wrapperspb.UInt64Value, opts ...grpc.CallOption) (*meta.Token, error)
	GetUserToken(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*GetTokenResponse, error)
	ListToken(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTokenResponse, error)
	GrantRole(ctx context.Context, in *RoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RevokeRole(ctx context.Context, in *RoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetUserRole(ctx context.Context, in *GetUserRoleRequest, opts ...grpc.CallOption) (*GetUserRoleResponse, error)
	GetResourceRole(ctx context.Context, in *GetResourceRoleRequest, opts ...grpc.CallOption) (*GetResourceRoleResponse, error)
}

type authControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthControllerClient(cc grpc.ClientConnInterface) AuthControllerClient {
	_ = "STUB: not implemented"
	return *new(AuthControllerClient)
}

func (c *authControllerClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*meta.User, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *authControllerClient) DeleteUser(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *authControllerClient) GetUser(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*meta.User, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *authControllerClient) ListUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListUserResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *authControllerClient) GetUserByToken(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*wrapperspb.StringValue, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *authControllerClient) CreateToken(ctx context.Context, in *CreateTokenRequest, opts ...grpc.CallOption) (*meta.Token, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *authControllerClient) DeleteToken(ctx context.Context, in *DeleteTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *authControllerClient) GetToken(ctx context.Context, in *wrapperspb.UInt64Value, opts ...grpc.CallOption) (*meta.Token, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *authControllerClient) GetUserToken(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *authControllerClient) ListToken(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListTokenResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *authControllerClient) GrantRole(ctx context.Context, in *RoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *authControllerClient) RevokeRole(ctx context.Context, in *RoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *authControllerClient) GetUserRole(ctx context.Context, in *GetUserRoleRequest, opts ...grpc.CallOption) (*GetUserRoleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *authControllerClient) GetResourceRole(ctx context.Context, in *GetResourceRoleRequest, opts ...grpc.CallOption) (*GetResourceRoleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AuthControllerServer is the server API for AuthController service.
// All implementations should embed UnimplementedAuthControllerServer
// for forward compatibility
type AuthControllerServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*meta.User, error)
	DeleteUser(context.Context, *wrapperspb.StringValue) (*emptypb.Empty, error)
	GetUser(context.Context, *wrapperspb.StringValue) (*meta.User, error)
	ListUser(context.Context, *emptypb.Empty) (*ListUserResponse, error)
	GetUserByToken(context.Context, *wrapperspb.StringValue) (*wrapperspb.StringValue, error)
	CreateToken(context.Context, *CreateTokenRequest) (*meta.Token, error)
	DeleteToken(context.Context, *DeleteTokenRequest) (*emptypb.Empty, error)
	GetToken(context.Context, *wrapperspb.UInt64Value) (*meta.Token, error)
	GetUserToken(context.Context, *wrapperspb.StringValue) (*GetTokenResponse, error)
	ListToken(context.Context, *emptypb.Empty) (*ListTokenResponse, error)
	GrantRole(context.Context, *RoleRequest) (*emptypb.Empty, error)
	RevokeRole(context.Context, *RoleRequest) (*emptypb.Empty, error)
	GetUserRole(context.Context, *GetUserRoleRequest) (*GetUserRoleResponse, error)
	GetResourceRole(context.Context, *GetResourceRoleRequest) (*GetResourceRoleResponse, error)
}

// UnimplementedAuthControllerServer should be embedded to have forward compatible implementations.
type UnimplementedAuthControllerServer struct {
}

func (UnimplementedAuthControllerServer) CreateUser(context.Context, *CreateUserRequest) (*meta.User, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedAuthControllerServer) DeleteUser(context.Context, *wrapperspb.StringValue) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedAuthControllerServer) GetUser(context.Context, *wrapperspb.StringValue) (*meta.User, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedAuthControllerServer) ListUser(context.Context, *emptypb.Empty) (*ListUserResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedAuthControllerServer) GetUserByToken(context.Context, *wrapperspb.StringValue) (*wrapperspb.StringValue, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedAuthControllerServer) CreateToken(context.Context, *CreateTokenRequest) (*meta.Token, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedAuthControllerServer) DeleteToken(context.Context, *DeleteTokenRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedAuthControllerServer) GetToken(context.Context, *wrapperspb.UInt64Value) (*meta.Token, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedAuthControllerServer) GetUserToken(context.Context, *wrapperspb.StringValue) (*GetTokenResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedAuthControllerServer) ListToken(context.Context, *emptypb.Empty) (*ListTokenResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedAuthControllerServer) GrantRole(context.Context, *RoleRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedAuthControllerServer) RevokeRole(context.Context, *RoleRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedAuthControllerServer) GetUserRole(context.Context, *GetUserRoleRequest) (*GetUserRoleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedAuthControllerServer) GetResourceRole(context.Context, *GetResourceRoleRequest) (*GetResourceRoleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnsafeAuthControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthControllerServer will
// result in compilation errors.
type UnsafeAuthControllerServer interface {
	mustEmbedUnimplementedAuthControllerServer()
}

func RegisterAuthControllerServer(s grpc.ServiceRegistrar, srv AuthControllerServer) {
	_ = "STUB: not implemented"
	return
}

func _AuthController_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _AuthController_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _AuthController_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _AuthController_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _AuthController_GetUserByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _AuthController_CreateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _AuthController_DeleteToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _AuthController_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _AuthController_GetUserToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _AuthController_ListToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _AuthController_GrantRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _AuthController_RevokeRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _AuthController_GetUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _AuthController_GetResourceRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AuthController_ServiceDesc is the grpc.ServiceDesc for AuthController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vanus.core.controller.AuthController",
	HandlerType: (*AuthControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _AuthController_CreateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _AuthController_DeleteUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _AuthController_GetUser_Handler,
		},
		{
			MethodName: "ListUser",
			Handler:    _AuthController_ListUser_Handler,
		},
		{
			MethodName: "GetUserByToken",
			Handler:    _AuthController_GetUserByToken_Handler,
		},
		{
			MethodName: "CreateToken",
			Handler:    _AuthController_CreateToken_Handler,
		},
		{
			MethodName: "DeleteToken",
			Handler:    _AuthController_DeleteToken_Handler,
		},
		{
			MethodName: "GetToken",
			Handler:    _AuthController_GetToken_Handler,
		},
		{
			MethodName: "GetUserToken",
			Handler:    _AuthController_GetUserToken_Handler,
		},
		{
			MethodName: "ListToken",
			Handler:    _AuthController_ListToken_Handler,
		},
		{
			MethodName: "GrantRole",
			Handler:    _AuthController_GrantRole_Handler,
		},
		{
			MethodName: "RevokeRole",
			Handler:    _AuthController_RevokeRole_Handler,
		},
		{
			MethodName: "GetUserRole",
			Handler:    _AuthController_GetUserRole_Handler,
		},
		{
			MethodName: "GetResourceRole",
			Handler:    _AuthController_GetResourceRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vanus/core/controller/controller.proto",
}
