// Code generated by MockGen. DO NOT EDIT.
// Source: controller.go

// Package cluster is a generated GoMock package.
package cluster

import (
	context "context"
	time "time"

	controller "github.com/vanus-labs/vanus/api/controller"
	meta "github.com/vanus-labs/vanus/api/meta"
	gomock "go.uber.org/mock/gomock"
)

// MockCluster is a mock of Cluster interface.
type MockCluster struct {
	ctrl     *gomock.Controller
	recorder *MockClusterMockRecorder
}

// MockClusterMockRecorder is the mock recorder for MockCluster.
type MockClusterMockRecorder struct {
	mock *MockCluster
}

// NewMockCluster creates a new mock instance.
func NewMockCluster(ctrl *gomock.Controller) *MockCluster { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCluster) EXPECT() *MockClusterMockRecorder {
	_ = "STUB: not implemented"

	// AuthService mocks base method.
	return nil
}

func (m *MockCluster) AuthService() AuthService {
	_ = "STUB: not implemented"
	return *new(AuthService)
}

// AuthService indicates an expected call of AuthService.
func (mr *MockClusterMockRecorder) AuthService() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// EventbusService mocks base method.
func (m *MockCluster) EventbusService() EventbusService {
	_ = "STUB: not implemented"
	return *new(EventbusService)
}

// EventbusService indicates an expected call of EventbusService.
func (mr *MockClusterMockRecorder) EventbusService() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// EventlogService mocks base method.
func (m *MockCluster) EventlogService() EventlogService {
	_ = "STUB: not implemented"
	return *new(EventlogService)
}

// EventlogService indicates an expected call of EventlogService.
func (mr *MockClusterMockRecorder) EventlogService() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IDService mocks base method.
func (m *MockCluster) IDService() IDService { _ = "STUB: not implemented"; return *new(IDService) }

// IDService indicates an expected call of IDService.
func (mr *MockClusterMockRecorder) IDService() *gomock.Call { _ = "STUB: not implemented"; return nil }

// IsReady mocks base method.
func (m *MockCluster) IsReady(createEventbus bool) bool { _ = "STUB: not implemented"; return false }

// IsReady indicates an expected call of IsReady.
func (mr *MockClusterMockRecorder) IsReady(createEventbus interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// NamespaceService mocks base method.
func (m *MockCluster) NamespaceService() NamespaceService {
	_ = "STUB: not implemented"
	return *new(NamespaceService)
}

// NamespaceService indicates an expected call of NamespaceService.
func (mr *MockClusterMockRecorder) NamespaceService() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SegmentService mocks base method.
func (m *MockCluster) SegmentService() SegmentService {
	_ = "STUB: not implemented"
	return *new(SegmentService)
}

// SegmentService indicates an expected call of SegmentService.
func (mr *MockClusterMockRecorder) SegmentService() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Status mocks base method.
func (m *MockCluster) Status() Topology { _ = "STUB: not implemented"; return *new(Topology) }

// Status indicates an expected call of Status.
func (mr *MockClusterMockRecorder) Status() *gomock.Call { _ = "STUB: not implemented"; return nil }

// TriggerService mocks base method.
func (m *MockCluster) TriggerService() TriggerService {
	_ = "STUB: not implemented"
	return *new(TriggerService)
}

// TriggerService indicates an expected call of TriggerService.
func (mr *MockClusterMockRecorder) TriggerService() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// WaitForControllerReady mocks base method.
func (m *MockCluster) WaitForControllerReady(createEventbus bool) error {
	_ = "STUB: not implemented"
	return nil
}

// WaitForControllerReady indicates an expected call of WaitForControllerReady.
func (mr *MockClusterMockRecorder) WaitForControllerReady(createEventbus interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockNamespaceService is a mock of NamespaceService interface.
type MockNamespaceService struct {
	ctrl     *gomock.Controller
	recorder *MockNamespaceServiceMockRecorder
}

// MockNamespaceServiceMockRecorder is the mock recorder for MockNamespaceService.
type MockNamespaceServiceMockRecorder struct {
	mock *MockNamespaceService
}

// NewMockNamespaceService creates a new mock instance.
func NewMockNamespaceService(ctrl *gomock.Controller) *MockNamespaceService {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNamespaceService) EXPECT() *MockNamespaceServiceMockRecorder {
	_ = "STUB: not implemented"

	// GetDefaultNamespace mocks base method.
	return nil
}

func (m *MockNamespaceService) GetDefaultNamespace(ctx context.Context) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDefaultNamespace indicates an expected call of GetDefaultNamespace.
func (mr *MockNamespaceServiceMockRecorder) GetDefaultNamespace(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNamespace mocks base method.
func (m *MockNamespaceService) GetNamespace(ctx context.Context, id uint64) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockNamespaceServiceMockRecorder) GetNamespace(ctx, id interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNamespaceByName mocks base method.
func (m *MockNamespaceService) GetNamespaceByName(ctx context.Context, name string) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetNamespaceByName indicates an expected call of GetNamespaceByName.
func (mr *MockNamespaceServiceMockRecorder) GetNamespaceByName(ctx, name interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSystemNamespace mocks base method.
func (m *MockNamespaceService) GetSystemNamespace(ctx context.Context) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetSystemNamespace indicates an expected call of GetSystemNamespace.
func (mr *MockNamespaceServiceMockRecorder) GetSystemNamespace(ctx interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RawClient mocks base method.
func (m *MockNamespaceService) RawClient() controller.NamespaceControllerClient {
	_ = "STUB: not implemented"
	return *new(controller.NamespaceControllerClient)
}

// RawClient indicates an expected call of RawClient.
func (mr *MockNamespaceServiceMockRecorder) RawClient() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockEventbusService is a mock of EventbusService interface.
type MockEventbusService struct {
	ctrl     *gomock.Controller
	recorder *MockEventbusServiceMockRecorder
}

// MockEventbusServiceMockRecorder is the mock recorder for MockEventbusService.
type MockEventbusServiceMockRecorder struct {
	mock *MockEventbusService
}

// NewMockEventbusService creates a new mock instance.
func NewMockEventbusService(ctrl *gomock.Controller) *MockEventbusService {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventbusService) EXPECT() *MockEventbusServiceMockRecorder {
	_ = "STUB: not implemented"

	// CreateSystemEventbusIfNotExist mocks base method.
	return nil
}

func (m *MockEventbusService) CreateSystemEventbusIfNotExist(ctx context.Context, name, desc string) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateSystemEventbusIfNotExist indicates an expected call of CreateSystemEventbusIfNotExist.
func (mr *MockEventbusServiceMockRecorder) CreateSystemEventbusIfNotExist(ctx, name, desc interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Delete mocks base method.
func (m *MockEventbusService) Delete(ctx context.Context, id uint64) error {
	_ = "STUB: not implemented"
	return nil
}

// Delete indicates an expected call of Delete.
func (mr *MockEventbusServiceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEventbus mocks base method.
func (m *MockEventbusService) GetEventbus(ctx context.Context, id uint64) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEventbus indicates an expected call of GetEventbus.
func (mr *MockEventbusServiceMockRecorder) GetEventbus(ctx, id interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEventbusByName mocks base method.
func (m *MockEventbusService) GetEventbusByName(ctx context.Context, ns, name string) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEventbusByName indicates an expected call of GetEventbusByName.
func (mr *MockEventbusServiceMockRecorder) GetEventbusByName(ctx, ns, name interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSystemEventbusByName mocks base method.
func (m *MockEventbusService) GetSystemEventbusByName(ctx context.Context, name string) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetSystemEventbusByName indicates an expected call of GetSystemEventbusByName.
func (mr *MockEventbusServiceMockRecorder) GetSystemEventbusByName(ctx, name interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RawClient mocks base method.
func (m *MockEventbusService) RawClient() controller.EventbusControllerClient {
	_ = "STUB: not implemented"
	return *new(controller.EventbusControllerClient)
}

// RawClient indicates an expected call of RawClient.
func (mr *MockEventbusServiceMockRecorder) RawClient() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockEventlogService is a mock of EventlogService interface.
type MockEventlogService struct {
	ctrl     *gomock.Controller
	recorder *MockEventlogServiceMockRecorder
}

// MockEventlogServiceMockRecorder is the mock recorder for MockEventlogService.
type MockEventlogServiceMockRecorder struct {
	mock *MockEventlogService
}

// NewMockEventlogService creates a new mock instance.
func NewMockEventlogService(ctrl *gomock.Controller) *MockEventlogService {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventlogService) EXPECT() *MockEventlogServiceMockRecorder {
	_ = "STUB: not implemented"

	// RawClient mocks base method.
	return nil
}

func (m *MockEventlogService) RawClient() controller.EventlogControllerClient {
	_ = "STUB: not implemented"
	return *new(controller.EventlogControllerClient)
}

// RawClient indicates an expected call of RawClient.
func (mr *MockEventlogServiceMockRecorder) RawClient() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockTriggerService is a mock of TriggerService interface.
type MockTriggerService struct {
	ctrl     *gomock.Controller
	recorder *MockTriggerServiceMockRecorder
}

// MockTriggerServiceMockRecorder is the mock recorder for MockTriggerService.
type MockTriggerServiceMockRecorder struct {
	mock *MockTriggerService
}

// NewMockTriggerService creates a new mock instance.
func NewMockTriggerService(ctrl *gomock.Controller) *MockTriggerService {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTriggerService) EXPECT() *MockTriggerServiceMockRecorder {
	_ = "STUB: not implemented"

	// GetSubscription mocks base method.
	return nil
}

func (m *MockTriggerService) GetSubscription(ctx context.Context, id uint64) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetSubscription indicates an expected call of GetSubscription.
func (mr *MockTriggerServiceMockRecorder) GetSubscription(ctx, id interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RawClient mocks base method.
func (m *MockTriggerService) RawClient() controller.TriggerControllerClient {
	_ = "STUB: not implemented"
	return *new(controller.TriggerControllerClient)
}

// RawClient indicates an expected call of RawClient.
func (mr *MockTriggerServiceMockRecorder) RawClient() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterHeartbeat mocks base method.
func (m *MockTriggerService) RegisterHeartbeat(ctx context.Context, interval time.Duration, reqFunc func() interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RegisterHeartbeat indicates an expected call of RegisterHeartbeat.
func (mr *MockTriggerServiceMockRecorder) RegisterHeartbeat(ctx, interval, reqFunc interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockIDService is a mock of IDService interface.
type MockIDService struct {
	ctrl     *gomock.Controller
	recorder *MockIDServiceMockRecorder
}

// MockIDServiceMockRecorder is the mock recorder for MockIDService.
type MockIDServiceMockRecorder struct {
	mock *MockIDService
}

// NewMockIDService creates a new mock instance.
func NewMockIDService(ctrl *gomock.Controller) *MockIDService {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDService) EXPECT() *MockIDServiceMockRecorder {
	_ = "STUB: not implemented"

	// RawClient mocks base method.
	return nil
}

func (m *MockIDService) RawClient() controller.SnowflakeControllerClient {
	_ = "STUB: not implemented"
	return *new(controller.SnowflakeControllerClient)
}

// RawClient indicates an expected call of RawClient.
func (mr *MockIDServiceMockRecorder) RawClient() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockSegmentService is a mock of SegmentService interface.
type MockSegmentService struct {
	ctrl     *gomock.Controller
	recorder *MockSegmentServiceMockRecorder
}

// MockSegmentServiceMockRecorder is the mock recorder for MockSegmentService.
type MockSegmentServiceMockRecorder struct {
	mock *MockSegmentService
}

// NewMockSegmentService creates a new mock instance.
func NewMockSegmentService(ctrl *gomock.Controller) *MockSegmentService {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSegmentService) EXPECT() *MockSegmentServiceMockRecorder {
	_ = "STUB: not implemented"

	// RawClient mocks base method.
	return nil
}

func (m *MockSegmentService) RawClient() controller.SegmentControllerClient {
	_ = "STUB: not implemented"
	return *new(controller.SegmentControllerClient)
}

// RawClient indicates an expected call of RawClient.
func (mr *MockSegmentServiceMockRecorder) RawClient() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterHeartbeat mocks base method.
func (m *MockSegmentService) RegisterHeartbeat(ctx context.Context, interval time.Duration, reqFunc func() interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RegisterHeartbeat indicates an expected call of RegisterHeartbeat.
func (mr *MockSegmentServiceMockRecorder) RegisterHeartbeat(ctx, interval, reqFunc interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	_ = "STUB: not implemented"

	// GetUserByToken mocks base method.
	return nil
}

func (m *MockAuthService) GetUserByToken(ctx context.Context, token string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetUserByToken indicates an expected call of GetUserByToken.
func (mr *MockAuthServiceMockRecorder) GetUserByToken(ctx, token interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUserRole mocks base method.
func (m *MockAuthService) GetUserRole(ctx context.Context, user string) ([]*meta.UserRole, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockAuthServiceMockRecorder) GetUserRole(ctx, user interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RawClient mocks base method.
func (m *MockAuthService) RawClient() controller.AuthControllerClient {
	_ = "STUB: not implemented"
	return *new(controller.AuthControllerClient)
}

// RawClient indicates an expected call of RawClient.
func (mr *MockAuthServiceMockRecorder) RawClient() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
