// Code generated by MockGen. DO NOT EDIT.
// Source: eventlog.go
//
// Generated by this command:
//
//	mockgen -source=eventlog.go -destination=mock_eventlog.go -package=eventlog
//

// Package eventlog is a generated GoMock package.
package eventlog

import (
	context "context"

	vsr "github.com/vanus-labs/vanus/api/vsr"
	kv "github.com/vanus-labs/vanus/pkg/kv"
	metadata "github.com/vanus-labs/vanus/server/controller/eventbus/metadata"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	_ = "STUB: not implemented"

	// AcquireEventlog mocks base method.
	return nil
}

func (m *MockManager) AcquireEventlog(ctx context.Context, eventbusID vsr.ID, eventbusName string) (*metadata.Eventlog, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AcquireEventlog indicates an expected call of AcquireEventlog.
func (mr *MockManagerMockRecorder) AcquireEventlog(ctx, eventbusID, eventbusName any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteEventlog mocks base method.
func (m *MockManager) DeleteEventlog(ctx context.Context, id vsr.ID) {
	_ = "STUB: not implemented"
	return
}

// DeleteEventlog indicates an expected call of DeleteEventlog.
func (mr *MockManagerMockRecorder) DeleteEventlog(ctx, id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetAppendableSegment mocks base method.
func (m *MockManager) GetAppendableSegment(ctx context.Context, eli *metadata.Eventlog, num int) ([]Segment, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetAppendableSegment indicates an expected call of GetAppendableSegment.
func (mr *MockManagerMockRecorder) GetAppendableSegment(ctx, eli, num any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBlock mocks base method.
func (m *MockManager) GetBlock(id vsr.ID) *metadata.Block { _ = "STUB: not implemented"; return nil }

// GetBlock indicates an expected call of GetBlock.
func (mr *MockManagerMockRecorder) GetBlock(id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEventlog mocks base method.
func (m *MockManager) GetEventlog(ctx context.Context, id vsr.ID) *metadata.Eventlog {
	_ = "STUB: not implemented"
	return nil
}

// GetEventlog indicates an expected call of GetEventlog.
func (mr *MockManagerMockRecorder) GetEventlog(ctx, id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEventlogSegmentList mocks base method.
func (m *MockManager) GetEventlogSegmentList(elID vsr.ID) []Segment {
	_ = "STUB: not implemented"
	return nil
}

// GetEventlogSegmentList indicates an expected call of GetEventlogSegmentList.
func (mr *MockManagerMockRecorder) GetEventlogSegmentList(elID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSegmentByBlockID mocks base method.
func (m *MockManager) GetSegmentByBlockID(block *metadata.Block) (Segment, error) {
	_ = "STUB: not implemented"
	return *new(Segment), nil
}

// GetSegmentByBlockID indicates an expected call of GetSegmentByBlockID.
func (mr *MockManagerMockRecorder) GetSegmentByBlockID(block any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Run mocks base method.
func (m *MockManager) Run(ctx context.Context, kvClient kv.Client, startTask bool) error {
	_ = "STUB: not implemented"
	return nil
}

// Run indicates an expected call of Run.
func (mr *MockManagerMockRecorder) Run(ctx, kvClient, startTask any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Stop mocks base method.
func (m *MockManager) Stop() { _ = "STUB: not implemented"; return }

// Stop indicates an expected call of Stop.
func (mr *MockManagerMockRecorder) Stop() *gomock.Call { _ = "STUB: not implemented"; return nil }

// UpdateSegment mocks base method.
func (m_2 *MockManager) UpdateSegment(ctx context.Context, m map[string][]Segment) {
	_ = "STUB: not implemented"
	return
}

// UpdateSegment indicates an expected call of UpdateSegment.
func (mr *MockManagerMockRecorder) UpdateSegment(ctx, m any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateSegmentReplicas mocks base method.
func (m *MockManager) UpdateSegmentReplicas(ctx context.Context, segID vsr.ID, term uint64) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateSegmentReplicas indicates an expected call of UpdateSegmentReplicas.
func (mr *MockManagerMockRecorder) UpdateSegmentReplicas(ctx, segID, term any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
