// Code generated by MockGen. DO NOT EDIT.
// Source: member.go
//
// Generated by this command:
//
//	mockgen -source=member.go -destination=mock_member.go -package=member
//

// Package member is a generated GoMock package.
package member

import (
	context "context"

	gomock "go.uber.org/mock/gomock"
)

// MockMember is a mock of Member interface.
type MockMember struct {
	ctrl     *gomock.Controller
	recorder *MockMemberMockRecorder
}

// MockMemberMockRecorder is the mock recorder for MockMember.
type MockMemberMockRecorder struct {
	mock *MockMember
}

// NewMockMember creates a new mock instance.
func NewMockMember(ctrl *gomock.Controller) *MockMember { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMember) EXPECT() *MockMemberMockRecorder {
	_ = "STUB: not implemented"

	// GetLeaderAddr mocks base method.
	return nil
}

func (m *MockMember) GetLeaderAddr() string { _ = "STUB: not implemented"; return "" }

// GetLeaderAddr indicates an expected call of GetLeaderAddr.
func (mr *MockMemberMockRecorder) GetLeaderAddr() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetLeaderID mocks base method.
func (m *MockMember) GetLeaderID() string { _ = "STUB: not implemented"; return "" }

// GetLeaderID indicates an expected call of GetLeaderID.
func (mr *MockMemberMockRecorder) GetLeaderID() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Init mocks base method.
func (m *MockMember) Init(arg0 context.Context) error { _ = "STUB: not implemented"; return nil }

// Init indicates an expected call of Init.
func (mr *MockMemberMockRecorder) Init(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// IsLeader mocks base method.
func (m *MockMember) IsLeader() bool { _ = "STUB: not implemented"; return false }

// IsLeader indicates an expected call of IsLeader.
func (mr *MockMemberMockRecorder) IsLeader() *gomock.Call { _ = "STUB: not implemented"; return nil }

// IsReady mocks base method.
func (m *MockMember) IsReady() bool { _ = "STUB: not implemented"; return false }

// IsReady indicates an expected call of IsReady.
func (mr *MockMemberMockRecorder) IsReady() *gomock.Call { _ = "STUB: not implemented"; return nil }

// RegisterMembershipChangedProcessor mocks base method.
func (m *MockMember) RegisterMembershipChangedProcessor(arg0 MembershipEventProcessor) {
	_ = "STUB: not implemented"
	return
}

// RegisterMembershipChangedProcessor indicates an expected call of RegisterMembershipChangedProcessor.
func (mr *MockMemberMockRecorder) RegisterMembershipChangedProcessor(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResignIfLeader mocks base method.
func (m *MockMember) ResignIfLeader() { _ = "STUB: not implemented"; return }

// ResignIfLeader indicates an expected call of ResignIfLeader.
func (mr *MockMemberMockRecorder) ResignIfLeader() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Start mocks base method.
func (m *MockMember) Start(arg0 context.Context) error { _ = "STUB: not implemented"; return nil }

// Start indicates an expected call of Start.
func (mr *MockMemberMockRecorder) Start(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Stop mocks base method.
func (m *MockMember) Stop(arg0 context.Context) { _ = "STUB: not implemented"; return }

// Stop indicates an expected call of Stop.
func (mr *MockMemberMockRecorder) Stop(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
