// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mock_interface.go -package=client
//

// Package client is a generated GoMock package.
package client

import (
	context "context"

	v2 "github.com/cloudevents/sdk-go/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockSender is a mock of Sender interface.
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
}

// MockSenderMockRecorder is the mock recorder for MockSender.
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance.
func NewMockSender(ctrl *gomock.Controller) *MockSender { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	_ = "STUB: not implemented"

	// Send mocks base method.
	return nil
}

func (m *MockSender) Send(ctx context.Context, events ...*v2.Event) Result {
	_ = "STUB: not implemented"
	return *new(Result)
}

// Send indicates an expected call of Send.
func (mr *MockSenderMockRecorder) Send(ctx any, events ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockEventClient is a mock of EventClient interface.
type MockEventClient struct {
	ctrl     *gomock.Controller
	recorder *MockEventClientMockRecorder
}

// MockEventClientMockRecorder is the mock recorder for MockEventClient.
type MockEventClientMockRecorder struct {
	mock *MockEventClient
}

// NewMockEventClient creates a new mock instance.
func NewMockEventClient(ctrl *gomock.Controller) *MockEventClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventClient) EXPECT() *MockEventClientMockRecorder {
	_ = "STUB: not implemented"

	// Send mocks base method.
	return nil
}

func (m *MockEventClient) Send(ctx context.Context, events ...*v2.Event) Result {
	_ = "STUB: not implemented"
	return *new(Result)
}

// Send indicates an expected call of Send.
func (mr *MockEventClientMockRecorder) Send(ctx any, events ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
