// Copyright 2022 Linkall Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: vanus/core/proxy/proxy.proto

package proxy

import (
	context "context"

	controller "github.com/vanus-labs/vanus/api/controller"
	meta "github.com/vanus-labs/vanus/api/meta"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ControllerProxy_CreateEventbus_FullMethodName                = "/vanus.core.proxy.ControllerProxy/CreateEventbus"
	ControllerProxy_CreateSystemEventbus_FullMethodName          = "/vanus.core.proxy.ControllerProxy/CreateSystemEventbus"
	ControllerProxy_DeleteEventbus_FullMethodName                = "/vanus.core.proxy.ControllerProxy/DeleteEventbus"
	ControllerProxy_GetEventbus_FullMethodName                   = "/vanus.core.proxy.ControllerProxy/GetEventbus"
	ControllerProxy_ListEventbus_FullMethodName                  = "/vanus.core.proxy.ControllerProxy/ListEventbus"
	ControllerProxy_UpdateEventbus_FullMethodName                = "/vanus.core.proxy.ControllerProxy/UpdateEventbus"
	ControllerProxy_GetEventbusWithHumanFriendly_FullMethodName  = "/vanus.core.proxy.ControllerProxy/GetEventbusWithHumanFriendly"
	ControllerProxy_ListSegment_FullMethodName                   = "/vanus.core.proxy.ControllerProxy/ListSegment"
	ControllerProxy_ValidateEventbus_FullMethodName              = "/vanus.core.proxy.ControllerProxy/ValidateEventbus"
	ControllerProxy_CreateSubscription_FullMethodName            = "/vanus.core.proxy.ControllerProxy/CreateSubscription"
	ControllerProxy_UpdateSubscription_FullMethodName            = "/vanus.core.proxy.ControllerProxy/UpdateSubscription"
	ControllerProxy_DeleteSubscription_FullMethodName            = "/vanus.core.proxy.ControllerProxy/DeleteSubscription"
	ControllerProxy_GetSubscription_FullMethodName               = "/vanus.core.proxy.ControllerProxy/GetSubscription"
	ControllerProxy_ListSubscription_FullMethodName              = "/vanus.core.proxy.ControllerProxy/ListSubscription"
	ControllerProxy_DisableSubscription_FullMethodName           = "/vanus.core.proxy.ControllerProxy/DisableSubscription"
	ControllerProxy_ResumeSubscription_FullMethodName            = "/vanus.core.proxy.ControllerProxy/ResumeSubscription"
	ControllerProxy_ResetOffsetToTimestamp_FullMethodName        = "/vanus.core.proxy.ControllerProxy/ResetOffsetToTimestamp"
	ControllerProxy_ClusterInfo_FullMethodName                   = "/vanus.core.proxy.ControllerProxy/ClusterInfo"
	ControllerProxy_LookupOffset_FullMethodName                  = "/vanus.core.proxy.ControllerProxy/LookupOffset"
	ControllerProxy_GetEvent_FullMethodName                      = "/vanus.core.proxy.ControllerProxy/GetEvent"
	ControllerProxy_ValidateSubscription_FullMethodName          = "/vanus.core.proxy.ControllerProxy/ValidateSubscription"
	ControllerProxy_GetDeadLetterEvent_FullMethodName            = "/vanus.core.proxy.ControllerProxy/GetDeadLetterEvent"
	ControllerProxy_ResendDeadLetterEvent_FullMethodName         = "/vanus.core.proxy.ControllerProxy/ResendDeadLetterEvent"
	ControllerProxy_SetDeadLetterEventOffset_FullMethodName      = "/vanus.core.proxy.ControllerProxy/SetDeadLetterEventOffset"
	ControllerProxy_GetNamespaceWithHumanFriendly_FullMethodName = "/vanus.core.proxy.ControllerProxy/GetNamespaceWithHumanFriendly"
	ControllerProxy_CreateNamespace_FullMethodName               = "/vanus.core.proxy.ControllerProxy/CreateNamespace"
	ControllerProxy_ListNamespace_FullMethodName                 = "/vanus.core.proxy.ControllerProxy/ListNamespace"
	ControllerProxy_GetNamespace_FullMethodName                  = "/vanus.core.proxy.ControllerProxy/GetNamespace"
	ControllerProxy_DeleteNamespace_FullMethodName               = "/vanus.core.proxy.ControllerProxy/DeleteNamespace"
	ControllerProxy_CreateUser_FullMethodName                    = "/vanus.core.proxy.ControllerProxy/CreateUser"
	ControllerProxy_DeleteUser_FullMethodName                    = "/vanus.core.proxy.ControllerProxy/DeleteUser"
	ControllerProxy_GetUser_FullMethodName                       = "/vanus.core.proxy.ControllerProxy/GetUser"
	ControllerProxy_ListUser_FullMethodName                      = "/vanus.core.proxy.ControllerProxy/ListUser"
	ControllerProxy_CreateToken_FullMethodName                   = "/vanus.core.proxy.ControllerProxy/CreateToken"
	ControllerProxy_DeleteToken_FullMethodName                   = "/vanus.core.proxy.ControllerProxy/DeleteToken"
	ControllerProxy_GetUserToken_FullMethodName                  = "/vanus.core.proxy.ControllerProxy/GetUserToken"
	ControllerProxy_ListToken_FullMethodName                     = "/vanus.core.proxy.ControllerProxy/ListToken"
	ControllerProxy_GrantRole_FullMethodName                     = "/vanus.core.proxy.ControllerProxy/GrantRole"
	ControllerProxy_RevokeRole_FullMethodName                    = "/vanus.core.proxy.ControllerProxy/RevokeRole"
	ControllerProxy_GetUserRole_FullMethodName                   = "/vanus.core.proxy.ControllerProxy/GetUserRole"
	ControllerProxy_GetResourceRole_FullMethodName               = "/vanus.core.proxy.ControllerProxy/GetResourceRole"
)

// ControllerProxyClient is the client API for ControllerProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerProxyClient interface {
	// Eventbus
	CreateEventbus(ctx context.Context, in *controller.CreateEventbusRequest, opts ...grpc.CallOption) (*meta.Eventbus, error)
	CreateSystemEventbus(ctx context.Context, in *controller.CreateEventbusRequest, opts ...grpc.CallOption) (*meta.Eventbus, error)
	DeleteEventbus(ctx context.Context, in *wrapperspb.UInt64Value, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetEventbus(ctx context.Context, in *wrapperspb.UInt64Value, opts ...grpc.CallOption) (*meta.Eventbus, error)
	ListEventbus(ctx context.Context, in *controller.ListEventbusRequest, opts ...grpc.CallOption) (*controller.ListEventbusResponse, error)
	UpdateEventbus(ctx context.Context, in *controller.UpdateEventbusRequest, opts ...grpc.CallOption) (*meta.Eventbus, error)
	GetEventbusWithHumanFriendly(ctx context.Context, in *controller.GetEventbusWithHumanFriendlyRequest, opts ...grpc.CallOption) (*meta.Eventbus, error)
	ListSegment(ctx context.Context, in *controller.ListSegmentRequest, opts ...grpc.CallOption) (*controller.ListSegmentResponse, error)
	ValidateEventbus(ctx context.Context, in *ValidateEventbusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Trigger
	CreateSubscription(ctx context.Context, in *controller.CreateSubscriptionRequest, opts ...grpc.CallOption) (*meta.Subscription, error)
	UpdateSubscription(ctx context.Context, in *controller.UpdateSubscriptionRequest, opts ...grpc.CallOption) (*meta.Subscription, error)
	DeleteSubscription(ctx context.Context, in *controller.DeleteSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetSubscription(ctx context.Context, in *controller.GetSubscriptionRequest, opts ...grpc.CallOption) (*meta.Subscription, error)
	ListSubscription(ctx context.Context, in *controller.ListSubscriptionRequest, opts ...grpc.CallOption) (*controller.ListSubscriptionResponse, error)
	DisableSubscription(ctx context.Context, in *controller.DisableSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ResumeSubscription(ctx context.Context, in *controller.ResumeSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ResetOffsetToTimestamp(ctx context.Context, in *controller.ResetOffsetToTimestampRequest, opts ...grpc.CallOption) (*controller.ResetOffsetToTimestampResponse, error)
	// custom
	ClusterInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClusterInfoResponse, error)
	LookupOffset(ctx context.Context, in *LookupOffsetRequest, opts ...grpc.CallOption) (*LookupOffsetResponse, error)
	GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*GetEventResponse, error)
	ValidateSubscription(ctx context.Context, in *ValidateSubscriptionRequest, opts ...grpc.CallOption) (*ValidateSubscriptionResponse, error)
	// dead letter
	GetDeadLetterEvent(ctx context.Context, in *GetDeadLetterEventRequest, opts ...grpc.CallOption) (*GetDeadLetterEventResponse, error)
	ResendDeadLetterEvent(ctx context.Context, in *ResendDeadLetterEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetDeadLetterEventOffset(ctx context.Context, in *controller.SetDeadLetterEventOffsetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// multiple tenant
	GetNamespaceWithHumanFriendly(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*meta.Namespace, error)
	CreateNamespace(ctx context.Context, in *controller.CreateNamespaceRequest, opts ...grpc.CallOption) (*meta.Namespace, error)
	ListNamespace(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*controller.ListNamespaceResponse, error)
	GetNamespace(ctx context.Context, in *controller.GetNamespaceRequest, opts ...grpc.CallOption) (*meta.Namespace, error)
	DeleteNamespace(ctx context.Context, in *controller.DeleteNamespaceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateUser(ctx context.Context, in *controller.CreateUserRequest, opts ...grpc.CallOption) (*meta.User, error)
	DeleteUser(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetUser(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*meta.User, error)
	ListUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*controller.ListUserResponse, error)
	CreateToken(ctx context.Context, in *controller.CreateTokenRequest, opts ...grpc.CallOption) (*meta.Token, error)
	DeleteToken(ctx context.Context, in *controller.DeleteTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetUserToken(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*controller.GetTokenResponse, error)
	ListToken(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*controller.ListTokenResponse, error)
	GrantRole(ctx context.Context, in *controller.RoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RevokeRole(ctx context.Context, in *controller.RoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetUserRole(ctx context.Context, in *controller.GetUserRoleRequest, opts ...grpc.CallOption) (*controller.GetUserRoleResponse, error)
	GetResourceRole(ctx context.Context, in *controller.GetResourceRoleRequest, opts ...grpc.CallOption) (*controller.GetResourceRoleResponse, error)
}

type controllerProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerProxyClient(cc grpc.ClientConnInterface) ControllerProxyClient {
	_ = "STUB: not implemented"
	return *new(ControllerProxyClient)
}

func (c *controllerProxyClient) CreateEventbus(ctx context.Context, in *controller.CreateEventbusRequest, opts ...grpc.CallOption) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) CreateSystemEventbus(ctx context.Context, in *controller.CreateEventbusRequest, opts ...grpc.CallOption) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) DeleteEventbus(ctx context.Context, in *wrapperspb.UInt64Value, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) GetEventbus(ctx context.Context, in *wrapperspb.UInt64Value, opts ...grpc.CallOption) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) ListEventbus(ctx context.Context, in *controller.ListEventbusRequest, opts ...grpc.CallOption) (*controller.ListEventbusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) UpdateEventbus(ctx context.Context, in *controller.UpdateEventbusRequest, opts ...grpc.CallOption) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) GetEventbusWithHumanFriendly(ctx context.Context, in *controller.GetEventbusWithHumanFriendlyRequest, opts ...grpc.CallOption) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) ListSegment(ctx context.Context, in *controller.ListSegmentRequest, opts ...grpc.CallOption) (*controller.ListSegmentResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) ValidateEventbus(ctx context.Context, in *ValidateEventbusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) CreateSubscription(ctx context.Context, in *controller.CreateSubscriptionRequest, opts ...grpc.CallOption) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) UpdateSubscription(ctx context.Context, in *controller.UpdateSubscriptionRequest, opts ...grpc.CallOption) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) DeleteSubscription(ctx context.Context, in *controller.DeleteSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) GetSubscription(ctx context.Context, in *controller.GetSubscriptionRequest, opts ...grpc.CallOption) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) ListSubscription(ctx context.Context, in *controller.ListSubscriptionRequest, opts ...grpc.CallOption) (*controller.ListSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) DisableSubscription(ctx context.Context, in *controller.DisableSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) ResumeSubscription(ctx context.Context, in *controller.ResumeSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) ResetOffsetToTimestamp(ctx context.Context, in *controller.ResetOffsetToTimestampRequest, opts ...grpc.CallOption) (*controller.ResetOffsetToTimestampResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) ClusterInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClusterInfoResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) LookupOffset(ctx context.Context, in *LookupOffsetRequest, opts ...grpc.CallOption) (*LookupOffsetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*GetEventResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) ValidateSubscription(ctx context.Context, in *ValidateSubscriptionRequest, opts ...grpc.CallOption) (*ValidateSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) GetDeadLetterEvent(ctx context.Context, in *GetDeadLetterEventRequest, opts ...grpc.CallOption) (*GetDeadLetterEventResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) ResendDeadLetterEvent(ctx context.Context, in *ResendDeadLetterEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) SetDeadLetterEventOffset(ctx context.Context, in *controller.SetDeadLetterEventOffsetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) GetNamespaceWithHumanFriendly(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) CreateNamespace(ctx context.Context, in *controller.CreateNamespaceRequest, opts ...grpc.CallOption) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) ListNamespace(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*controller.ListNamespaceResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) GetNamespace(ctx context.Context, in *controller.GetNamespaceRequest, opts ...grpc.CallOption) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) DeleteNamespace(ctx context.Context, in *controller.DeleteNamespaceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) CreateUser(ctx context.Context, in *controller.CreateUserRequest, opts ...grpc.CallOption) (*meta.User, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) DeleteUser(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) GetUser(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*meta.User, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) ListUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*controller.ListUserResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) CreateToken(ctx context.Context, in *controller.CreateTokenRequest, opts ...grpc.CallOption) (*meta.Token, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) DeleteToken(ctx context.Context, in *controller.DeleteTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) GetUserToken(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*controller.GetTokenResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) ListToken(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*controller.ListTokenResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) GrantRole(ctx context.Context, in *controller.RoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) RevokeRole(ctx context.Context, in *controller.RoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) GetUserRole(ctx context.Context, in *controller.GetUserRoleRequest, opts ...grpc.CallOption) (*controller.GetUserRoleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *controllerProxyClient) GetResourceRole(ctx context.Context, in *controller.GetResourceRoleRequest, opts ...grpc.CallOption) (*controller.GetResourceRoleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ControllerProxyServer is the server API for ControllerProxy service.
// All implementations should embed UnimplementedControllerProxyServer
// for forward compatibility
type ControllerProxyServer interface {
	// Eventbus
	CreateEventbus(context.Context, *controller.CreateEventbusRequest) (*meta.Eventbus, error)
	CreateSystemEventbus(context.Context, *controller.CreateEventbusRequest) (*meta.Eventbus, error)
	DeleteEventbus(context.Context, *wrapperspb.UInt64Value) (*emptypb.Empty, error)
	GetEventbus(context.Context, *wrapperspb.UInt64Value) (*meta.Eventbus, error)
	ListEventbus(context.Context, *controller.ListEventbusRequest) (*controller.ListEventbusResponse, error)
	UpdateEventbus(context.Context, *controller.UpdateEventbusRequest) (*meta.Eventbus, error)
	GetEventbusWithHumanFriendly(context.Context, *controller.GetEventbusWithHumanFriendlyRequest) (*meta.Eventbus, error)
	ListSegment(context.Context, *controller.ListSegmentRequest) (*controller.ListSegmentResponse, error)
	ValidateEventbus(context.Context, *ValidateEventbusRequest) (*emptypb.Empty, error)
	// Trigger
	CreateSubscription(context.Context, *controller.CreateSubscriptionRequest) (*meta.Subscription, error)
	UpdateSubscription(context.Context, *controller.UpdateSubscriptionRequest) (*meta.Subscription, error)
	DeleteSubscription(context.Context, *controller.DeleteSubscriptionRequest) (*emptypb.Empty, error)
	GetSubscription(context.Context, *controller.GetSubscriptionRequest) (*meta.Subscription, error)
	ListSubscription(context.Context, *controller.ListSubscriptionRequest) (*controller.ListSubscriptionResponse, error)
	DisableSubscription(context.Context, *controller.DisableSubscriptionRequest) (*emptypb.Empty, error)
	ResumeSubscription(context.Context, *controller.ResumeSubscriptionRequest) (*emptypb.Empty, error)
	ResetOffsetToTimestamp(context.Context, *controller.ResetOffsetToTimestampRequest) (*controller.ResetOffsetToTimestampResponse, error)
	// custom
	ClusterInfo(context.Context, *emptypb.Empty) (*ClusterInfoResponse, error)
	LookupOffset(context.Context, *LookupOffsetRequest) (*LookupOffsetResponse, error)
	GetEvent(context.Context, *GetEventRequest) (*GetEventResponse, error)
	ValidateSubscription(context.Context, *ValidateSubscriptionRequest) (*ValidateSubscriptionResponse, error)
	// dead letter
	GetDeadLetterEvent(context.Context, *GetDeadLetterEventRequest) (*GetDeadLetterEventResponse, error)
	ResendDeadLetterEvent(context.Context, *ResendDeadLetterEventRequest) (*emptypb.Empty, error)
	SetDeadLetterEventOffset(context.Context, *controller.SetDeadLetterEventOffsetRequest) (*emptypb.Empty, error)
	// multiple tenant
	GetNamespaceWithHumanFriendly(context.Context, *wrapperspb.StringValue) (*meta.Namespace, error)
	CreateNamespace(context.Context, *controller.CreateNamespaceRequest) (*meta.Namespace, error)
	ListNamespace(context.Context, *emptypb.Empty) (*controller.ListNamespaceResponse, error)
	GetNamespace(context.Context, *controller.GetNamespaceRequest) (*meta.Namespace, error)
	DeleteNamespace(context.Context, *controller.DeleteNamespaceRequest) (*emptypb.Empty, error)
	CreateUser(context.Context, *controller.CreateUserRequest) (*meta.User, error)
	DeleteUser(context.Context, *wrapperspb.StringValue) (*emptypb.Empty, error)
	GetUser(context.Context, *wrapperspb.StringValue) (*meta.User, error)
	ListUser(context.Context, *emptypb.Empty) (*controller.ListUserResponse, error)
	CreateToken(context.Context, *controller.CreateTokenRequest) (*meta.Token, error)
	DeleteToken(context.Context, *controller.DeleteTokenRequest) (*emptypb.Empty, error)
	GetUserToken(context.Context, *wrapperspb.StringValue) (*controller.GetTokenResponse, error)
	ListToken(context.Context, *emptypb.Empty) (*controller.ListTokenResponse, error)
	GrantRole(context.Context, *controller.RoleRequest) (*emptypb.Empty, error)
	RevokeRole(context.Context, *controller.RoleRequest) (*emptypb.Empty, error)
	GetUserRole(context.Context, *controller.GetUserRoleRequest) (*controller.GetUserRoleResponse, error)
	GetResourceRole(context.Context, *controller.GetResourceRoleRequest) (*controller.GetResourceRoleResponse, error)
}

// UnimplementedControllerProxyServer should be embedded to have forward compatible implementations.
type UnimplementedControllerProxyServer struct {
}

func (UnimplementedControllerProxyServer) CreateEventbus(context.Context, *controller.CreateEventbusRequest) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) CreateSystemEventbus(context.Context, *controller.CreateEventbusRequest) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) DeleteEventbus(context.Context, *wrapperspb.UInt64Value) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) GetEventbus(context.Context, *wrapperspb.UInt64Value) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) ListEventbus(context.Context, *controller.ListEventbusRequest) (*controller.ListEventbusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) UpdateEventbus(context.Context, *controller.UpdateEventbusRequest) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) GetEventbusWithHumanFriendly(context.Context, *controller.GetEventbusWithHumanFriendlyRequest) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) ListSegment(context.Context, *controller.ListSegmentRequest) (*controller.ListSegmentResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) ValidateEventbus(context.Context, *ValidateEventbusRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) CreateSubscription(context.Context, *controller.CreateSubscriptionRequest) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) UpdateSubscription(context.Context, *controller.UpdateSubscriptionRequest) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) DeleteSubscription(context.Context, *controller.DeleteSubscriptionRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) GetSubscription(context.Context, *controller.GetSubscriptionRequest) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) ListSubscription(context.Context, *controller.ListSubscriptionRequest) (*controller.ListSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) DisableSubscription(context.Context, *controller.DisableSubscriptionRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) ResumeSubscription(context.Context, *controller.ResumeSubscriptionRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) ResetOffsetToTimestamp(context.Context, *controller.ResetOffsetToTimestampRequest) (*controller.ResetOffsetToTimestampResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) ClusterInfo(context.Context, *emptypb.Empty) (*ClusterInfoResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) LookupOffset(context.Context, *LookupOffsetRequest) (*LookupOffsetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) GetEvent(context.Context, *GetEventRequest) (*GetEventResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) ValidateSubscription(context.Context, *ValidateSubscriptionRequest) (*ValidateSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) GetDeadLetterEvent(context.Context, *GetDeadLetterEventRequest) (*GetDeadLetterEventResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) ResendDeadLetterEvent(context.Context, *ResendDeadLetterEventRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) SetDeadLetterEventOffset(context.Context, *controller.SetDeadLetterEventOffsetRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) GetNamespaceWithHumanFriendly(context.Context, *wrapperspb.StringValue) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) CreateNamespace(context.Context, *controller.CreateNamespaceRequest) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) ListNamespace(context.Context, *emptypb.Empty) (*controller.ListNamespaceResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) GetNamespace(context.Context, *controller.GetNamespaceRequest) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) DeleteNamespace(context.Context, *controller.DeleteNamespaceRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) CreateUser(context.Context, *controller.CreateUserRequest) (*meta.User, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) DeleteUser(context.Context, *wrapperspb.StringValue) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) GetUser(context.Context, *wrapperspb.StringValue) (*meta.User, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) ListUser(context.Context, *emptypb.Empty) (*controller.ListUserResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) CreateToken(context.Context, *controller.CreateTokenRequest) (*meta.Token, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) DeleteToken(context.Context, *controller.DeleteTokenRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) GetUserToken(context.Context, *wrapperspb.StringValue) (*controller.GetTokenResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) ListToken(context.Context, *emptypb.Empty) (*controller.ListTokenResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) GrantRole(context.Context, *controller.RoleRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) RevokeRole(context.Context, *controller.RoleRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) GetUserRole(context.Context, *controller.GetUserRoleRequest) (*controller.GetUserRoleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedControllerProxyServer) GetResourceRole(context.Context, *controller.GetResourceRoleRequest) (*controller.GetResourceRoleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnsafeControllerProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerProxyServer will
// result in compilation errors.
type UnsafeControllerProxyServer interface {
	mustEmbedUnimplementedControllerProxyServer()
}

func RegisterControllerProxyServer(s grpc.ServiceRegistrar, srv ControllerProxyServer) {
	_ = "STUB: not implemented"
	return
}

func _ControllerProxy_CreateEventbus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_CreateSystemEventbus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_DeleteEventbus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_GetEventbus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_ListEventbus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_UpdateEventbus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_GetEventbusWithHumanFriendly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_ListSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_ValidateEventbus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_CreateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_UpdateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_DeleteSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_GetSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_ListSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_DisableSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_ResumeSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_ResetOffsetToTimestamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_ClusterInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_LookupOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_ValidateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_GetDeadLetterEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_ResendDeadLetterEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_SetDeadLetterEventOffset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_GetNamespaceWithHumanFriendly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_CreateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_ListNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_GetNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_DeleteNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_CreateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_DeleteToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_GetUserToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_ListToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_GrantRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_RevokeRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_GetUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ControllerProxy_GetResourceRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ControllerProxy_ServiceDesc is the grpc.ServiceDesc for ControllerProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControllerProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vanus.core.proxy.ControllerProxy",
	HandlerType: (*ControllerProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEventbus",
			Handler:    _ControllerProxy_CreateEventbus_Handler,
		},
		{
			MethodName: "CreateSystemEventbus",
			Handler:    _ControllerProxy_CreateSystemEventbus_Handler,
		},
		{
			MethodName: "DeleteEventbus",
			Handler:    _ControllerProxy_DeleteEventbus_Handler,
		},
		{
			MethodName: "GetEventbus",
			Handler:    _ControllerProxy_GetEventbus_Handler,
		},
		{
			MethodName: "ListEventbus",
			Handler:    _ControllerProxy_ListEventbus_Handler,
		},
		{
			MethodName: "UpdateEventbus",
			Handler:    _ControllerProxy_UpdateEventbus_Handler,
		},
		{
			MethodName: "GetEventbusWithHumanFriendly",
			Handler:    _ControllerProxy_GetEventbusWithHumanFriendly_Handler,
		},
		{
			MethodName: "ListSegment",
			Handler:    _ControllerProxy_ListSegment_Handler,
		},
		{
			MethodName: "ValidateEventbus",
			Handler:    _ControllerProxy_ValidateEventbus_Handler,
		},
		{
			MethodName: "CreateSubscription",
			Handler:    _ControllerProxy_CreateSubscription_Handler,
		},
		{
			MethodName: "UpdateSubscription",
			Handler:    _ControllerProxy_UpdateSubscription_Handler,
		},
		{
			MethodName: "DeleteSubscription",
			Handler:    _ControllerProxy_DeleteSubscription_Handler,
		},
		{
			MethodName: "GetSubscription",
			Handler:    _ControllerProxy_GetSubscription_Handler,
		},
		{
			MethodName: "ListSubscription",
			Handler:    _ControllerProxy_ListSubscription_Handler,
		},
		{
			MethodName: "DisableSubscription",
			Handler:    _ControllerProxy_DisableSubscription_Handler,
		},
		{
			MethodName: "ResumeSubscription",
			Handler:    _ControllerProxy_ResumeSubscription_Handler,
		},
		{
			MethodName: "ResetOffsetToTimestamp",
			Handler:    _ControllerProxy_ResetOffsetToTimestamp_Handler,
		},
		{
			MethodName: "ClusterInfo",
			Handler:    _ControllerProxy_ClusterInfo_Handler,
		},
		{
			MethodName: "LookupOffset",
			Handler:    _ControllerProxy_LookupOffset_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _ControllerProxy_GetEvent_Handler,
		},
		{
			MethodName: "ValidateSubscription",
			Handler:    _ControllerProxy_ValidateSubscription_Handler,
		},
		{
			MethodName: "GetDeadLetterEvent",
			Handler:    _ControllerProxy_GetDeadLetterEvent_Handler,
		},
		{
			MethodName: "ResendDeadLetterEvent",
			Handler:    _ControllerProxy_ResendDeadLetterEvent_Handler,
		},
		{
			MethodName: "SetDeadLetterEventOffset",
			Handler:    _ControllerProxy_SetDeadLetterEventOffset_Handler,
		},
		{
			MethodName: "GetNamespaceWithHumanFriendly",
			Handler:    _ControllerProxy_GetNamespaceWithHumanFriendly_Handler,
		},
		{
			MethodName: "CreateNamespace",
			Handler:    _ControllerProxy_CreateNamespace_Handler,
		},
		{
			MethodName: "ListNamespace",
			Handler:    _ControllerProxy_ListNamespace_Handler,
		},
		{
			MethodName: "GetNamespace",
			Handler:    _ControllerProxy_GetNamespace_Handler,
		},
		{
			MethodName: "DeleteNamespace",
			Handler:    _ControllerProxy_DeleteNamespace_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _ControllerProxy_CreateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _ControllerProxy_DeleteUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _ControllerProxy_GetUser_Handler,
		},
		{
			MethodName: "ListUser",
			Handler:    _ControllerProxy_ListUser_Handler,
		},
		{
			MethodName: "CreateToken",
			Handler:    _ControllerProxy_CreateToken_Handler,
		},
		{
			MethodName: "DeleteToken",
			Handler:    _ControllerProxy_DeleteToken_Handler,
		},
		{
			MethodName: "GetUserToken",
			Handler:    _ControllerProxy_GetUserToken_Handler,
		},
		{
			MethodName: "ListToken",
			Handler:    _ControllerProxy_ListToken_Handler,
		},
		{
			MethodName: "GrantRole",
			Handler:    _ControllerProxy_GrantRole_Handler,
		},
		{
			MethodName: "RevokeRole",
			Handler:    _ControllerProxy_RevokeRole_Handler,
		},
		{
			MethodName: "GetUserRole",
			Handler:    _ControllerProxy_GetUserRole_Handler,
		},
		{
			MethodName: "GetResourceRole",
			Handler:    _ControllerProxy_GetResourceRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vanus/core/proxy/proxy.proto",
}

const (
	StoreProxy_Publish_FullMethodName   = "/vanus.core.proxy.StoreProxy/Publish"
	StoreProxy_Subscribe_FullMethodName = "/vanus.core.proxy.StoreProxy/Subscribe"
	StoreProxy_Ack_FullMethodName       = "/vanus.core.proxy.StoreProxy/Ack"
)

// StoreProxyClient is the client API for StoreProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoreProxyClient interface {
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (StoreProxy_SubscribeClient, error)
	Ack(ctx context.Context, opts ...grpc.CallOption) (StoreProxy_AckClient, error)
}

type storeProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreProxyClient(cc grpc.ClientConnInterface) StoreProxyClient {
	_ = "STUB: not implemented"
	return *new(StoreProxyClient)
}

func (c *storeProxyClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *storeProxyClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (StoreProxy_SubscribeClient, error) {
	_ = "STUB: not implemented"
	return *new(StoreProxy_SubscribeClient), nil
}

type StoreProxy_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type storeProxySubscribeClient struct {
	grpc.ClientStream
}

func (x *storeProxySubscribeClient) Recv() (*SubscribeResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *storeProxyClient) Ack(ctx context.Context, opts ...grpc.CallOption) (StoreProxy_AckClient, error) {
	_ = "STUB: not implemented"
	return *new(StoreProxy_AckClient), nil
}

type StoreProxy_AckClient interface {
	Send(*AckRequest) error
	CloseAndRecv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type storeProxyAckClient struct {
	grpc.ClientStream
}

func (x *storeProxyAckClient) Send(m *AckRequest) error { _ = "STUB: not implemented"; return nil }

func (x *storeProxyAckClient) CloseAndRecv() (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// StoreProxyServer is the server API for StoreProxy service.
// All implementations should embed UnimplementedStoreProxyServer
// for forward compatibility
type StoreProxyServer interface {
	Publish(context.Context, *PublishRequest) (*emptypb.Empty, error)
	Subscribe(*SubscribeRequest, StoreProxy_SubscribeServer) error
	Ack(StoreProxy_AckServer) error
}

// UnimplementedStoreProxyServer should be embedded to have forward compatible implementations.
type UnimplementedStoreProxyServer struct {
}

func (UnimplementedStoreProxyServer) Publish(context.Context, *PublishRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedStoreProxyServer) Subscribe(*SubscribeRequest, StoreProxy_SubscribeServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (UnimplementedStoreProxyServer) Ack(StoreProxy_AckServer) error {
	_ = "STUB: not implemented"
	return nil
}

// UnsafeStoreProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreProxyServer will
// result in compilation errors.
type UnsafeStoreProxyServer interface {
	mustEmbedUnimplementedStoreProxyServer()
}

func RegisterStoreProxyServer(s grpc.ServiceRegistrar, srv StoreProxyServer) {
	_ = "STUB: not implemented"
	return
}

func _StoreProxy_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _StoreProxy_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

type StoreProxy_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type storeProxySubscribeServer struct {
	grpc.ServerStream
}

func (x *storeProxySubscribeServer) Send(m *SubscribeResponse) error {
	_ = "STUB: not implemented"
	return nil
}

func _StoreProxy_Ack_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

type StoreProxy_AckServer interface {
	SendAndClose(*emptypb.Empty) error
	Recv() (*AckRequest, error)
	grpc.ServerStream
}

type storeProxyAckServer struct {
	grpc.ServerStream
}

func (x *storeProxyAckServer) SendAndClose(m *emptypb.Empty) error {
	_ = "STUB: not implemented"
	return nil
}

func (x *storeProxyAckServer) Recv() (*AckRequest, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// StoreProxy_ServiceDesc is the grpc.ServiceDesc for StoreProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoreProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vanus.core.proxy.StoreProxy",
	HandlerType: (*StoreProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _StoreProxy_Publish_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _StoreProxy_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Ack",
			Handler:       _StoreProxy_Ack_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "vanus/core/proxy/proxy.proto",
}
