// Code generated by protoc-gen-go-grpc-mock. DO NOT EDIT.
// source: vanus/core/proxy/proxy.proto

package proxy

import (
	context "context"

	controller "github.com/vanus-labs/vanus/api/controller"
	meta "github.com/vanus-labs/vanus/api/meta"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// MockControllerProxyClient is a mock of ControllerProxyClient interface.
type MockControllerProxyClient struct {
	ctrl     *gomock.Controller
	recorder *MockControllerProxyClientMockRecorder
}

// MockControllerProxyClientMockRecorder is the mock recorder for MockControllerProxyClient.
type MockControllerProxyClientMockRecorder struct {
	mock *MockControllerProxyClient
}

// NewMockControllerProxyClient creates a new mock instance.
func NewMockControllerProxyClient(ctrl *gomock.Controller) *MockControllerProxyClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControllerProxyClient) EXPECT() *MockControllerProxyClientMockRecorder {
	_ = "STUB: not implemented"

	// ClusterInfo mocks base method.
	return nil
}

func (m *MockControllerProxyClient) ClusterInfo(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClusterInfoResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ClusterInfo indicates an expected call of ClusterInfo.
func (mr *MockControllerProxyClientMockRecorder) ClusterInfo(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateEventbus mocks base method.
func (m *MockControllerProxyClient) CreateEventbus(ctx context.Context, in *controller.CreateEventbusRequest, opts ...grpc.CallOption) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateEventbus indicates an expected call of CreateEventbus.
func (mr *MockControllerProxyClientMockRecorder) CreateEventbus(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateNamespace mocks base method.
func (m *MockControllerProxyClient) CreateNamespace(ctx context.Context, in *controller.CreateNamespaceRequest, opts ...grpc.CallOption) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateNamespace indicates an expected call of CreateNamespace.
func (mr *MockControllerProxyClientMockRecorder) CreateNamespace(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateSubscription mocks base method.
func (m *MockControllerProxyClient) CreateSubscription(ctx context.Context, in *controller.CreateSubscriptionRequest, opts ...grpc.CallOption) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockControllerProxyClientMockRecorder) CreateSubscription(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateSystemEventbus mocks base method.
func (m *MockControllerProxyClient) CreateSystemEventbus(ctx context.Context, in *controller.CreateEventbusRequest, opts ...grpc.CallOption) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateSystemEventbus indicates an expected call of CreateSystemEventbus.
func (mr *MockControllerProxyClientMockRecorder) CreateSystemEventbus(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateToken mocks base method.
func (m *MockControllerProxyClient) CreateToken(ctx context.Context, in *controller.CreateTokenRequest, opts ...grpc.CallOption) (*meta.Token, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockControllerProxyClientMockRecorder) CreateToken(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateUser mocks base method.
func (m *MockControllerProxyClient) CreateUser(ctx context.Context, in *controller.CreateUserRequest, opts ...grpc.CallOption) (*meta.User, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockControllerProxyClientMockRecorder) CreateUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteEventbus mocks base method.
func (m *MockControllerProxyClient) DeleteEventbus(ctx context.Context, in *wrapperspb.UInt64Value, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteEventbus indicates an expected call of DeleteEventbus.
func (mr *MockControllerProxyClientMockRecorder) DeleteEventbus(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteNamespace mocks base method.
func (m *MockControllerProxyClient) DeleteNamespace(ctx context.Context, in *controller.DeleteNamespaceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteNamespace indicates an expected call of DeleteNamespace.
func (mr *MockControllerProxyClientMockRecorder) DeleteNamespace(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteSubscription mocks base method.
func (m *MockControllerProxyClient) DeleteSubscription(ctx context.Context, in *controller.DeleteSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteSubscription indicates an expected call of DeleteSubscription.
func (mr *MockControllerProxyClientMockRecorder) DeleteSubscription(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteToken mocks base method.
func (m *MockControllerProxyClient) DeleteToken(ctx context.Context, in *controller.DeleteTokenRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteToken indicates an expected call of DeleteToken.
func (mr *MockControllerProxyClientMockRecorder) DeleteToken(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteUser mocks base method.
func (m *MockControllerProxyClient) DeleteUser(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockControllerProxyClientMockRecorder) DeleteUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DisableSubscription mocks base method.
func (m *MockControllerProxyClient) DisableSubscription(ctx context.Context, in *controller.DisableSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DisableSubscription indicates an expected call of DisableSubscription.
func (mr *MockControllerProxyClientMockRecorder) DisableSubscription(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetDeadLetterEvent mocks base method.
func (m *MockControllerProxyClient) GetDeadLetterEvent(ctx context.Context, in *GetDeadLetterEventRequest, opts ...grpc.CallOption) (*GetDeadLetterEventResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDeadLetterEvent indicates an expected call of GetDeadLetterEvent.
func (mr *MockControllerProxyClientMockRecorder) GetDeadLetterEvent(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEvent mocks base method.
func (m *MockControllerProxyClient) GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*GetEventResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEvent indicates an expected call of GetEvent.
func (mr *MockControllerProxyClientMockRecorder) GetEvent(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEventbus mocks base method.
func (m *MockControllerProxyClient) GetEventbus(ctx context.Context, in *wrapperspb.UInt64Value, opts ...grpc.CallOption) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEventbus indicates an expected call of GetEventbus.
func (mr *MockControllerProxyClientMockRecorder) GetEventbus(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEventbusWithHumanFriendly mocks base method.
func (m *MockControllerProxyClient) GetEventbusWithHumanFriendly(ctx context.Context, in *controller.GetEventbusWithHumanFriendlyRequest, opts ...grpc.CallOption) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEventbusWithHumanFriendly indicates an expected call of GetEventbusWithHumanFriendly.
func (mr *MockControllerProxyClientMockRecorder) GetEventbusWithHumanFriendly(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNamespace mocks base method.
func (m *MockControllerProxyClient) GetNamespace(ctx context.Context, in *controller.GetNamespaceRequest, opts ...grpc.CallOption) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockControllerProxyClientMockRecorder) GetNamespace(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNamespaceWithHumanFriendly mocks base method.
func (m *MockControllerProxyClient) GetNamespaceWithHumanFriendly(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetNamespaceWithHumanFriendly indicates an expected call of GetNamespaceWithHumanFriendly.
func (mr *MockControllerProxyClientMockRecorder) GetNamespaceWithHumanFriendly(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetResourceRole mocks base method.
func (m *MockControllerProxyClient) GetResourceRole(ctx context.Context, in *controller.GetResourceRoleRequest, opts ...grpc.CallOption) (*controller.GetResourceRoleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetResourceRole indicates an expected call of GetResourceRole.
func (mr *MockControllerProxyClientMockRecorder) GetResourceRole(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSubscription mocks base method.
func (m *MockControllerProxyClient) GetSubscription(ctx context.Context, in *controller.GetSubscriptionRequest, opts ...grpc.CallOption) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetSubscription indicates an expected call of GetSubscription.
func (mr *MockControllerProxyClientMockRecorder) GetSubscription(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUser mocks base method.
func (m *MockControllerProxyClient) GetUser(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*meta.User, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUser indicates an expected call of GetUser.
func (mr *MockControllerProxyClientMockRecorder) GetUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUserRole mocks base method.
func (m *MockControllerProxyClient) GetUserRole(ctx context.Context, in *controller.GetUserRoleRequest, opts ...grpc.CallOption) (*controller.GetUserRoleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockControllerProxyClientMockRecorder) GetUserRole(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUserToken mocks base method.
func (m *MockControllerProxyClient) GetUserToken(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*controller.GetTokenResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUserToken indicates an expected call of GetUserToken.
func (mr *MockControllerProxyClientMockRecorder) GetUserToken(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GrantRole mocks base method.
func (m *MockControllerProxyClient) GrantRole(ctx context.Context, in *controller.RoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GrantRole indicates an expected call of GrantRole.
func (mr *MockControllerProxyClientMockRecorder) GrantRole(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListEventbus mocks base method.
func (m *MockControllerProxyClient) ListEventbus(ctx context.Context, in *controller.ListEventbusRequest, opts ...grpc.CallOption) (*controller.ListEventbusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListEventbus indicates an expected call of ListEventbus.
func (mr *MockControllerProxyClientMockRecorder) ListEventbus(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListNamespace mocks base method.
func (m *MockControllerProxyClient) ListNamespace(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*controller.ListNamespaceResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListNamespace indicates an expected call of ListNamespace.
func (mr *MockControllerProxyClientMockRecorder) ListNamespace(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListSegment mocks base method.
func (m *MockControllerProxyClient) ListSegment(ctx context.Context, in *controller.ListSegmentRequest, opts ...grpc.CallOption) (*controller.ListSegmentResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListSegment indicates an expected call of ListSegment.
func (mr *MockControllerProxyClientMockRecorder) ListSegment(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListSubscription mocks base method.
func (m *MockControllerProxyClient) ListSubscription(ctx context.Context, in *controller.ListSubscriptionRequest, opts ...grpc.CallOption) (*controller.ListSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListSubscription indicates an expected call of ListSubscription.
func (mr *MockControllerProxyClientMockRecorder) ListSubscription(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListToken mocks base method.
func (m *MockControllerProxyClient) ListToken(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*controller.ListTokenResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListToken indicates an expected call of ListToken.
func (mr *MockControllerProxyClientMockRecorder) ListToken(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListUser mocks base method.
func (m *MockControllerProxyClient) ListUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*controller.ListUserResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListUser indicates an expected call of ListUser.
func (mr *MockControllerProxyClientMockRecorder) ListUser(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LookupOffset mocks base method.
func (m *MockControllerProxyClient) LookupOffset(ctx context.Context, in *LookupOffsetRequest, opts ...grpc.CallOption) (*LookupOffsetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// LookupOffset indicates an expected call of LookupOffset.
func (mr *MockControllerProxyClientMockRecorder) LookupOffset(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResendDeadLetterEvent mocks base method.
func (m *MockControllerProxyClient) ResendDeadLetterEvent(ctx context.Context, in *ResendDeadLetterEventRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ResendDeadLetterEvent indicates an expected call of ResendDeadLetterEvent.
func (mr *MockControllerProxyClientMockRecorder) ResendDeadLetterEvent(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResetOffsetToTimestamp mocks base method.
func (m *MockControllerProxyClient) ResetOffsetToTimestamp(ctx context.Context, in *controller.ResetOffsetToTimestampRequest, opts ...grpc.CallOption) (*controller.ResetOffsetToTimestampResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ResetOffsetToTimestamp indicates an expected call of ResetOffsetToTimestamp.
func (mr *MockControllerProxyClientMockRecorder) ResetOffsetToTimestamp(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResumeSubscription mocks base method.
func (m *MockControllerProxyClient) ResumeSubscription(ctx context.Context, in *controller.ResumeSubscriptionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ResumeSubscription indicates an expected call of ResumeSubscription.
func (mr *MockControllerProxyClientMockRecorder) ResumeSubscription(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RevokeRole mocks base method.
func (m *MockControllerProxyClient) RevokeRole(ctx context.Context, in *controller.RoleRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RevokeRole indicates an expected call of RevokeRole.
func (mr *MockControllerProxyClientMockRecorder) RevokeRole(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetDeadLetterEventOffset mocks base method.
func (m *MockControllerProxyClient) SetDeadLetterEventOffset(ctx context.Context, in *controller.SetDeadLetterEventOffsetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SetDeadLetterEventOffset indicates an expected call of SetDeadLetterEventOffset.
func (mr *MockControllerProxyClientMockRecorder) SetDeadLetterEventOffset(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateEventbus mocks base method.
func (m *MockControllerProxyClient) UpdateEventbus(ctx context.Context, in *controller.UpdateEventbusRequest, opts ...grpc.CallOption) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateEventbus indicates an expected call of UpdateEventbus.
func (mr *MockControllerProxyClientMockRecorder) UpdateEventbus(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateSubscription mocks base method.
func (m *MockControllerProxyClient) UpdateSubscription(ctx context.Context, in *controller.UpdateSubscriptionRequest, opts ...grpc.CallOption) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateSubscription indicates an expected call of UpdateSubscription.
func (mr *MockControllerProxyClientMockRecorder) UpdateSubscription(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ValidateEventbus mocks base method.
func (m *MockControllerProxyClient) ValidateEventbus(ctx context.Context, in *ValidateEventbusRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ValidateEventbus indicates an expected call of ValidateEventbus.
func (mr *MockControllerProxyClientMockRecorder) ValidateEventbus(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ValidateSubscription mocks base method.
func (m *MockControllerProxyClient) ValidateSubscription(ctx context.Context, in *ValidateSubscriptionRequest, opts ...grpc.CallOption) (*ValidateSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ValidateSubscription indicates an expected call of ValidateSubscription.
func (mr *MockControllerProxyClientMockRecorder) ValidateSubscription(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockControllerProxyServer is a mock of ControllerProxyServer interface.
type MockControllerProxyServer struct {
	ctrl     *gomock.Controller
	recorder *MockControllerProxyServerMockRecorder
}

// MockControllerProxyServerMockRecorder is the mock recorder for MockControllerProxyServer.
type MockControllerProxyServerMockRecorder struct {
	mock *MockControllerProxyServer
}

// NewMockControllerProxyServer creates a new mock instance.
func NewMockControllerProxyServer(ctrl *gomock.Controller) *MockControllerProxyServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControllerProxyServer) EXPECT() *MockControllerProxyServerMockRecorder {
	_ = "STUB: not implemented"

	// ClusterInfo mocks base method.
	return nil
}

func (m *MockControllerProxyServer) ClusterInfo(ctx context.Context, in *emptypb.Empty) (*ClusterInfoResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ClusterInfo indicates an expected call of ClusterInfo.
func (mr *MockControllerProxyServerMockRecorder) ClusterInfo(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateEventbus mocks base method.
func (m *MockControllerProxyServer) CreateEventbus(ctx context.Context, in *controller.CreateEventbusRequest) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateEventbus indicates an expected call of CreateEventbus.
func (mr *MockControllerProxyServerMockRecorder) CreateEventbus(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateNamespace mocks base method.
func (m *MockControllerProxyServer) CreateNamespace(ctx context.Context, in *controller.CreateNamespaceRequest) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateNamespace indicates an expected call of CreateNamespace.
func (mr *MockControllerProxyServerMockRecorder) CreateNamespace(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateSubscription mocks base method.
func (m *MockControllerProxyServer) CreateSubscription(ctx context.Context, in *controller.CreateSubscriptionRequest) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockControllerProxyServerMockRecorder) CreateSubscription(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateSystemEventbus mocks base method.
func (m *MockControllerProxyServer) CreateSystemEventbus(ctx context.Context, in *controller.CreateEventbusRequest) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateSystemEventbus indicates an expected call of CreateSystemEventbus.
func (mr *MockControllerProxyServerMockRecorder) CreateSystemEventbus(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateToken mocks base method.
func (m *MockControllerProxyServer) CreateToken(ctx context.Context, in *controller.CreateTokenRequest) (*meta.Token, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockControllerProxyServerMockRecorder) CreateToken(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateUser mocks base method.
func (m *MockControllerProxyServer) CreateUser(ctx context.Context, in *controller.CreateUserRequest) (*meta.User, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockControllerProxyServerMockRecorder) CreateUser(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteEventbus mocks base method.
func (m *MockControllerProxyServer) DeleteEventbus(ctx context.Context, in *wrapperspb.UInt64Value) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteEventbus indicates an expected call of DeleteEventbus.
func (mr *MockControllerProxyServerMockRecorder) DeleteEventbus(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteNamespace mocks base method.
func (m *MockControllerProxyServer) DeleteNamespace(ctx context.Context, in *controller.DeleteNamespaceRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteNamespace indicates an expected call of DeleteNamespace.
func (mr *MockControllerProxyServerMockRecorder) DeleteNamespace(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteSubscription mocks base method.
func (m *MockControllerProxyServer) DeleteSubscription(ctx context.Context, in *controller.DeleteSubscriptionRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteSubscription indicates an expected call of DeleteSubscription.
func (mr *MockControllerProxyServerMockRecorder) DeleteSubscription(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteToken mocks base method.
func (m *MockControllerProxyServer) DeleteToken(ctx context.Context, in *controller.DeleteTokenRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteToken indicates an expected call of DeleteToken.
func (mr *MockControllerProxyServerMockRecorder) DeleteToken(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteUser mocks base method.
func (m *MockControllerProxyServer) DeleteUser(ctx context.Context, in *wrapperspb.StringValue) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockControllerProxyServerMockRecorder) DeleteUser(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DisableSubscription mocks base method.
func (m *MockControllerProxyServer) DisableSubscription(ctx context.Context, in *controller.DisableSubscriptionRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DisableSubscription indicates an expected call of DisableSubscription.
func (mr *MockControllerProxyServerMockRecorder) DisableSubscription(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetDeadLetterEvent mocks base method.
func (m *MockControllerProxyServer) GetDeadLetterEvent(ctx context.Context, in *GetDeadLetterEventRequest) (*GetDeadLetterEventResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetDeadLetterEvent indicates an expected call of GetDeadLetterEvent.
func (mr *MockControllerProxyServerMockRecorder) GetDeadLetterEvent(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEvent mocks base method.
func (m *MockControllerProxyServer) GetEvent(ctx context.Context, in *GetEventRequest) (*GetEventResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEvent indicates an expected call of GetEvent.
func (mr *MockControllerProxyServerMockRecorder) GetEvent(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEventbus mocks base method.
func (m *MockControllerProxyServer) GetEventbus(ctx context.Context, in *wrapperspb.UInt64Value) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEventbus indicates an expected call of GetEventbus.
func (mr *MockControllerProxyServerMockRecorder) GetEventbus(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetEventbusWithHumanFriendly mocks base method.
func (m *MockControllerProxyServer) GetEventbusWithHumanFriendly(ctx context.Context, in *controller.GetEventbusWithHumanFriendlyRequest) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetEventbusWithHumanFriendly indicates an expected call of GetEventbusWithHumanFriendly.
func (mr *MockControllerProxyServerMockRecorder) GetEventbusWithHumanFriendly(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNamespace mocks base method.
func (m *MockControllerProxyServer) GetNamespace(ctx context.Context, in *controller.GetNamespaceRequest) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetNamespace indicates an expected call of GetNamespace.
func (mr *MockControllerProxyServerMockRecorder) GetNamespace(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetNamespaceWithHumanFriendly mocks base method.
func (m *MockControllerProxyServer) GetNamespaceWithHumanFriendly(ctx context.Context, in *wrapperspb.StringValue) (*meta.Namespace, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetNamespaceWithHumanFriendly indicates an expected call of GetNamespaceWithHumanFriendly.
func (mr *MockControllerProxyServerMockRecorder) GetNamespaceWithHumanFriendly(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetResourceRole mocks base method.
func (m *MockControllerProxyServer) GetResourceRole(ctx context.Context, in *controller.GetResourceRoleRequest) (*controller.GetResourceRoleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetResourceRole indicates an expected call of GetResourceRole.
func (mr *MockControllerProxyServerMockRecorder) GetResourceRole(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSubscription mocks base method.
func (m *MockControllerProxyServer) GetSubscription(ctx context.Context, in *controller.GetSubscriptionRequest) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetSubscription indicates an expected call of GetSubscription.
func (mr *MockControllerProxyServerMockRecorder) GetSubscription(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUser mocks base method.
func (m *MockControllerProxyServer) GetUser(ctx context.Context, in *wrapperspb.StringValue) (*meta.User, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUser indicates an expected call of GetUser.
func (mr *MockControllerProxyServerMockRecorder) GetUser(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUserRole mocks base method.
func (m *MockControllerProxyServer) GetUserRole(ctx context.Context, in *controller.GetUserRoleRequest) (*controller.GetUserRoleResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUserRole indicates an expected call of GetUserRole.
func (mr *MockControllerProxyServerMockRecorder) GetUserRole(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUserToken mocks base method.
func (m *MockControllerProxyServer) GetUserToken(ctx context.Context, in *wrapperspb.StringValue) (*controller.GetTokenResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetUserToken indicates an expected call of GetUserToken.
func (mr *MockControllerProxyServerMockRecorder) GetUserToken(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GrantRole mocks base method.
func (m *MockControllerProxyServer) GrantRole(ctx context.Context, in *controller.RoleRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GrantRole indicates an expected call of GrantRole.
func (mr *MockControllerProxyServerMockRecorder) GrantRole(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListEventbus mocks base method.
func (m *MockControllerProxyServer) ListEventbus(ctx context.Context, in *controller.ListEventbusRequest) (*controller.ListEventbusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListEventbus indicates an expected call of ListEventbus.
func (mr *MockControllerProxyServerMockRecorder) ListEventbus(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListNamespace mocks base method.
func (m *MockControllerProxyServer) ListNamespace(ctx context.Context, in *emptypb.Empty) (*controller.ListNamespaceResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListNamespace indicates an expected call of ListNamespace.
func (mr *MockControllerProxyServerMockRecorder) ListNamespace(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListSegment mocks base method.
func (m *MockControllerProxyServer) ListSegment(ctx context.Context, in *controller.ListSegmentRequest) (*controller.ListSegmentResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListSegment indicates an expected call of ListSegment.
func (mr *MockControllerProxyServerMockRecorder) ListSegment(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListSubscription mocks base method.
func (m *MockControllerProxyServer) ListSubscription(ctx context.Context, in *controller.ListSubscriptionRequest) (*controller.ListSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListSubscription indicates an expected call of ListSubscription.
func (mr *MockControllerProxyServerMockRecorder) ListSubscription(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListToken mocks base method.
func (m *MockControllerProxyServer) ListToken(ctx context.Context, in *emptypb.Empty) (*controller.ListTokenResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListToken indicates an expected call of ListToken.
func (mr *MockControllerProxyServerMockRecorder) ListToken(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListUser mocks base method.
func (m *MockControllerProxyServer) ListUser(ctx context.Context, in *emptypb.Empty) (*controller.ListUserResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListUser indicates an expected call of ListUser.
func (mr *MockControllerProxyServerMockRecorder) ListUser(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LookupOffset mocks base method.
func (m *MockControllerProxyServer) LookupOffset(ctx context.Context, in *LookupOffsetRequest) (*LookupOffsetResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// LookupOffset indicates an expected call of LookupOffset.
func (mr *MockControllerProxyServerMockRecorder) LookupOffset(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResendDeadLetterEvent mocks base method.
func (m *MockControllerProxyServer) ResendDeadLetterEvent(ctx context.Context, in *ResendDeadLetterEventRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ResendDeadLetterEvent indicates an expected call of ResendDeadLetterEvent.
func (mr *MockControllerProxyServerMockRecorder) ResendDeadLetterEvent(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResetOffsetToTimestamp mocks base method.
func (m *MockControllerProxyServer) ResetOffsetToTimestamp(ctx context.Context, in *controller.ResetOffsetToTimestampRequest) (*controller.ResetOffsetToTimestampResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ResetOffsetToTimestamp indicates an expected call of ResetOffsetToTimestamp.
func (mr *MockControllerProxyServerMockRecorder) ResetOffsetToTimestamp(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResumeSubscription mocks base method.
func (m *MockControllerProxyServer) ResumeSubscription(ctx context.Context, in *controller.ResumeSubscriptionRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ResumeSubscription indicates an expected call of ResumeSubscription.
func (mr *MockControllerProxyServerMockRecorder) ResumeSubscription(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RevokeRole mocks base method.
func (m *MockControllerProxyServer) RevokeRole(ctx context.Context, in *controller.RoleRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RevokeRole indicates an expected call of RevokeRole.
func (mr *MockControllerProxyServerMockRecorder) RevokeRole(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetDeadLetterEventOffset mocks base method.
func (m *MockControllerProxyServer) SetDeadLetterEventOffset(ctx context.Context, in *controller.SetDeadLetterEventOffsetRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// SetDeadLetterEventOffset indicates an expected call of SetDeadLetterEventOffset.
func (mr *MockControllerProxyServerMockRecorder) SetDeadLetterEventOffset(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateEventbus mocks base method.
func (m *MockControllerProxyServer) UpdateEventbus(ctx context.Context, in *controller.UpdateEventbusRequest) (*meta.Eventbus, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateEventbus indicates an expected call of UpdateEventbus.
func (mr *MockControllerProxyServerMockRecorder) UpdateEventbus(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateSubscription mocks base method.
func (m *MockControllerProxyServer) UpdateSubscription(ctx context.Context, in *controller.UpdateSubscriptionRequest) (*meta.Subscription, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UpdateSubscription indicates an expected call of UpdateSubscription.
func (mr *MockControllerProxyServerMockRecorder) UpdateSubscription(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ValidateEventbus mocks base method.
func (m *MockControllerProxyServer) ValidateEventbus(ctx context.Context, in *ValidateEventbusRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ValidateEventbus indicates an expected call of ValidateEventbus.
func (mr *MockControllerProxyServerMockRecorder) ValidateEventbus(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ValidateSubscription mocks base method.
func (m *MockControllerProxyServer) ValidateSubscription(ctx context.Context, in *ValidateSubscriptionRequest) (*ValidateSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ValidateSubscription indicates an expected call of ValidateSubscription.
func (mr *MockControllerProxyServerMockRecorder) ValidateSubscription(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockStoreProxy_SubscribeClient is a mock of StoreProxy_SubscribeClient interface.
type MockStoreProxy_SubscribeClient struct {
	ctrl     *gomock.Controller
	recorder *MockStoreProxy_SubscribeClientMockRecorder
}

// MockStoreProxy_SubscribeClientMockRecorder is the mock recorder for MockStoreProxy_SubscribeClient.
type MockStoreProxy_SubscribeClientMockRecorder struct {
	mock *MockStoreProxy_SubscribeClient
}

// NewMockStoreProxy_SubscribeClient creates a new mock instance.
func NewMockStoreProxy_SubscribeClient(ctrl *gomock.Controller) *MockStoreProxy_SubscribeClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreProxy_SubscribeClient) EXPECT() *MockStoreProxy_SubscribeClientMockRecorder {
	_ = "STUB: not implemented"

	// CloseSend mocks base method.
	return nil
}

func (m *MockStoreProxy_SubscribeClient) CloseSend() error { _ = "STUB: not implemented"; return nil }

// CloseSend indicates an expected call of CloseSend.
func (mr *MockStoreProxy_SubscribeClientMockRecorder) CloseSend() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Context mocks base method.
func (m *MockStoreProxy_SubscribeClient) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockStoreProxy_SubscribeClientMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Header mocks base method.
func (m *MockStoreProxy_SubscribeClient) Header() (metadata.MD, error) {
	_ = "STUB: not implemented"
	return *new(metadata.MD), nil
}

// Header indicates an expected call of Header.
func (mr *MockStoreProxy_SubscribeClientMockRecorder) Header() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Recv mocks base method.
func (m *MockStoreProxy_SubscribeClient) Recv() (*SubscribeResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Recv indicates an expected call of Recv.
func (mr *MockStoreProxy_SubscribeClientMockRecorder) Recv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m *MockStoreProxy_SubscribeClient) RecvMsg(arg0 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockStoreProxy_SubscribeClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m *MockStoreProxy_SubscribeClient) SendMsg(arg0 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockStoreProxy_SubscribeClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Trailer mocks base method.
func (m *MockStoreProxy_SubscribeClient) Trailer() metadata.MD {
	_ = "STUB: not implemented"
	return *new(metadata.MD)
}

// Trailer indicates an expected call of Trailer.
func (mr *MockStoreProxy_SubscribeClientMockRecorder) Trailer() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockStoreProxy_SubscribeServer is a mock of StoreProxy_SubscribeServer interface.
type MockStoreProxy_SubscribeServer struct {
	ctrl     *gomock.Controller
	recorder *MockStoreProxy_SubscribeServerMockRecorder
}

// MockStoreProxy_SubscribeServerMockRecorder is the mock recorder for MockStoreProxy_SubscribeServer.
type MockStoreProxy_SubscribeServerMockRecorder struct {
	mock *MockStoreProxy_SubscribeServer
}

// NewMockStoreProxy_SubscribeServer creates a new mock instance.
func NewMockStoreProxy_SubscribeServer(ctrl *gomock.Controller) *MockStoreProxy_SubscribeServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreProxy_SubscribeServer) EXPECT() *MockStoreProxy_SubscribeServerMockRecorder {
	_ = "STUB: not implemented"

	// Context mocks base method.
	return nil
}

func (m *MockStoreProxy_SubscribeServer) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockStoreProxy_SubscribeServerMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m *MockStoreProxy_SubscribeServer) RecvMsg(arg0 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockStoreProxy_SubscribeServerMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Send mocks base method.
func (m *MockStoreProxy_SubscribeServer) Send(arg0 *SubscribeResponse) error {
	_ = "STUB: not implemented"
	return nil
}

// Send indicates an expected call of Send.
func (mr *MockStoreProxy_SubscribeServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader mocks base method.
func (m *MockStoreProxy_SubscribeServer) SendHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockStoreProxy_SubscribeServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m *MockStoreProxy_SubscribeServer) SendMsg(arg0 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockStoreProxy_SubscribeServerMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader mocks base method.
func (m *MockStoreProxy_SubscribeServer) SetHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockStoreProxy_SubscribeServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTrailer mocks base method.
func (m *MockStoreProxy_SubscribeServer) SetTrailer(arg0 metadata.MD) {
	_ = "STUB: not implemented"
	return
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockStoreProxy_SubscribeServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockStoreProxy_AckClient is a mock of StoreProxy_AckClient interface.
type MockStoreProxy_AckClient struct {
	ctrl     *gomock.Controller
	recorder *MockStoreProxy_AckClientMockRecorder
}

// MockStoreProxy_AckClientMockRecorder is the mock recorder for MockStoreProxy_AckClient.
type MockStoreProxy_AckClientMockRecorder struct {
	mock *MockStoreProxy_AckClient
}

// NewMockStoreProxy_AckClient creates a new mock instance.
func NewMockStoreProxy_AckClient(ctrl *gomock.Controller) *MockStoreProxy_AckClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreProxy_AckClient) EXPECT() *MockStoreProxy_AckClientMockRecorder {
	_ = "STUB: not implemented"

	// CloseAndRecv mocks base method.
	return nil
}

func (m *MockStoreProxy_AckClient) CloseAndRecv() (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// CloseAndRecv indicates an expected call of CloseAndRecv.
func (mr *MockStoreProxy_AckClientMockRecorder) CloseAndRecv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CloseSend mocks base method.
func (m *MockStoreProxy_AckClient) CloseSend() error { _ = "STUB: not implemented"; return nil }

// CloseSend indicates an expected call of CloseSend.
func (mr *MockStoreProxy_AckClientMockRecorder) CloseSend() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Context mocks base method.
func (m *MockStoreProxy_AckClient) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockStoreProxy_AckClientMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Header mocks base method.
func (m *MockStoreProxy_AckClient) Header() (metadata.MD, error) {
	_ = "STUB: not implemented"
	return *new(metadata.MD), nil
}

// Header indicates an expected call of Header.
func (mr *MockStoreProxy_AckClientMockRecorder) Header() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m *MockStoreProxy_AckClient) RecvMsg(arg0 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockStoreProxy_AckClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Send mocks base method.
func (m *MockStoreProxy_AckClient) Send(arg0 *AckRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// Send indicates an expected call of Send.
func (mr *MockStoreProxy_AckClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m *MockStoreProxy_AckClient) SendMsg(arg0 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockStoreProxy_AckClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Trailer mocks base method.
func (m *MockStoreProxy_AckClient) Trailer() metadata.MD {
	_ = "STUB: not implemented"
	return *new(metadata.MD)
}

// Trailer indicates an expected call of Trailer.
func (mr *MockStoreProxy_AckClientMockRecorder) Trailer() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockStoreProxy_AckServer is a mock of StoreProxy_AckServer interface.
type MockStoreProxy_AckServer struct {
	ctrl     *gomock.Controller
	recorder *MockStoreProxy_AckServerMockRecorder
}

// MockStoreProxy_AckServerMockRecorder is the mock recorder for MockStoreProxy_AckServer.
type MockStoreProxy_AckServerMockRecorder struct {
	mock *MockStoreProxy_AckServer
}

// NewMockStoreProxy_AckServer creates a new mock instance.
func NewMockStoreProxy_AckServer(ctrl *gomock.Controller) *MockStoreProxy_AckServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreProxy_AckServer) EXPECT() *MockStoreProxy_AckServerMockRecorder {
	_ = "STUB: not implemented"

	// Context mocks base method.
	return nil
}

func (m *MockStoreProxy_AckServer) Context() context.Context {
	_ = "STUB: not implemented"
	return *new(context.Context)
}

// Context indicates an expected call of Context.
func (mr *MockStoreProxy_AckServerMockRecorder) Context() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Recv mocks base method.
func (m *MockStoreProxy_AckServer) Recv() (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Recv indicates an expected call of Recv.
func (mr *MockStoreProxy_AckServerMockRecorder) Recv() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg mocks base method.
func (m *MockStoreProxy_AckServer) RecvMsg(arg0 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockStoreProxy_AckServerMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendAndClose mocks base method.
func (m *MockStoreProxy_AckServer) SendAndClose(arg0 *AckRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// SendAndClose indicates an expected call of SendAndClose.
func (mr *MockStoreProxy_AckServerMockRecorder) SendAndClose(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader mocks base method.
func (m *MockStoreProxy_AckServer) SendHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockStoreProxy_AckServerMockRecorder) SendHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg mocks base method.
func (m *MockStoreProxy_AckServer) SendMsg(arg0 interface{}) error {
	_ = "STUB: not implemented"
	return nil
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockStoreProxy_AckServerMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader mocks base method.
func (m *MockStoreProxy_AckServer) SetHeader(arg0 metadata.MD) error {
	_ = "STUB: not implemented"
	return nil
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockStoreProxy_AckServerMockRecorder) SetHeader(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SetTrailer mocks base method.
func (m *MockStoreProxy_AckServer) SetTrailer(arg0 metadata.MD) { _ = "STUB: not implemented"; return }

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockStoreProxy_AckServerMockRecorder) SetTrailer(arg0 interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockStoreProxyClient is a mock of StoreProxyClient interface.
type MockStoreProxyClient struct {
	ctrl     *gomock.Controller
	recorder *MockStoreProxyClientMockRecorder
}

// MockStoreProxyClientMockRecorder is the mock recorder for MockStoreProxyClient.
type MockStoreProxyClientMockRecorder struct {
	mock *MockStoreProxyClient
}

// NewMockStoreProxyClient creates a new mock instance.
func NewMockStoreProxyClient(ctrl *gomock.Controller) *MockStoreProxyClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreProxyClient) EXPECT() *MockStoreProxyClientMockRecorder {
	_ = "STUB: not implemented"

	// Ack mocks base method.
	return nil
}

func (m *MockStoreProxyClient) Ack(ctx context.Context, opts ...grpc.CallOption) (StoreProxy_AckClient, error) {
	_ = "STUB: not implemented"
	return *new(StoreProxy_AckClient), nil
}

// Ack indicates an expected call of Ack.
func (mr *MockStoreProxyClientMockRecorder) Ack(ctx interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Publish mocks base method.
func (m *MockStoreProxyClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Publish indicates an expected call of Publish.
func (mr *MockStoreProxyClientMockRecorder) Publish(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Subscribe mocks base method.
func (m *MockStoreProxyClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (StoreProxy_SubscribeClient, error) {
	_ = "STUB: not implemented"
	return *new(StoreProxy_SubscribeClient), nil
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockStoreProxyClientMockRecorder) Subscribe(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockStoreProxyServer is a mock of StoreProxyServer interface.
type MockStoreProxyServer struct {
	ctrl     *gomock.Controller
	recorder *MockStoreProxyServerMockRecorder
}

// MockStoreProxyServerMockRecorder is the mock recorder for MockStoreProxyServer.
type MockStoreProxyServerMockRecorder struct {
	mock *MockStoreProxyServer
}

// NewMockStoreProxyServer creates a new mock instance.
func NewMockStoreProxyServer(ctrl *gomock.Controller) *MockStoreProxyServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreProxyServer) EXPECT() *MockStoreProxyServerMockRecorder {
	_ = "STUB: not implemented"

	// Ack mocks base method.
	return nil
}

func (m *MockStoreProxyServer) Ack(server StoreProxy_AckServer) error {
	_ = "STUB: not implemented"
	return nil
}

// Ack indicates an expected call of Ack.
func (mr *MockStoreProxyServerMockRecorder) Ack(server interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Publish mocks base method.
func (m *MockStoreProxyServer) Publish(ctx context.Context, in *PublishRequest) (*emptypb.Empty, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Publish indicates an expected call of Publish.
func (mr *MockStoreProxyServerMockRecorder) Publish(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Subscribe mocks base method.
func (m *MockStoreProxyServer) Subscribe(blob *SubscribeRequest, server StoreProxy_SubscribeServer) error {
	_ = "STUB: not implemented"
	return nil
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockStoreProxyServerMockRecorder) Subscribe(blob, server interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
