// Code generated by MockGen. DO NOT EDIT.
// Source: entry.go
//
// Generated by this command:
//
//	mockgen -source=entry.go -destination=testing/mock_entry.go -package=testing
//

// Package testing is a generated GoMock package.
package testing

import (
	time "time"

	block "github.com/vanus-labs/vanus/server/store/block"
	gomock "go.uber.org/mock/gomock"
)

// MockValue is a mock of Value interface.
type MockValue struct {
	ctrl     *gomock.Controller
	recorder *MockValueMockRecorder
}

// MockValueMockRecorder is the mock recorder for MockValue.
type MockValueMockRecorder struct {
	mock *MockValue
}

// NewMockValue creates a new mock instance.
func NewMockValue(ctrl *gomock.Controller) *MockValue { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValue) EXPECT() *MockValueMockRecorder {
	_ = "STUB: not implemented"

	// Size mocks base method.
	return nil
}

func (m *MockValue) Size() int { _ = "STUB: not implemented"; return 0 }

// Size indicates an expected call of Size.
func (mr *MockValueMockRecorder) Size() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Value mocks base method.
func (m *MockValue) Value() []byte { _ = "STUB: not implemented"; return nil }

// Value indicates an expected call of Value.
func (mr *MockValueMockRecorder) Value() *gomock.Call { _ = "STUB: not implemented"; return nil }

// MockValueMarshaler is a mock of ValueMarshaler interface.
type MockValueMarshaler struct {
	ctrl     *gomock.Controller
	recorder *MockValueMarshalerMockRecorder
}

// MockValueMarshalerMockRecorder is the mock recorder for MockValueMarshaler.
type MockValueMarshalerMockRecorder struct {
	mock *MockValueMarshaler
}

// NewMockValueMarshaler creates a new mock instance.
func NewMockValueMarshaler(ctrl *gomock.Controller) *MockValueMarshaler {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValueMarshaler) EXPECT() *MockValueMarshalerMockRecorder {
	_ = "STUB: not implemented"

	// MarshalTo mocks base method.
	return nil
}

func (m *MockValueMarshaler) MarshalTo(buf []byte) int { _ = "STUB: not implemented"; return 0 }

// MarshalTo indicates an expected call of MarshalTo.
func (mr *MockValueMarshalerMockRecorder) MarshalTo(buf any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Size mocks base method.
func (m *MockValueMarshaler) Size() int { _ = "STUB: not implemented"; return 0 }

// Size indicates an expected call of Size.
func (mr *MockValueMarshalerMockRecorder) Size() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Value mocks base method.
func (m *MockValueMarshaler) Value() []byte { _ = "STUB: not implemented"; return nil }

// Value indicates an expected call of Value.
func (mr *MockValueMarshalerMockRecorder) Value() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockExtensionAttributeCallback is a mock of ExtensionAttributeCallback interface.
type MockExtensionAttributeCallback struct {
	ctrl     *gomock.Controller
	recorder *MockExtensionAttributeCallbackMockRecorder
}

// MockExtensionAttributeCallbackMockRecorder is the mock recorder for MockExtensionAttributeCallback.
type MockExtensionAttributeCallbackMockRecorder struct {
	mock *MockExtensionAttributeCallback
}

// NewMockExtensionAttributeCallback creates a new mock instance.
func NewMockExtensionAttributeCallback(ctrl *gomock.Controller) *MockExtensionAttributeCallback {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtensionAttributeCallback) EXPECT() *MockExtensionAttributeCallbackMockRecorder {
	_ = "STUB: not implemented"

	// OnAttribute mocks base method.
	return nil
}

func (m *MockExtensionAttributeCallback) OnAttribute(attr []byte, val block.Value) {
	_ = "STUB: not implemented"
	return
}

// OnAttribute indicates an expected call of OnAttribute.
func (mr *MockExtensionAttributeCallbackMockRecorder) OnAttribute(attr, val any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockEntry is a mock of Entry interface.
type MockEntry struct {
	ctrl     *gomock.Controller
	recorder *MockEntryMockRecorder
}

// MockEntryMockRecorder is the mock recorder for MockEntry.
type MockEntryMockRecorder struct {
	mock *MockEntry
}

// NewMockEntry creates a new mock instance.
func NewMockEntry(ctrl *gomock.Controller) *MockEntry { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntry) EXPECT() *MockEntryMockRecorder {
	_ = "STUB: not implemented"

	// Get mocks base method.
	return nil
}

func (m *MockEntry) Get(ordinal int) any { _ = "STUB: not implemented"; return *new(any) }

// Get indicates an expected call of Get.
func (mr *MockEntryMockRecorder) Get(ordinal any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBytes mocks base method.
func (m *MockEntry) GetBytes(ordinal int) []byte { _ = "STUB: not implemented"; return nil }

// GetBytes indicates an expected call of GetBytes.
func (mr *MockEntryMockRecorder) GetBytes(ordinal any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetExtensionAttribute mocks base method.
func (m *MockEntry) GetExtensionAttribute(arg0 []byte) []byte {
	_ = "STUB: not implemented"
	return nil
}

// GetExtensionAttribute indicates an expected call of GetExtensionAttribute.
func (mr *MockEntryMockRecorder) GetExtensionAttribute(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInt64 mocks base method.
func (m *MockEntry) GetInt64(ordinal int) int64 { _ = "STUB: not implemented"; return 0 }

// GetInt64 indicates an expected call of GetInt64.
func (mr *MockEntryMockRecorder) GetInt64(ordinal any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetString mocks base method.
func (m *MockEntry) GetString(ordinal int) string { _ = "STUB: not implemented"; return "" }

// GetString indicates an expected call of GetString.
func (mr *MockEntryMockRecorder) GetString(ordinal any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetTime mocks base method.
func (m *MockEntry) GetTime(ordinal int) time.Time {
	_ = "STUB: not implemented"
	return *new(time.Time)
}

// GetTime indicates an expected call of GetTime.
func (mr *MockEntryMockRecorder) GetTime(ordinal any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUint16 mocks base method.
func (m *MockEntry) GetUint16(ordinal int) uint16 { _ = "STUB: not implemented"; return 0 }

// GetUint16 indicates an expected call of GetUint16.
func (mr *MockEntryMockRecorder) GetUint16(ordinal any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUint64 mocks base method.
func (m *MockEntry) GetUint64(ordinal int) uint64 { _ = "STUB: not implemented"; return 0 }

// GetUint64 indicates an expected call of GetUint64.
func (mr *MockEntryMockRecorder) GetUint64(ordinal any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RangeExtensionAttributes mocks base method.
func (m *MockEntry) RangeExtensionAttributes(cb block.ExtensionAttributeCallback) {
	_ = "STUB: not implemented"
	return
}

// RangeExtensionAttributes indicates an expected call of RangeExtensionAttributes.
func (mr *MockEntryMockRecorder) RangeExtensionAttributes(cb any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockOptionalAttributeCallback is a mock of OptionalAttributeCallback interface.
type MockOptionalAttributeCallback struct {
	ctrl     *gomock.Controller
	recorder *MockOptionalAttributeCallbackMockRecorder
}

// MockOptionalAttributeCallbackMockRecorder is the mock recorder for MockOptionalAttributeCallback.
type MockOptionalAttributeCallbackMockRecorder struct {
	mock *MockOptionalAttributeCallback
}

// NewMockOptionalAttributeCallback creates a new mock instance.
func NewMockOptionalAttributeCallback(ctrl *gomock.Controller) *MockOptionalAttributeCallback {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOptionalAttributeCallback) EXPECT() *MockOptionalAttributeCallbackMockRecorder {
	_ = "STUB: not implemented"

	// OnAttribute mocks base method.
	return nil
}

func (m *MockOptionalAttributeCallback) OnAttribute(ordinal int, val any) {
	_ = "STUB: not implemented"
	return
}

// OnAttribute indicates an expected call of OnAttribute.
func (mr *MockOptionalAttributeCallbackMockRecorder) OnAttribute(ordinal, val any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// OnBytes mocks base method.
func (m *MockOptionalAttributeCallback) OnBytes(ordinal int, val []byte) {
	_ = "STUB: not implemented"
	return
}

// OnBytes indicates an expected call of OnBytes.
func (mr *MockOptionalAttributeCallbackMockRecorder) OnBytes(ordinal, val any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// OnInt64 mocks base method.
func (m *MockOptionalAttributeCallback) OnInt64(ordinal int, val int64) {
	_ = "STUB: not implemented"
	return
}

// OnInt64 indicates an expected call of OnInt64.
func (mr *MockOptionalAttributeCallbackMockRecorder) OnInt64(ordinal, val any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// OnString mocks base method.
func (m *MockOptionalAttributeCallback) OnString(ordinal int, val string) {
	_ = "STUB: not implemented"
	return
}

// OnString indicates an expected call of OnString.
func (mr *MockOptionalAttributeCallbackMockRecorder) OnString(ordinal, val any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// OnTime mocks base method.
func (m *MockOptionalAttributeCallback) OnTime(ordinal int, val time.Time) {
	_ = "STUB: not implemented"
	return
}

// OnTime indicates an expected call of OnTime.
func (mr *MockOptionalAttributeCallbackMockRecorder) OnTime(ordinal, val any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// OnUint16 mocks base method.
func (m *MockOptionalAttributeCallback) OnUint16(ordinal int, val uint16) {
	_ = "STUB: not implemented"
	return
}

// OnUint16 indicates an expected call of OnUint16.
func (mr *MockOptionalAttributeCallbackMockRecorder) OnUint16(ordinal, val any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// OnUint64 mocks base method.
func (m *MockOptionalAttributeCallback) OnUint64(ordinal int, val uint64) {
	_ = "STUB: not implemented"
	return
}

// OnUint64 indicates an expected call of OnUint64.
func (mr *MockOptionalAttributeCallbackMockRecorder) OnUint64(ordinal, val any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockEntryExt is a mock of EntryExt interface.
type MockEntryExt struct {
	ctrl     *gomock.Controller
	recorder *MockEntryExtMockRecorder
}

// MockEntryExtMockRecorder is the mock recorder for MockEntryExt.
type MockEntryExtMockRecorder struct {
	mock *MockEntryExt
}

// NewMockEntryExt creates a new mock instance.
func NewMockEntryExt(ctrl *gomock.Controller) *MockEntryExt { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntryExt) EXPECT() *MockEntryExtMockRecorder {
	_ = "STUB: not implemented"

	// ExtensionAttributeCount mocks base method.
	return nil
}

func (m *MockEntryExt) ExtensionAttributeCount() int { _ = "STUB: not implemented"; return 0 }

// ExtensionAttributeCount indicates an expected call of ExtensionAttributeCount.
func (mr *MockEntryExtMockRecorder) ExtensionAttributeCount() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Get mocks base method.
func (m *MockEntryExt) Get(ordinal int) any { _ = "STUB: not implemented"; return *new(any) }

// Get indicates an expected call of Get.
func (mr *MockEntryExtMockRecorder) Get(ordinal any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetBytes mocks base method.
func (m *MockEntryExt) GetBytes(ordinal int) []byte { _ = "STUB: not implemented"; return nil }

// GetBytes indicates an expected call of GetBytes.
func (mr *MockEntryExtMockRecorder) GetBytes(ordinal any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetExtensionAttribute mocks base method.
func (m *MockEntryExt) GetExtensionAttribute(arg0 []byte) []byte {
	_ = "STUB: not implemented"
	return nil
}

// GetExtensionAttribute indicates an expected call of GetExtensionAttribute.
func (mr *MockEntryExtMockRecorder) GetExtensionAttribute(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetInt64 mocks base method.
func (m *MockEntryExt) GetInt64(ordinal int) int64 { _ = "STUB: not implemented"; return 0 }

// GetInt64 indicates an expected call of GetInt64.
func (mr *MockEntryExtMockRecorder) GetInt64(ordinal any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetString mocks base method.
func (m *MockEntryExt) GetString(ordinal int) string { _ = "STUB: not implemented"; return "" }

// GetString indicates an expected call of GetString.
func (mr *MockEntryExtMockRecorder) GetString(ordinal any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetTime mocks base method.
func (m *MockEntryExt) GetTime(ordinal int) time.Time {
	_ = "STUB: not implemented"
	return *new(time.Time)
}

// GetTime indicates an expected call of GetTime.
func (mr *MockEntryExtMockRecorder) GetTime(ordinal any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUint16 mocks base method.
func (m *MockEntryExt) GetUint16(ordinal int) uint16 { _ = "STUB: not implemented"; return 0 }

// GetUint16 indicates an expected call of GetUint16.
func (mr *MockEntryExtMockRecorder) GetUint16(ordinal any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetUint64 mocks base method.
func (m *MockEntryExt) GetUint64(ordinal int) uint64 { _ = "STUB: not implemented"; return 0 }

// GetUint64 indicates an expected call of GetUint64.
func (mr *MockEntryExtMockRecorder) GetUint64(ordinal any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// OptionalAttributeCount mocks base method.
func (m *MockEntryExt) OptionalAttributeCount() int { _ = "STUB: not implemented"; return 0 }

// OptionalAttributeCount indicates an expected call of OptionalAttributeCount.
func (mr *MockEntryExtMockRecorder) OptionalAttributeCount() *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RangeExtensionAttributes mocks base method.
func (m *MockEntryExt) RangeExtensionAttributes(cb block.ExtensionAttributeCallback) {
	_ = "STUB: not implemented"
	return
}

// RangeExtensionAttributes indicates an expected call of RangeExtensionAttributes.
func (mr *MockEntryExtMockRecorder) RangeExtensionAttributes(cb any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RangeOptionalAttributes mocks base method.
func (m *MockEntryExt) RangeOptionalAttributes(cb block.OptionalAttributeCallback) {
	_ = "STUB: not implemented"
	return
}

// RangeOptionalAttributes indicates an expected call of RangeOptionalAttributes.
func (mr *MockEntryExtMockRecorder) RangeOptionalAttributes(cb any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
