// Code generated by MockGen. DO NOT EDIT.
// Source: block.go
//
// Generated by this command:
//
//	mockgen -source=block.go -destination=testing/mock_block.go -package=testing
//

// Package testing is a generated GoMock package.
package testing

import (
	context "context"

	vsr "github.com/vanus-labs/vanus/api/vsr"
	block "github.com/vanus-labs/vanus/server/store/block"
	gomock "go.uber.org/mock/gomock"
)

// MockSeeker is a mock of Seeker interface.
type MockSeeker struct {
	ctrl     *gomock.Controller
	recorder *MockSeekerMockRecorder
}

// MockSeekerMockRecorder is the mock recorder for MockSeeker.
type MockSeekerMockRecorder struct {
	mock *MockSeeker
}

// NewMockSeeker creates a new mock instance.
func NewMockSeeker(ctrl *gomock.Controller) *MockSeeker { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeeker) EXPECT() *MockSeekerMockRecorder {
	_ = "STUB: not implemented"

	// Seek mocks base method.
	return nil
}

func (m *MockSeeker) Seek(ctx context.Context, index int64, key block.Entry, flag block.SeekKeyFlag) (int64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// Seek indicates an expected call of Seek.
func (mr *MockSeekerMockRecorder) Seek(ctx, index, key, flag any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	_ = "STUB: not implemented"

	// Read mocks base method.
	return nil
}

func (m *MockReader) Read(ctx context.Context, seq int64, num int) ([]block.Entry, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Read indicates an expected call of Read.
func (mr *MockReaderMockRecorder) Read(ctx, seq, num any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockAppender is a mock of Appender interface.
type MockAppender struct {
	ctrl     *gomock.Controller
	recorder *MockAppenderMockRecorder
}

// MockAppenderMockRecorder is the mock recorder for MockAppender.
type MockAppenderMockRecorder struct {
	mock *MockAppender
}

// NewMockAppender creates a new mock instance.
func NewMockAppender(ctrl *gomock.Controller) *MockAppender { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppender) EXPECT() *MockAppenderMockRecorder {
	_ = "STUB: not implemented"

	// Append mocks base method.
	return nil
}

func (m *MockAppender) Append(ctx context.Context, entries []block.Entry, cb block.AppendCallback) {
	_ = "STUB: not implemented"
	return
}

// Append indicates an expected call of Append.
func (mr *MockAppenderMockRecorder) Append(ctx, entries, cb any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockBlock is a mock of Block interface.
type MockBlock struct {
	ctrl     *gomock.Controller
	recorder *MockBlockMockRecorder
}

// MockBlockMockRecorder is the mock recorder for MockBlock.
type MockBlockMockRecorder struct {
	mock *MockBlock
}

// NewMockBlock creates a new mock instance.
func NewMockBlock(ctrl *gomock.Controller) *MockBlock { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlock) EXPECT() *MockBlockMockRecorder {
	_ = "STUB: not implemented"

	// Append mocks base method.
	return nil
}

func (m *MockBlock) Append(ctx context.Context, entries []block.Entry, cb block.AppendCallback) {
	_ = "STUB: not implemented"
	return
}

// Append indicates an expected call of Append.
func (mr *MockBlockMockRecorder) Append(ctx, entries, cb any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ID mocks base method.
func (m *MockBlock) ID() vsr.ID { _ = "STUB: not implemented"; return *new(vsr.ID) }

// ID indicates an expected call of ID.
func (mr *MockBlockMockRecorder) ID() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Read mocks base method.
func (m *MockBlock) Read(ctx context.Context, seq int64, num int) ([]block.Entry, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Read indicates an expected call of Read.
func (mr *MockBlockMockRecorder) Read(ctx, seq, num any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Seek mocks base method.
func (m *MockBlock) Seek(ctx context.Context, index int64, key block.Entry, flag block.SeekKeyFlag) (int64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// Seek indicates an expected call of Seek.
func (mr *MockBlockMockRecorder) Seek(ctx, index, key, flag any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
