// Code generated by MockGen. DO NOT EDIT.
// Source: replica.go
//
// Generated by this command:
//
//	mockgen -source=replica.go -destination=mock_replica.go -package=segment
//

// Package segment is a generated GoMock package.
package segment

import (
	context "context"

	meta "github.com/vanus-labs/vanus/api/meta"
	vsr "github.com/vanus-labs/vanus/api/vsr"
	block "github.com/vanus-labs/vanus/server/store/block"
	block0 "github.com/vanus-labs/vanus/server/store/raft/block"
	gomock "go.uber.org/mock/gomock"
)

// MockReplica is a mock of Replica interface.
type MockReplica struct {
	ctrl     *gomock.Controller
	recorder *MockReplicaMockRecorder
}

// MockReplicaMockRecorder is the mock recorder for MockReplica.
type MockReplicaMockRecorder struct {
	mock *MockReplica
}

// NewMockReplica creates a new mock instance.
func NewMockReplica(ctrl *gomock.Controller) *MockReplica { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReplica) EXPECT() *MockReplicaMockRecorder {
	_ = "STUB: not implemented"

	// Append mocks base method.
	return nil
}

func (m *MockReplica) Append(ctx context.Context, entries []block.Entry, cb block.AppendCallback) {
	_ = "STUB: not implemented"
	return
}

// Append indicates an expected call of Append.
func (mr *MockReplicaMockRecorder) Append(ctx, entries, cb any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Bootstrap mocks base method.
func (m *MockReplica) Bootstrap(ctx context.Context, blocks []block0.Peer) error {
	_ = "STUB: not implemented"
	return nil
}

// Bootstrap indicates an expected call of Bootstrap.
func (mr *MockReplicaMockRecorder) Bootstrap(ctx, blocks any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Close mocks base method.
func (m *MockReplica) Close(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// Close indicates an expected call of Close.
func (mr *MockReplicaMockRecorder) Close(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Delete mocks base method.
func (m *MockReplica) Delete(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// Delete indicates an expected call of Delete.
func (mr *MockReplicaMockRecorder) Delete(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ID mocks base method.
func (m *MockReplica) ID() vsr.ID { _ = "STUB: not implemented"; return *new(vsr.ID) }

// ID indicates an expected call of ID.
func (mr *MockReplicaMockRecorder) ID() *gomock.Call { _ = "STUB: not implemented"; return nil }

// IDStr mocks base method.
func (m *MockReplica) IDStr() string { _ = "STUB: not implemented"; return "" }

// IDStr indicates an expected call of IDStr.
func (mr *MockReplicaMockRecorder) IDStr() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Read mocks base method.
func (m *MockReplica) Read(ctx context.Context, seq int64, num int) ([]block.Entry, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Read indicates an expected call of Read.
func (mr *MockReplicaMockRecorder) Read(ctx, seq, num any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Seek mocks base method.
func (m *MockReplica) Seek(ctx context.Context, index int64, key block.Entry, flag block.SeekKeyFlag) (int64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// Seek indicates an expected call of Seek.
func (mr *MockReplicaMockRecorder) Seek(ctx, index, key, flag any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Status mocks base method.
func (m *MockReplica) Status() *meta.SegmentHealthInfo { _ = "STUB: not implemented"; return nil }

// Status indicates an expected call of Status.
func (mr *MockReplicaMockRecorder) Status() *gomock.Call { _ = "STUB: not implemented"; return nil }
