// Code generated by MockGen. DO NOT EDIT.
// Source: server.go
//
// Generated by this command:
//
//	mockgen -source=server.go -destination=mock_server.go -package=segment
//

// Package segment is a generated GoMock package.
package segment

import (
	context "context"
	net "net"

	cloudevents "github.com/vanus-labs/vanus/api/cloudevents"
	meta "github.com/vanus-labs/vanus/api/meta"
	vsr "github.com/vanus-labs/vanus/api/vsr"
	pkg "github.com/vanus-labs/vanus/pkg"
	gomock "go.uber.org/mock/gomock"
)

// MockServer is a mock of Server interface.
type MockServer struct {
	ctrl     *gomock.Controller
	recorder *MockServerMockRecorder
}

// MockServerMockRecorder is the mock recorder for MockServer.
type MockServerMockRecorder struct {
	mock *MockServer
}

// NewMockServer creates a new mock instance.
func NewMockServer(ctrl *gomock.Controller) *MockServer { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServer) EXPECT() *MockServerMockRecorder {
	_ = "STUB: not implemented"

	// ActivateSegment mocks base method.
	return nil
}

func (m *MockServer) ActivateSegment(ctx context.Context, logID, segID vsr.ID, replicas map[vsr.ID]string) error {
	_ = "STUB: not implemented"
	return nil
}

// ActivateSegment indicates an expected call of ActivateSegment.
func (mr *MockServerMockRecorder) ActivateSegment(ctx, logID, segID, replicas any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// AppendToBlock mocks base method.
func (m *MockServer) AppendToBlock(ctx context.Context, id vsr.ID, events []*cloudevents.CloudEvent) ([]int64, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AppendToBlock indicates an expected call of AppendToBlock.
func (mr *MockServerMockRecorder) AppendToBlock(ctx, id, events any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// CreateBlock mocks base method.
func (m *MockServer) CreateBlock(ctx context.Context, id vsr.ID, size int64) error {
	_ = "STUB: not implemented"
	return nil
}

// CreateBlock indicates an expected call of CreateBlock.
func (mr *MockServerMockRecorder) CreateBlock(ctx, id, size any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DescribeBlock mocks base method.
func (m *MockServer) DescribeBlock(ctx context.Context, id vsr.ID) (*meta.SegmentHealthInfo, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DescribeBlock indicates an expected call of DescribeBlock.
func (mr *MockServerMockRecorder) DescribeBlock(ctx, id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// InactivateSegment mocks base method.
func (m *MockServer) InactivateSegment(ctx context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// InactivateSegment indicates an expected call of InactivateSegment.
func (mr *MockServerMockRecorder) InactivateSegment(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Initialize mocks base method.
func (m *MockServer) Initialize(arg0 context.Context) error { _ = "STUB: not implemented"; return nil }

// Initialize indicates an expected call of Initialize.
func (mr *MockServerMockRecorder) Initialize(arg0 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// LookupOffsetInBlock mocks base method.
func (m *MockServer) LookupOffsetInBlock(ctx context.Context, id vsr.ID, stime int64) (int64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// LookupOffsetInBlock indicates an expected call of LookupOffsetInBlock.
func (mr *MockServerMockRecorder) LookupOffsetInBlock(ctx, id, stime any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ReadFromBlock mocks base method.
func (m *MockServer) ReadFromBlock(ctx context.Context, id vsr.ID, seq int64, num int, pollingTimeout uint32) ([]*cloudevents.CloudEvent, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ReadFromBlock indicates an expected call of ReadFromBlock.
func (mr *MockServerMockRecorder) ReadFromBlock(ctx, id, seq, num, pollingTimeout any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RegisterToController mocks base method.
func (m *MockServer) RegisterToController(ctx context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// RegisterToController indicates an expected call of RegisterToController.
func (mr *MockServerMockRecorder) RegisterToController(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoveBlock mocks base method.
func (m *MockServer) RemoveBlock(ctx context.Context, id vsr.ID) error {
	_ = "STUB: not implemented"
	return nil
}

// RemoveBlock indicates an expected call of RemoveBlock.
func (mr *MockServerMockRecorder) RemoveBlock(ctx, id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Serve mocks base method.
func (m *MockServer) Serve(lis net.Listener) error { _ = "STUB: not implemented"; return nil }

// Serve indicates an expected call of Serve.
func (mr *MockServerMockRecorder) Serve(lis any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Start mocks base method.
func (m *MockServer) Start(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// Start indicates an expected call of Start.
func (mr *MockServerMockRecorder) Start(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Status mocks base method.
func (m *MockServer) Status() pkg.ServerState {
	_ = "STUB: not implemented"
	return *new(pkg.ServerState)
}

// Status indicates an expected call of Status.
func (mr *MockServerMockRecorder) Status() *gomock.Call { _ = "STUB: not implemented"; return nil }

// Stop mocks base method.
func (m *MockServer) Stop(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// Stop indicates an expected call of Stop.
func (mr *MockServerMockRecorder) Stop(ctx any) *gomock.Call { _ = "STUB: not implemented"; return nil }
