// Copyright 2022 Linkall Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: vanus/core/trigger/trigger.proto

package trigger

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TriggerWorker_Start_FullMethodName              = "/vanus.core.trigger.TriggerWorker/Start"
	TriggerWorker_Stop_FullMethodName               = "/vanus.core.trigger.TriggerWorker/Stop"
	TriggerWorker_AddSubscription_FullMethodName    = "/vanus.core.trigger.TriggerWorker/AddSubscription"
	TriggerWorker_RemoveSubscription_FullMethodName = "/vanus.core.trigger.TriggerWorker/RemoveSubscription"
	TriggerWorker_PauseSubscription_FullMethodName  = "/vanus.core.trigger.TriggerWorker/PauseSubscription"
	TriggerWorker_ResumeSubscription_FullMethodName = "/vanus.core.trigger.TriggerWorker/ResumeSubscription"
)

// TriggerWorkerClient is the client API for TriggerWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TriggerWorkerClient interface {
	Start(ctx context.Context, in *StartTriggerWorkerRequest, opts ...grpc.CallOption) (*StartTriggerWorkerResponse, error)
	Stop(ctx context.Context, in *StopTriggerWorkerRequest, opts ...grpc.CallOption) (*StopTriggerWorkerResponse, error)
	AddSubscription(ctx context.Context, in *AddSubscriptionRequest, opts ...grpc.CallOption) (*AddSubscriptionResponse, error)
	RemoveSubscription(ctx context.Context, in *RemoveSubscriptionRequest, opts ...grpc.CallOption) (*RemoveSubscriptionResponse, error)
	PauseSubscription(ctx context.Context, in *PauseSubscriptionRequest, opts ...grpc.CallOption) (*PauseSubscriptionResponse, error)
	ResumeSubscription(ctx context.Context, in *ResumeSubscriptionRequest, opts ...grpc.CallOption) (*ResumeSubscriptionResponse, error)
}

type triggerWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewTriggerWorkerClient(cc grpc.ClientConnInterface) TriggerWorkerClient {
	_ = "STUB: not implemented"
	return *new(TriggerWorkerClient)
}

func (c *triggerWorkerClient) Start(ctx context.Context, in *StartTriggerWorkerRequest, opts ...grpc.CallOption) (*StartTriggerWorkerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *triggerWorkerClient) Stop(ctx context.Context, in *StopTriggerWorkerRequest, opts ...grpc.CallOption) (*StopTriggerWorkerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *triggerWorkerClient) AddSubscription(ctx context.Context, in *AddSubscriptionRequest, opts ...grpc.CallOption) (*AddSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *triggerWorkerClient) RemoveSubscription(ctx context.Context, in *RemoveSubscriptionRequest, opts ...grpc.CallOption) (*RemoveSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *triggerWorkerClient) PauseSubscription(ctx context.Context, in *PauseSubscriptionRequest, opts ...grpc.CallOption) (*PauseSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *triggerWorkerClient) ResumeSubscription(ctx context.Context, in *ResumeSubscriptionRequest, opts ...grpc.CallOption) (*ResumeSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TriggerWorkerServer is the server API for TriggerWorker service.
// All implementations should embed UnimplementedTriggerWorkerServer
// for forward compatibility
type TriggerWorkerServer interface {
	Start(context.Context, *StartTriggerWorkerRequest) (*StartTriggerWorkerResponse, error)
	Stop(context.Context, *StopTriggerWorkerRequest) (*StopTriggerWorkerResponse, error)
	AddSubscription(context.Context, *AddSubscriptionRequest) (*AddSubscriptionResponse, error)
	RemoveSubscription(context.Context, *RemoveSubscriptionRequest) (*RemoveSubscriptionResponse, error)
	PauseSubscription(context.Context, *PauseSubscriptionRequest) (*PauseSubscriptionResponse, error)
	ResumeSubscription(context.Context, *ResumeSubscriptionRequest) (*ResumeSubscriptionResponse, error)
}

// UnimplementedTriggerWorkerServer should be embedded to have forward compatible implementations.
type UnimplementedTriggerWorkerServer struct {
}

func (UnimplementedTriggerWorkerServer) Start(context.Context, *StartTriggerWorkerRequest) (*StartTriggerWorkerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTriggerWorkerServer) Stop(context.Context, *StopTriggerWorkerRequest) (*StopTriggerWorkerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTriggerWorkerServer) AddSubscription(context.Context, *AddSubscriptionRequest) (*AddSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTriggerWorkerServer) RemoveSubscription(context.Context, *RemoveSubscriptionRequest) (*RemoveSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTriggerWorkerServer) PauseSubscription(context.Context, *PauseSubscriptionRequest) (*PauseSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedTriggerWorkerServer) ResumeSubscription(context.Context, *ResumeSubscriptionRequest) (*ResumeSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnsafeTriggerWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TriggerWorkerServer will
// result in compilation errors.
type UnsafeTriggerWorkerServer interface {
	mustEmbedUnimplementedTriggerWorkerServer()
}

func RegisterTriggerWorkerServer(s grpc.ServiceRegistrar, srv TriggerWorkerServer) {
	_ = "STUB: not implemented"
	return
}

func _TriggerWorker_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TriggerWorker_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TriggerWorker_AddSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TriggerWorker_RemoveSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TriggerWorker_PauseSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _TriggerWorker_ResumeSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// TriggerWorker_ServiceDesc is the grpc.ServiceDesc for TriggerWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TriggerWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vanus.core.trigger.TriggerWorker",
	HandlerType: (*TriggerWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _TriggerWorker_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _TriggerWorker_Stop_Handler,
		},
		{
			MethodName: "AddSubscription",
			Handler:    _TriggerWorker_AddSubscription_Handler,
		},
		{
			MethodName: "RemoveSubscription",
			Handler:    _TriggerWorker_RemoveSubscription_Handler,
		},
		{
			MethodName: "PauseSubscription",
			Handler:    _TriggerWorker_PauseSubscription_Handler,
		},
		{
			MethodName: "ResumeSubscription",
			Handler:    _TriggerWorker_ResumeSubscription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vanus/core/trigger/trigger.proto",
}
