// Code generated by protoc-gen-go-grpc-mock. DO NOT EDIT.
// source: vanus/core/trigger/trigger.proto

package trigger

import (
	context "context"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockTriggerWorkerClient is a mock of TriggerWorkerClient interface.
type MockTriggerWorkerClient struct {
	ctrl     *gomock.Controller
	recorder *MockTriggerWorkerClientMockRecorder
}

// MockTriggerWorkerClientMockRecorder is the mock recorder for MockTriggerWorkerClient.
type MockTriggerWorkerClientMockRecorder struct {
	mock *MockTriggerWorkerClient
}

// NewMockTriggerWorkerClient creates a new mock instance.
func NewMockTriggerWorkerClient(ctrl *gomock.Controller) *MockTriggerWorkerClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTriggerWorkerClient) EXPECT() *MockTriggerWorkerClientMockRecorder {
	_ = "STUB: not implemented"

	// AddSubscription mocks base method.
	return nil
}

func (m *MockTriggerWorkerClient) AddSubscription(ctx context.Context, in *AddSubscriptionRequest, opts ...grpc.CallOption) (*AddSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AddSubscription indicates an expected call of AddSubscription.
func (mr *MockTriggerWorkerClientMockRecorder) AddSubscription(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PauseSubscription mocks base method.
func (m *MockTriggerWorkerClient) PauseSubscription(ctx context.Context, in *PauseSubscriptionRequest, opts ...grpc.CallOption) (*PauseSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PauseSubscription indicates an expected call of PauseSubscription.
func (mr *MockTriggerWorkerClientMockRecorder) PauseSubscription(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoveSubscription mocks base method.
func (m *MockTriggerWorkerClient) RemoveSubscription(ctx context.Context, in *RemoveSubscriptionRequest, opts ...grpc.CallOption) (*RemoveSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RemoveSubscription indicates an expected call of RemoveSubscription.
func (mr *MockTriggerWorkerClientMockRecorder) RemoveSubscription(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResumeSubscription mocks base method.
func (m *MockTriggerWorkerClient) ResumeSubscription(ctx context.Context, in *ResumeSubscriptionRequest, opts ...grpc.CallOption) (*ResumeSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ResumeSubscription indicates an expected call of ResumeSubscription.
func (mr *MockTriggerWorkerClientMockRecorder) ResumeSubscription(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Start mocks base method.
func (m *MockTriggerWorkerClient) Start(ctx context.Context, in *StartTriggerWorkerRequest, opts ...grpc.CallOption) (*StartTriggerWorkerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Start indicates an expected call of Start.
func (mr *MockTriggerWorkerClientMockRecorder) Start(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Stop mocks base method.
func (m *MockTriggerWorkerClient) Stop(ctx context.Context, in *StopTriggerWorkerRequest, opts ...grpc.CallOption) (*StopTriggerWorkerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Stop indicates an expected call of Stop.
func (mr *MockTriggerWorkerClientMockRecorder) Stop(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockTriggerWorkerServer is a mock of TriggerWorkerServer interface.
type MockTriggerWorkerServer struct {
	ctrl     *gomock.Controller
	recorder *MockTriggerWorkerServerMockRecorder
}

// MockTriggerWorkerServerMockRecorder is the mock recorder for MockTriggerWorkerServer.
type MockTriggerWorkerServerMockRecorder struct {
	mock *MockTriggerWorkerServer
}

// NewMockTriggerWorkerServer creates a new mock instance.
func NewMockTriggerWorkerServer(ctrl *gomock.Controller) *MockTriggerWorkerServer {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTriggerWorkerServer) EXPECT() *MockTriggerWorkerServerMockRecorder {
	_ = "STUB: not implemented"

	// AddSubscription mocks base method.
	return nil
}

func (m *MockTriggerWorkerServer) AddSubscription(ctx context.Context, in *AddSubscriptionRequest) (*AddSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// AddSubscription indicates an expected call of AddSubscription.
func (mr *MockTriggerWorkerServerMockRecorder) AddSubscription(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PauseSubscription mocks base method.
func (m *MockTriggerWorkerServer) PauseSubscription(ctx context.Context, in *PauseSubscriptionRequest) (*PauseSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PauseSubscription indicates an expected call of PauseSubscription.
func (mr *MockTriggerWorkerServerMockRecorder) PauseSubscription(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoveSubscription mocks base method.
func (m *MockTriggerWorkerServer) RemoveSubscription(ctx context.Context, in *RemoveSubscriptionRequest) (*RemoveSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// RemoveSubscription indicates an expected call of RemoveSubscription.
func (mr *MockTriggerWorkerServerMockRecorder) RemoveSubscription(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ResumeSubscription mocks base method.
func (m *MockTriggerWorkerServer) ResumeSubscription(ctx context.Context, in *ResumeSubscriptionRequest) (*ResumeSubscriptionResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ResumeSubscription indicates an expected call of ResumeSubscription.
func (mr *MockTriggerWorkerServerMockRecorder) ResumeSubscription(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Start mocks base method.
func (m *MockTriggerWorkerServer) Start(ctx context.Context, in *StartTriggerWorkerRequest) (*StartTriggerWorkerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Start indicates an expected call of Start.
func (mr *MockTriggerWorkerServerMockRecorder) Start(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Stop mocks base method.
func (m *MockTriggerWorkerServer) Stop(ctx context.Context, in *StopTriggerWorkerRequest) (*StopTriggerWorkerResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Stop indicates an expected call of Stop.
func (mr *MockTriggerWorkerServerMockRecorder) Stop(ctx, in interface{}) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
