// Code generated by MockGen. DO NOT EDIT.
// Source: trigger.go
//
// Generated by this command:
//
//	mockgen -source=trigger.go -destination=mock_trigger.go -package=trigger
//

// Package trigger is a generated GoMock package.
package trigger

import (
	context "context"

	pkg "github.com/vanus-labs/vanus/pkg"
	info "github.com/vanus-labs/vanus/pkg/info"
	gomock "go.uber.org/mock/gomock"
)

// MockTrigger is a mock of Trigger interface.
type MockTrigger struct {
	ctrl     *gomock.Controller
	recorder *MockTriggerMockRecorder
}

// MockTriggerMockRecorder is the mock recorder for MockTrigger.
type MockTriggerMockRecorder struct {
	mock *MockTrigger
}

// NewMockTrigger creates a new mock instance.
func NewMockTrigger(ctrl *gomock.Controller) *MockTrigger { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrigger) EXPECT() *MockTriggerMockRecorder {
	_ = "STUB: not implemented"

	// Change mocks base method.
	return nil
}

func (m *MockTrigger) Change(ctx context.Context, subscription *pkg.Subscription) error {
	_ = "STUB: not implemented"
	return nil
}

// Change indicates an expected call of Change.
func (mr *MockTriggerMockRecorder) Change(ctx, subscription any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetOffsets mocks base method.
func (m *MockTrigger) GetOffsets(ctx context.Context) info.ListOffsetInfo {
	_ = "STUB: not implemented"
	return *new(info.ListOffsetInfo)
}

// GetOffsets indicates an expected call of GetOffsets.
func (mr *MockTriggerMockRecorder) GetOffsets(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Init mocks base method.
func (m *MockTrigger) Init(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// Init indicates an expected call of Init.
func (mr *MockTriggerMockRecorder) Init(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Start mocks base method.
func (m *MockTrigger) Start(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// Start indicates an expected call of Start.
func (mr *MockTriggerMockRecorder) Start(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Stop mocks base method.
func (m *MockTrigger) Stop(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// Stop indicates an expected call of Stop.
func (mr *MockTriggerMockRecorder) Stop(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
