// Code generated by MockGen. DO NOT EDIT.
// Source: leaderelection.go
//
// Generated by this command:
//
//	mockgen -source=leaderelection.go -destination=mock_leaderelection.go -package=leaderelection
//

// Package leaderelection is a generated GoMock package.
package leaderelection

import (
	context "context"

	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	_ = "STUB: not implemented"

	// Start mocks base method.
	return nil
}

func (m *MockManager) Start(ctx context.Context, callbacks LeaderCallbacks) error {
	_ = "STUB: not implemented"
	return nil
}

// Start indicates an expected call of Start.
func (mr *MockManagerMockRecorder) Start(ctx, callbacks any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Stop mocks base method.
func (m *MockManager) Stop(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// Stop indicates an expected call of Stop.
func (mr *MockManagerMockRecorder) Stop(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockMutex is a mock of Mutex interface.
type MockMutex struct {
	ctrl     *gomock.Controller
	recorder *MockMutexMockRecorder
}

// MockMutexMockRecorder is the mock recorder for MockMutex.
type MockMutexMockRecorder struct {
	mock *MockMutex
}

// NewMockMutex creates a new mock instance.
func NewMockMutex(ctrl *gomock.Controller) *MockMutex { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMutex) EXPECT() *MockMutexMockRecorder {
	_ = "STUB: not implemented"

	// TryLock mocks base method.
	return nil
}

func (m *MockMutex) TryLock(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// TryLock indicates an expected call of TryLock.
func (mr *MockMutexMockRecorder) TryLock(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Unlock mocks base method.
func (m *MockMutex) Unlock(ctx context.Context) error { _ = "STUB: not implemented"; return nil }

// Unlock indicates an expected call of Unlock.
func (mr *MockMutexMockRecorder) Unlock(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
