// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client.go -package=authentication
//

// Package authentication is a generated GoMock package.
package authentication

import (
	context "context"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenClient is a mock of TokenClient interface.
type MockTokenClient struct {
	ctrl     *gomock.Controller
	recorder *MockTokenClientMockRecorder
}

// MockTokenClientMockRecorder is the mock recorder for MockTokenClient.
type MockTokenClientMockRecorder struct {
	mock *MockTokenClient
}

// NewMockTokenClient creates a new mock instance.
func NewMockTokenClient(ctrl *gomock.Controller) *MockTokenClient {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenClient) EXPECT() *MockTokenClientMockRecorder {
	_ = "STUB: not implemented"

	// GetUser mocks base method.
	return nil
}

func (m *MockTokenClient) GetUser(ctx context.Context, token string) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

// GetUser indicates an expected call of GetUser.
func (mr *MockTokenClientMockRecorder) GetUser(ctx, token any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
