// Code generated by MockGen. DO NOT EDIT.
// Source: trigger_worker.go
//
// Generated by this command:
//
//	mockgen -source=trigger_worker.go -destination=mock_trigger_worker.go -package=storage
//

// Package storage is a generated GoMock package.
package storage

import (
	context "context"

	metadata "github.com/vanus-labs/vanus/server/controller/trigger/metadata"
	gomock "go.uber.org/mock/gomock"
)

// MockTriggerWorkerStorage is a mock of TriggerWorkerStorage interface.
type MockTriggerWorkerStorage struct {
	ctrl     *gomock.Controller
	recorder *MockTriggerWorkerStorageMockRecorder
}

// MockTriggerWorkerStorageMockRecorder is the mock recorder for MockTriggerWorkerStorage.
type MockTriggerWorkerStorageMockRecorder struct {
	mock *MockTriggerWorkerStorage
}

// NewMockTriggerWorkerStorage creates a new mock instance.
func NewMockTriggerWorkerStorage(ctrl *gomock.Controller) *MockTriggerWorkerStorage {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTriggerWorkerStorage) EXPECT() *MockTriggerWorkerStorageMockRecorder {
	_ = "STUB: not implemented"

	// DeleteTriggerWorker mocks base method.
	return nil
}

func (m *MockTriggerWorkerStorage) DeleteTriggerWorker(ctx context.Context, id string) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteTriggerWorker indicates an expected call of DeleteTriggerWorker.
func (mr *MockTriggerWorkerStorageMockRecorder) DeleteTriggerWorker(ctx, id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetTriggerWorker mocks base method.
func (m *MockTriggerWorkerStorage) GetTriggerWorker(ctx context.Context, id string) (*metadata.TriggerWorkerInfo, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetTriggerWorker indicates an expected call of GetTriggerWorker.
func (mr *MockTriggerWorkerStorageMockRecorder) GetTriggerWorker(ctx, id any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListTriggerWorker mocks base method.
func (m *MockTriggerWorkerStorage) ListTriggerWorker(ctx context.Context) ([]*metadata.TriggerWorkerInfo, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListTriggerWorker indicates an expected call of ListTriggerWorker.
func (mr *MockTriggerWorkerStorageMockRecorder) ListTriggerWorker(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// SaveTriggerWorker mocks base method.
func (m *MockTriggerWorkerStorage) SaveTriggerWorker(arg0 context.Context, arg1 metadata.TriggerWorkerInfo) error {
	_ = "STUB: not implemented"
	return nil
}

// SaveTriggerWorker indicates an expected call of SaveTriggerWorker.
func (mr *MockTriggerWorkerStorageMockRecorder) SaveTriggerWorker(arg0, arg1 any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
