// Code generated by MockGen. DO NOT EDIT.
// Source: offset.go
//
// Generated by this command:
//
//	mockgen -source=offset.go -destination=mock_offset.go -package=storage
//

// Package storage is a generated GoMock package.
package storage

import (
	context "context"

	vsr "github.com/vanus-labs/vanus/api/vsr"
	info "github.com/vanus-labs/vanus/pkg/info"
	gomock "go.uber.org/mock/gomock"
)

// MockOffsetStorage is a mock of OffsetStorage interface.
type MockOffsetStorage struct {
	ctrl     *gomock.Controller
	recorder *MockOffsetStorageMockRecorder
}

// MockOffsetStorageMockRecorder is the mock recorder for MockOffsetStorage.
type MockOffsetStorageMockRecorder struct {
	mock *MockOffsetStorage
}

// NewMockOffsetStorage creates a new mock instance.
func NewMockOffsetStorage(ctrl *gomock.Controller) *MockOffsetStorage {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOffsetStorage) EXPECT() *MockOffsetStorageMockRecorder {
	_ = "STUB: not implemented"

	// CreateOffset mocks base method.
	return nil
}

func (m *MockOffsetStorage) CreateOffset(ctx context.Context, subscriptionID vsr.ID, info info.OffsetInfo) error {
	_ = "STUB: not implemented"
	return nil
}

// CreateOffset indicates an expected call of CreateOffset.
func (mr *MockOffsetStorageMockRecorder) CreateOffset(ctx, subscriptionID, info any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// DeleteOffset mocks base method.
func (m *MockOffsetStorage) DeleteOffset(ctx context.Context, subscriptionID vsr.ID) error {
	_ = "STUB: not implemented"
	return nil
}

// DeleteOffset indicates an expected call of DeleteOffset.
func (mr *MockOffsetStorageMockRecorder) DeleteOffset(ctx, subscriptionID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetOffsets mocks base method.
func (m *MockOffsetStorage) GetOffsets(ctx context.Context, subscriptionID vsr.ID) (info.ListOffsetInfo, error) {
	_ = "STUB: not implemented"
	return *new(info.ListOffsetInfo), nil
}

// GetOffsets indicates an expected call of GetOffsets.
func (mr *MockOffsetStorageMockRecorder) GetOffsets(ctx, subscriptionID any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// UpdateOffset mocks base method.
func (m *MockOffsetStorage) UpdateOffset(ctx context.Context, subscriptionID vsr.ID, info info.OffsetInfo) error {
	_ = "STUB: not implemented"
	return nil
}

// UpdateOffset indicates an expected call of UpdateOffset.
func (mr *MockOffsetStorageMockRecorder) UpdateOffset(ctx, subscriptionID, info any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
