// Code generated by MockGen. DO NOT EDIT.
// Source: block.go
//
// Generated by this command:
//
//	mockgen -source=block.go -destination=mock_block.go -package=block
//

// Package block is a generated GoMock package.
package block

import (
	context "context"

	vsr "github.com/vanus-labs/vanus/api/vsr"
	kv "github.com/vanus-labs/vanus/pkg/kv"
	metadata "github.com/vanus-labs/vanus/server/controller/eventbus/metadata"
	gomock "go.uber.org/mock/gomock"
)

// MockAllocator is a mock of Allocator interface.
type MockAllocator struct {
	ctrl     *gomock.Controller
	recorder *MockAllocatorMockRecorder
}

// MockAllocatorMockRecorder is the mock recorder for MockAllocator.
type MockAllocatorMockRecorder struct {
	mock *MockAllocator
}

// NewMockAllocator creates a new mock instance.
func NewMockAllocator(ctrl *gomock.Controller) *MockAllocator {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllocator) EXPECT() *MockAllocatorMockRecorder {
	_ = "STUB: not implemented"

	// Pick mocks base method.
	return nil
}

func (m *MockAllocator) Pick(ctx context.Context, num int) ([]*metadata.Block, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Pick indicates an expected call of Pick.
func (mr *MockAllocatorMockRecorder) Pick(ctx, num any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// PickByVolumes mocks base method.
func (m *MockAllocator) PickByVolumes(ctx context.Context, volumes []vsr.ID) ([]*metadata.Block, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// PickByVolumes indicates an expected call of PickByVolumes.
func (mr *MockAllocatorMockRecorder) PickByVolumes(ctx, volumes any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Run mocks base method.
func (m *MockAllocator) Run(ctx context.Context, kvCli kv.Client, dynamicAllocate bool) error {
	_ = "STUB: not implemented"
	return nil
}

// Run indicates an expected call of Run.
func (mr *MockAllocatorMockRecorder) Run(ctx, kvCli, dynamicAllocate any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Stop mocks base method.
func (m *MockAllocator) Stop() { _ = "STUB: not implemented"; return }

// Stop indicates an expected call of Stop.
func (mr *MockAllocatorMockRecorder) Stop() *gomock.Call { _ = "STUB: not implemented"; return nil }
