// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock_client.go -package=api
//

// Package api is a generated GoMock package.
package api

import (
	context "context"

	cloudevents "github.com/vanus-labs/vanus/api/cloudevents"
	gomock "go.uber.org/mock/gomock"
)

// MockEventbus is a mock of Eventbus interface.
type MockEventbus struct {
	ctrl     *gomock.Controller
	recorder *MockEventbusMockRecorder
}

// MockEventbusMockRecorder is the mock recorder for MockEventbus.
type MockEventbusMockRecorder struct {
	mock *MockEventbus
}

// NewMockEventbus creates a new mock instance.
func NewMockEventbus(ctrl *gomock.Controller) *MockEventbus { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventbus) EXPECT() *MockEventbusMockRecorder {
	_ = "STUB: not implemented"

	// CheckHealth mocks base method.
	return nil
}

func (m *MockEventbus) CheckHealth(ctx context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// CheckHealth indicates an expected call of CheckHealth.
func (mr *MockEventbusMockRecorder) CheckHealth(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Close mocks base method.
func (m *MockEventbus) Close(ctx context.Context) { _ = "STUB: not implemented"; return }

// Close indicates an expected call of Close.
func (mr *MockEventbusMockRecorder) Close(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetLog mocks base method.
func (m *MockEventbus) GetLog(ctx context.Context, logID uint64, opts ...LogOption) (Eventlog, error) {
	_ = "STUB: not implemented"
	return *new(Eventlog), nil
}

// GetLog indicates an expected call of GetLog.
func (mr *MockEventbusMockRecorder) GetLog(ctx, logID any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ListLog mocks base method.
func (m *MockEventbus) ListLog(ctx context.Context, opts ...LogOption) ([]Eventlog, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ListLog indicates an expected call of ListLog.
func (mr *MockEventbusMockRecorder) ListLog(ctx any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Reader mocks base method.
func (m *MockEventbus) Reader(opts ...ReadOption) BusReader {
	_ = "STUB: not implemented"
	return *new(BusReader)
}

// Reader indicates an expected call of Reader.
func (mr *MockEventbusMockRecorder) Reader(opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Writer mocks base method.
func (m *MockEventbus) Writer(opts ...WriteOption) BusWriter {
	_ = "STUB: not implemented"
	return *new(BusWriter)
}

// Writer indicates an expected call of Writer.
func (mr *MockEventbusMockRecorder) Writer(opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockBusWriter is a mock of BusWriter interface.
type MockBusWriter struct {
	ctrl     *gomock.Controller
	recorder *MockBusWriterMockRecorder
}

// MockBusWriterMockRecorder is the mock recorder for MockBusWriter.
type MockBusWriterMockRecorder struct {
	mock *MockBusWriter
}

// NewMockBusWriter creates a new mock instance.
func NewMockBusWriter(ctrl *gomock.Controller) *MockBusWriter {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBusWriter) EXPECT() *MockBusWriterMockRecorder {
	_ = "STUB: not implemented"

	// Append mocks base method.
	return nil
}

func (m *MockBusWriter) Append(ctx context.Context, events *cloudevents.CloudEventBatch, opts ...WriteOption) ([]string, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// Append indicates an expected call of Append.
func (mr *MockBusWriterMockRecorder) Append(ctx, events any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockBusReader is a mock of BusReader interface.
type MockBusReader struct {
	ctrl     *gomock.Controller
	recorder *MockBusReaderMockRecorder
}

// MockBusReaderMockRecorder is the mock recorder for MockBusReader.
type MockBusReaderMockRecorder struct {
	mock *MockBusReader
}

// NewMockBusReader creates a new mock instance.
func NewMockBusReader(ctrl *gomock.Controller) *MockBusReader {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBusReader) EXPECT() *MockBusReaderMockRecorder {
	_ = "STUB: not implemented"

	// Read mocks base method.
	return nil
}

func (m *MockBusReader) Read(ctx context.Context, opts ...ReadOption) (*cloudevents.CloudEventBatch, int64, uint64, error) {
	_ = "STUB: not implemented"
	return nil, 0, 0, nil
}

// Read indicates an expected call of Read.
func (mr *MockBusReaderMockRecorder) Read(ctx any, opts ...any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// MockEventlog is a mock of Eventlog interface.
type MockEventlog struct {
	ctrl     *gomock.Controller
	recorder *MockEventlogMockRecorder
}

// MockEventlogMockRecorder is the mock recorder for MockEventlog.
type MockEventlogMockRecorder struct {
	mock *MockEventlog
}

// NewMockEventlog creates a new mock instance.
func NewMockEventlog(ctrl *gomock.Controller) *MockEventlog { _ = "STUB: not implemented"; return nil }

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventlog) EXPECT() *MockEventlogMockRecorder {
	_ = "STUB: not implemented"

	// CheckHealth mocks base method.
	return nil
}

func (m *MockEventlog) CheckHealth(ctx context.Context) error {
	_ = "STUB: not implemented"
	return nil
}

// CheckHealth indicates an expected call of CheckHealth.
func (mr *MockEventlogMockRecorder) CheckHealth(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// EarliestOffset mocks base method.
func (m *MockEventlog) EarliestOffset(ctx context.Context) (int64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// EarliestOffset indicates an expected call of EarliestOffset.
func (mr *MockEventlogMockRecorder) EarliestOffset(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// ID mocks base method.
func (m *MockEventlog) ID() uint64 { _ = "STUB: not implemented"; return 0 }

// ID indicates an expected call of ID.
func (mr *MockEventlogMockRecorder) ID() *gomock.Call { _ = "STUB: not implemented"; return nil }

// LatestOffset mocks base method.
func (m *MockEventlog) LatestOffset(ctx context.Context) (int64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// LatestOffset indicates an expected call of LatestOffset.
func (mr *MockEventlogMockRecorder) LatestOffset(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// Length mocks base method.
func (m *MockEventlog) Length(ctx context.Context) (int64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// Length indicates an expected call of Length.
func (mr *MockEventlogMockRecorder) Length(ctx any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// QueryOffsetByTime mocks base method.
func (m *MockEventlog) QueryOffsetByTime(ctx context.Context, timestamp int64) (int64, error) {
	_ = "STUB: not implemented"
	return 0, nil
}

// QueryOffsetByTime indicates an expected call of QueryOffsetByTime.
func (mr *MockEventlogMockRecorder) QueryOffsetByTime(ctx, timestamp any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
