// Code generated by MockGen. DO NOT EDIT.
// Source: snapshot_storage.go
//
// Generated by this command:
//
//	mockgen -source=snapshot_storage.go -destination=mock_snapshot_storage.go -package=storage
//

// Package storage is a generated GoMock package.
package storage

import (
	gomock "go.uber.org/mock/gomock"
)

// MockSnapshotOperator is a mock of SnapshotOperator interface.
type MockSnapshotOperator struct {
	ctrl     *gomock.Controller
	recorder *MockSnapshotOperatorMockRecorder
}

// MockSnapshotOperatorMockRecorder is the mock recorder for MockSnapshotOperator.
type MockSnapshotOperatorMockRecorder struct {
	mock *MockSnapshotOperator
}

// NewMockSnapshotOperator creates a new mock instance.
func NewMockSnapshotOperator(ctrl *gomock.Controller) *MockSnapshotOperator {
	_ = "STUB: not implemented"
	return nil
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnapshotOperator) EXPECT() *MockSnapshotOperatorMockRecorder {
	_ = "STUB: not implemented"

	// ApplySnapshot mocks base method.
	return nil
}

func (m *MockSnapshotOperator) ApplySnapshot(data []byte) error {
	_ = "STUB: not implemented"
	return nil
}

// ApplySnapshot indicates an expected call of ApplySnapshot.
func (mr *MockSnapshotOperatorMockRecorder) ApplySnapshot(data any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}

// GetSnapshot mocks base method.
func (m *MockSnapshotOperator) GetSnapshot(index uint64) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// GetSnapshot indicates an expected call of GetSnapshot.
func (mr *MockSnapshotOperatorMockRecorder) GetSnapshot(index any) *gomock.Call {
	_ = "STUB: not implemented"
	return nil
}
